const fs = require('fs');
const path = require('path');

const tnFilePath = path.join(__dirname, '../src/data/tamilnaduTemples.js');
let tnContent = fs.readFileSync(tnFilePath, 'utf8');

const newTemplesCode = `
  // ─── TIRUCHIRAPPALLI DISTRICT (Wikipedia & Sacred Sthalams) ─────────────────
  {
    id: 'brahmapureeswarar-thiruppattur',
    name: 'Brahmapureeswarar Temple, Thiruppattur',
    city: 'Thiruppattur, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 11.0267,
    lng: 78.7368,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Brahmapureeswarar_Temple%2C_Tirupattur.jpg/800px-Brahmapureeswarar_Temple%2C_Tirupattur.jpg',
    period: 'Ancient Chola-era origin; 7th–10th Century CE',
    category: 'Shiva',
    designation: 'Destiny Altering Temple (Vidhi Mattrum Sthalam)',
    history: 'Brahmapureeswarar Temple in Thiruppattur is a celebrated shrine where Lord Shiva restored the pride and creative power of Lord Brahma. Legend says Lord Shiva severed Brahma\\'s fifth head and stripped Him of creation power due to ego; Brahma underwent intense penance here installing 12 Shiva lingams. Pleased, Shiva (Brahmapureeswarar) granted Brahma the power to rewrite the destiny (Vidhi) of devotees visiting this shrine. The temple houses a magnificent 6-foot tall idol of Lord Brahma in meditative lotus posture.',
    timings: 'Morning: 7:00 AM – 12:00 PM | Evening: 4:30 PM – 8:30 PM',
    festivals: ['Brahmotsavam', 'Maha Shivaratri', 'Pradosham', 'Guru Peyarchi'],
    significance: 'World-renowned destiny-altering temple where Lord Brahma sits in meditative grace. Devotees visit to rewrite unfavorable destiny and seek blessings for career, marriage, and prosperity.',
    mapsUrl: 'https://maps.google.com/?q=Brahmapureeswarar+Temple+Thiruppattur+Trichy',
    sourceUrl: 'https://en.wikipedia.org/wiki/Brahmapurisvarar_Temple,_Thiruppattur',
    translations: {
      ta: {
        name: 'பிரம்மபுரீஸ்வரர் திருக்கோயில், திருப்பட்டூர்',
        city: 'திருப்பட்டூர், திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய சோழர் காலம்',
        category: 'சிவன்',
        designation: 'விதியை மாற்றும் திருத்தலம் (பிரம்மன் சன்னதி)',
        history: 'திருப்பட்டூர் பிரம்மபுரீஸ்வரர் திருக்கோயில் மனிதர்களின் தலைவிதியை மாற்றி நல்வாழ்வு அருளும் புண்ணிய தலமாகும். சிவபெருமான் பிரம்மனின் ஐந்தாவது தலையைக் கொய்து படைப்புத் தொழிலை பறித்த பின், பிரம்மன் இங்கு 12 சிவலிங்கங்களை அமைத்து வழிபட்டு சாபவிமோசனம் பெற்றார். இங்கு வரும் பக்தர்களின் தலையெழுத்தை மாற்றி எழுதும் வரத்தை பிரம்மனுக்கு சிவன் அருளினார். பிரம்மனுக்கு 6 அடி உயர தனி சன்னதி இங்குள்ளது.',
        timings: 'காலை: 7:00 – 12:00 | மாலை: 4:30 – 8:30',
        festivals: ['பிரம்மோற்சவம்', 'மகா சிவராத்திரி', 'குருப் பெயர்ச்சி', 'பிரதோஷம்'],
        significance: 'தலைவிதியை மாற்றியமைக்கும் அற்புத பிரம்மன் சன்னதி கொண்ட சிவாலயம்.',
      },
      hi: {
        name: 'ब्रह्मपुरीश्वरर मंदिर, तिरुपत्तूर',
        city: 'तिरुपत्तूर, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: 'प्राचीन चोल काल',
        category: 'शिव',
        designation: 'भाग्य बदलने वाला पावन मंदिर',
        history: 'यहाँ भगवान शिव ने ब्रह्माजी का अहंकार मिटाकर उन्हें पुनः सृष्टि रचने और श्रद्धालुओं का भाग्य संवारने का वरदान दिया था। यहाँ 6 फुट ऊंची भगवान ब्रह्मा की ध्यान मुद्रा में भव्य मूर्ति स्थापित है।',
        timings: 'प्रातः: 7:00 – 12:00 | सायं: 4:30 – 8:30',
        festivals: ['ब्रह्मोत्सवम', 'महाशिवरात्रि', 'गुरु गोचर'],
        significance: 'भाग्य संवारने वाला भगवान ब्रह्मा का दुर्लभ एवं सिद्ध मंदिर।',
      },
    },
  },
  {
    id: 'rockfort-ucchi-pillayar-trichy',
    name: 'Rockfort Ucchi Pillayar & Thayumanaswamy Temple',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.8282,
    lng: 78.6967,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Rock_Fort_Temple_Tiruchirappalli.jpg/800px-Rock_Fort_Temple_Tiruchirappalli.jpg',
    period: '7th Century CE Pallava & Nayak Dynasty',
    category: 'Ganesh',
    designation: 'Iconic 83m Hillfort Temple & Paadal Petra Sthalam',
    history: 'The iconic Rockfort Temple of Tiruchirappalli is built atop an 83-metre (272 ft) high ancient rock thought to be over one billion years old. At the base is the Manikka Vinayagar shrine; midway up through 417 stone-hewn steps is the cave-temple of Lord Thayumanaswamy (Shiva, who took the form of a mother to help a devotee during childbirth); and perched at the summit is the famous Ucchi Pillayar (Ganesh). Vibhishana was pursued by Ganesh here while carrying the Ranganathaswamy idol to Lanka.',
    timings: 'Morning: 6:00 AM – 1:00 PM | Evening: 4:00 PM – 9:00 PM',
    festivals: ['Vinayaka Chaturthi', 'Chithirai Brahmotsavam', 'Maha Shivaratri', 'Karthigai Deepam'],
    significance: 'Iconic rock landmark of Trichy offering 360-degree views of Kaveri and Srirangam. Unique Shiva as loving mother (Thayumanavar) and hilltop Ucchi Pillayar.',
    mapsUrl: 'https://maps.google.com/?q=Rockfort+Ucchi+Pillayar+Temple+Trichy',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ucchi_Pillayar_Temple,_Rockfort',
    translations: {
      ta: {
        name: 'மலைக்கோட்டை உச்சிப் பிள்ளையார் & தாயுமானசுவாமி திருக்கோயில்',
        city: 'திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: '7-ஆம் நூற்றாண்டு பல்லவர் மற்றும் நாயக்கர் காலம்',
        category: 'விநாயகர்',
        designation: 'திருச்சியின் அடையாள மலைக்கோயில் & பாடல் பெற்ற தலம்',
        history: 'திருச்சிராப்பள்ளியின் இதயப்பகுதியில் 83 மீட்டர் உயர பழமையான பாறை மீது கம்பீரமாக நிற்கிறது மலைக்கோட்டை. கீழே மாணிக்க விநாயகர், நடுவே பக்தைக்கு தாயாக வந்து பிரசவம் பார்த்த தாயுமானசுவாமி, உச்சியில் உச்சிப் பிள்ளையார் வீற்றிருக்கின்றனர். விபீஷணன் ஸ்ரீரங்கநாதரை இலங்கைக்கு கொண்டு செல்வதைத் தடுத்து இங்கு நிலைநிறுத்திய பிள்ளையார் இவர்.',
        timings: 'காலை: 6:00 – 1:00 | மாலை: 4:00 – 9:00',
        festivals: ['விநாயகர் சதுர்த்தி (மெகா கொழுக்கட்டை)', 'சித்திரை பிரம்மோற்சவம்', 'மகா சிவராத்திரி'],
        significance: 'திருச்சியின் உலகப் புகழ்பெற்ற மலைக்கோட்டை. தாயாக வந்த சிவபெருமான் மற்றும் உச்சிப் பிள்ளையார்.',
      },
      hi: {
        name: 'रॉकफोर्ट उच्छी पिल्लैयार एवं तायुमानस्वामी मंदिर',
        city: 'तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: '7वीं शताब्दी पल्लव व नायक काल',
        category: 'गणेश',
        designation: 'ऐतिहासिक रॉकफोर्ट शिखर मंदिर',
        history: '83 मीटर ऊंची प्राकृतिक चट्टान पर स्थित त्रिची का प्रतीक मंदिर। 417 सीढ़ियां चढ़कर ऊपर उच्छी पिल्लैयार (गणेश जी) और मध्य में भगवान तायुमानस्वामी (शिव जी) के दर्शन होते हैं।',
        timings: 'प्रातः: 6:00 – 1:00 | सायं: 4:00 – 9:00',
        festivals: ['विनायक चतुर्थी', 'महाशिवरात्रि', 'कार्तिगई दीपम'],
        significance: 'त्रिची का ऐतिहासिक रॉकफोर्ट। कावेरी नदी और श्रीरंगम का विहंगम दृश्य।',
      },
    },
  },
  {
    id: 'vayalur-murugan-temple',
    name: 'Vayalur Murugan Temple (Kumaravayalur)',
    city: 'Kumaravayalur, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.8032,
    lng: 78.6186,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Vayalur_Murugan_temple.jpg/800px-Vayalur_Murugan_temple.jpg',
    period: '9th Century CE Chola Dynasty',
    category: 'Murugan',
    designation: 'Sthalam of Saint Arunagirinathar\\'s Enlightenment',
    history: 'Arulmigu Subramaniya Swamy Temple at Vayalur (Kumaravayalur) is one of the most sacred Murugan shrines in Tamil Nadu. It is here that Lord Murugan appeared before Saint Arunagirinathar, touched his tongue with His Vel (spear), and dictated the first divine verse \\'Muthaitharu Pathithirunagai\\', leading to the composition of the monumental Thiruppugazh hymns. Surrounded by fertile fields and coconut groves, the temple also features Lord Shiva as Agneeswarar.',
    timings: 'Morning: 6:00 AM – 1:00 PM | Evening: 3:30 PM – 9:00 PM',
    festivals: ['Skanda Sashti', 'Thai Poosam', 'Panguni Uthiram', 'Vaikasi Visakam'],
    significance: 'Birthplace of the divine Thiruppugazh hymns where Lord Murugan initiated Saint Arunagirinathar. Renowned for peace of mind, education, and artistic mastery.',
    mapsUrl: 'https://maps.google.com/?q=Vayalur+Murugan+Temple+Trichy',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vayalur_Murugan_Temple',
    translations: {
      ta: {
        name: 'வயலூர் முருகன் திருக்கோயில் (குமாரவயலூர்)',
        city: 'குமாரவயலூர், திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: '9-ஆம் நூற்றாண்டு சோழர் காலம்',
        category: 'முருகன்',
        designation: 'அருணகிரிநாதருக்கு வேல் தந்து பாடியருளிய தலம்',
        history: 'வயலூர் சுப்பிரமணிய சுவாமி திருக்கோயில் அருணகிரிநாதரின் நாவில் முருகன் தனது ஞானவேலால் "முத்தைத்தரு பத்தித்திருநகை" என முதல் அடி எடுத்துக் கொடுத்து திருப்புகழ் பாட வைத்த புகழ்பெற்ற திருத்தலமாகும். பசுமையான வயல்வெளிகள் நடுவே அமைந்த இக்கோயிலில் அக்னீஸ்வரர் சிவாலயமும் உள்ளது.',
        timings: 'காலை: 6:00 – 1:00 | மாலை: 3:30 – 9:00',
        festivals: ['கந்த சஷ்டி', 'தைப்பூசம்', 'பங்குனி உத்திரம்', 'வைகாசி விசாகம்'],
        significance: 'திருப்புகழ் தோன்றிய புண்ணிய பூமி. கல்வியிலும் கலையிலும் சிறக்க உதவும் தலம்.',
      },
      hi: {
        name: 'वयलर मुरुगन मंदिर (कुमारवयलर)',
        city: 'कुमारवयलर, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: '9वीं सदी चोल काल',
        category: 'मुरुगन',
        designation: 'संत अरुणगिरिनाथर की तपोभूमि',
        history: 'भगवान मुरुगन ने संत अरुणगिरिनाथर की जिह्वा पर अपने पवित्र वेल से प्रथम श्लोक लिखकर विश्वविख्यात तिरुप्पुगळ स्तुतियों की रचना करवाई थी।',
        timings: 'प्रातः: 6:00 – 1:00 | सायं: 3:30 – 9:00',
        festivals: ['स्कंद षष्ठी', 'थाई पूसम', 'पंगुनि उत्तिरम'],
        significance: 'तिरुप्पुगळ की उद्गम स्थली। बुद्धि, वाणी एवं विद्या प्रदायक पावन धाम।',
      },
    },
  },
  {
    id: 'samayapuram-mariamman-temple',
    name: 'Samayapuram Mariamman Temple',
    city: 'Samayapuram, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.9255,
    lng: 78.7402,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Samayapuram_Mariamman_temple_gopuram.jpg/800px-Samayapuram_Mariamman_temple_gopuram.jpg',
    period: 'Ancient Chola & Vijayanagara tradition',
    category: 'Shakti',
    designation: 'Foremost Mariamman Shrine of Tamil Nadu',
    history: 'Samayapuram Mariamman Temple is one of the most visited and revered Shakti pilgrimage centres in South India. Dedicated to Goddess Mariamman (an incarnation of Mahakali/Durga), the deity is made of sand and clay, hence no direct abhishekam is performed to the main idol. Devotees visit from across the nation to pray for relief from chickenpox, smallpox, health ailments, and to offer Mavilakku and hair tonsuring. The annual Poochorichal (flower-showering) festival during the Tamil month of Masi/Panguni is legendary.',
    timings: 'Morning: 5:00 AM – 11:00 PM (Continuous darshan on festival days)',
    festivals: ['Poochorichal Festival (March-April)', 'Chithirai Car Festival', 'Panguni Ther', 'Navaratri'],
    significance: 'Foremost Mariamman temple drawing millions of pilgrims. The grand 28-day fast of the Goddess and the flower festival (Poochorichal) are unparalleled in devotion.',
    mapsUrl: 'https://maps.google.com/?q=Samayapuram+Mariamman+Temple+Trichy',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mariamman_Temple,_Samayapuram',
    translations: {
      ta: {
        name: 'சமயபுரம் மாரியம்மன் திருக்கோயில்',
        city: 'சமயபுரம், திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய சக்தி பீடம்',
        category: 'சக்தி',
        designation: 'தென்னிந்தியாவின் முதன்மை மாரியம்மன் தலம்',
        history: 'சமயபுரம் மாரியம்மன் கோயில் தமிழ்நாட்டின் மிக சக்தி வாய்ந்த வழிபாட்டுத் தலங்களில் ஒன்றாகும். அன்னை மாரியம்மன் சுதை வடிவில் உள்ளதால் மூலவருக்கு அபிஷேகம் கிடையாது. அம்மை நோய், தீராத நோய்களைக் குணமாக்கும் தாயாக விளங்குகிறாள். மாசி மாதம் அன்னை 28 நாட்கள் விரதம் இருக்கும் பூச்சொரிதல் விழா லட்சக்கணக்கான பக்தர்களால் கொண்டாடப்படுகிறது.',
        timings: 'காலை: 5:00 – இரவு 11:00',
        festivals: ['பூச்சொரிதல் விழா (பங்குனி)', 'சித்திரைத் தேரோட்டம்', 'மாவிளக்கு பூஜை'],
        significance: 'நோய் தீர்க்கும் சமயபுரத்தாள். உலகப் புகழ்பெற்ற பூச்சொரிதல் திருவிழா.',
      },
      hi: {
        name: 'समयपुरम मरियम्मन मंदिर',
        city: 'समयपुरम, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: 'प्राचीन शक्तिपीठ',
        category: 'शक्ति',
        designation: 'तमिलनाडु का प्रमुख मरियम्मन मंदिर',
        history: 'दक्षिण भारत का सर्वाधिक पूजनीय देवी मंदिर। माँ मरियम्मन भक्तों के सभी रोगों और कष्टों को दूर करती हैं। 28 दिवसीय पुष्प अर्पण उत्सव (पूच्चोरिचल) अद्वितीय है।',
        timings: 'प्रातः: 5:00 – रात्रि 11:00',
        festivals: ['पूच्चोरिचल उत्सव', 'चित्तिरई रथोत्सव', 'नवरात्रि'],
        significance: 'आरोग्यदायिनी माँ मरियम्मन का विश्वविख्यात शक्तिपीठ।',
      },
    },
  },
  {
    id: 'pundarikakshan-perumal-thiruvellarai',
    name: 'Pundarikakshan Perumal Temple, Thiruvellarai',
    city: 'Thiruvellarai, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.9654,
    lng: 78.6652,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Thiruvellarai_temple.jpg/800px-Thiruvellarai_temple.jpg',
    period: 'Pre-dates Srirangam; 8th Century CE Pallava Dynasty',
    category: 'Vishnu',
    designation: '108 Divya Desams — Ancient White Hill Shrine',
    history: 'Pundarikakshan Perumal Temple at Thiruvellarai is an ancient Divya Desam believed to pre-date the Srirangam temple. Built on an 85-foot white granite hillock (Thiru Vellarai = holy white rock), the temple was constructed by King Sibi and expanded by the Pallavas and Hoysalas. It features the historic Swastika-shaped stepwell (Nalumoolai Keni) built in 800 CE during the reign of Dantivarman Pallava, with four distinct bathing ghats designed so bathers cannot see one another.',
    timings: 'Morning: 7:00 AM – 1:00 PM | Evening: 4:00 PM – 8:00 PM',
    festivals: ['Chithirai Brahmotsavam', 'Vaikunta Ekadasi', 'Panguni Car Festival'],
    significance: 'One of the oldest Divya Desams in existence. Houses the unique 8th-century Swastika stepwell (ASI monument) and dual entrance gates representing Dakshinayana and Uttarayana.',
    mapsUrl: 'https://maps.google.com/?q=Pundarikakshan+Perumal+Temple+Thiruvellarai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pundarikakshan_Perumal_Temple',
    translations: {
      ta: {
        name: 'புண்டரீகாட்சன் பெருமாள் திருக்கோயில், திருவெள்ளறை',
        city: 'திருவெள்ளறை, திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: 'ஸ்ரீரங்கத்தை விட தொன்மையானது; 8-ஆம் நூற்றாண்டு பல்லவர் காலம்',
        category: 'விஷ்ணு',
        designation: '108 திவ்ய தேசங்களில் ஒன்று — சுவஸ்திக் கிணறு தலம்',
        history: 'திருவெள்ளறை புண்டரீகாட்சன் பெருமாள் கோயில் ஸ்ரீரங்கம் கோயிலுக்கும் முற்பட்ட பழமையான திவ்ய தேசமாகும். 85 அடி உயர வெள்ளைப் பாறை மீது அமைந்துள்ள இக்கோயிலில் கி.பி. 800-ல் பல்லவ மன்னன் தந்திவர்மன் அமைத்த புகழ்பெற்ற சுவஸ்திக் வடிவ நான்கு மூலை குளம் (சுவஸ்திக் கிணறு) உள்ளது.',
        timings: 'காலை: 7:00 – 1:00 | மாலை: 4:00 – 8:00',
        festivals: ['சித்திரை பிரம்மோற்சவம்', 'வைகுண்ட ஏகாதசி', 'பங்குனி தேரோட்டம்'],
        significance: '108 திவ்ய தேசங்களில் தொன்மையான தலம். 1200 ஆண்டுகள் பழமையான சுவஸ்திக் குளம்.',
      },
      hi: {
        name: 'पुंडरीकाक्षन पेरुमल मंदिर, तिरुवेल्लारई',
        city: 'तिरुवेल्लारई, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: 'श्रीरंगम से भी प्राचीन; 8वीं शताब्दी पल्लव काल',
        category: 'विष्णु',
        designation: '108 दिव्य देशमों में से एक',
        history: 'सफेद ग्रेनाइट पहाड़ी पर स्थित प्राचीन दिव्य देशम। यहाँ 1200 वर्ष पुरानी स्वास्तिक आकार की बावड़ी (स्वास्तिक कुआं) स्थित है।',
        timings: 'प्रातः: 7:00 – 1:00 | सायं: 4:00 – 8:00',
        festivals: ['चित्तिरई ब्रह्मोत्सवम', 'वैकुंठ एकादशी'],
        significance: 'अति प्राचीन दिव्य देशम एवं ऐतिहासिक स्वास्तिक कुंड।',
      },
    },
  },
  {
    id: 'uthamar-kovil-trichy',
    name: 'Uthamar Kovil (Bhikshatandar Kovil)',
    city: 'Uthamar Kovil, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.8876,
    lng: 78.7189,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Uthamar_kovil_Trichy.jpg/800px-Uthamar_kovil_Trichy.jpg',
    period: '8th Century CE Pallava & Chola era',
    category: 'Vishnu',
    designation: '108 Divya Desams — Rare Trimurti & Tridevi Shrine',
    history: 'Uthamar Kovil, also known as Bhikshatandar Kovil, is a rare and unique temple in Hindu tradition housing shrines for all three supreme deities—Brahma, Vishnu (Purushothamar), and Shiva (Bhikshatandar)—along with their divine consorts Saraswati, Mahalakshmi, and Soundaryaparvati. This temple is celebrated in the hymns of Thirumangai Azhwar as a Divya Desam and also as a Paadal Petra Shiva sthalam. Shiva prayed to Vishnu here to be freed from the curse of Brahma\\'s skull clinging to his hand.',
    timings: 'Morning: 6:00 AM – 12:30 PM | Evening: 4:30 PM – 8:30 PM',
    festivals: ['Brahmotsavam', 'Vaikunta Ekadasi', 'Maha Shivaratri', 'Navaratri'],
    significance: 'Extremely rare temple housing all Trinity deities (Brahma, Vishnu, Shiva) and their three divine consorts under one sacred precinct. Both a Divya Desam and Shaivite sacred sthalam.',
    mapsUrl: 'https://maps.google.com/?q=Uthamar+Kovil+Trichy',
    sourceUrl: 'https://en.wikipedia.org/wiki/Uthamar_Kovil',
    translations: {
      ta: {
        name: 'உத்தமர் கோயில் (பிச்சாண்டார் கோயில்)',
        city: 'உத்தமர்கோயில், திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: '8-ஆம் நூற்றாண்டு பல்லவர் & சோழர் காலம்',
        category: 'விஷ்ணு',
        designation: '108 திவ்ய தேசம் — மும்மூர்த்திகளும் முப்பெரும் தேவிகளும் அருளும் தலம்',
        history: 'உத்தமர் கோயில் பிரம்மா, விஷ்ணு (புருஷோத்தமன்), சிவன் (பிட்சாடனர்) ஆகிய மும்மூர்த்திகளும் சரஸ்வதி, மகாலட்சுமி, சௌந்தர்ய பார்வதி ஆகிய முப்பெரும் தேவிகளும் ஒருங்கே எழுந்தருளியுள்ள அரிய புண்ணிய தலமாகும். திருமங்கையாழ்வாரால் மங்களாசாசனம் செய்யப்பட்ட திவ்ய தேசம்.',
        timings: 'காலை: 6:00 – 12:30 | மாலை: 4:30 – 8:30',
        festivals: ['பிரம்மோற்சவம்', 'வைகுண்ட ஏகாதசி', 'மகா சிவராத்திரி'],
        significance: 'பிரம்மா, விஷ்ணு, சிவன் மற்றும் சரஸ்வதி, லட்சுமி, பார்வதி ஆறு பேரும் அருளும் மும்மூர்த்தி தலம்.',
      },
      hi: {
        name: 'उत्तमार मंदिर (भिक्षाटनदार मंदिर)',
        city: 'उत्तमारकोयिल, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: '8वीं शताब्दी पल्लव व चोल काल',
        category: 'विष्णु',
        designation: '108 दिव्य देशम — त्रिमूर्ति एवं त्रिदेवी मंदिर',
        history: 'यह अत्यंत दुर्लभ मंदिर है जहाँ ब्रह्मा, विष्णु और शिव तथा उनकी अर्धांगिनियाँ सरस्वती, लक्ष्मी और पार्वती एक ही मंदिर परिसर में विराजमान हैं।',
        timings: 'प्रातः: 6:00 – 12:30 | सायं: 4:30 – 8:30',
        festivals: ['ब्रह्मोत्सवम', 'वैकुंठ एकादशी', 'महाशिवरात्रि'],
        significance: 'त्रिमूर्ति और त्रिदेवी का एक ही स्थान पर दर्शन कराने वाला पवित्र तीर्थ।',
      },
    },
  },
  {
    id: 'gunaseelam-prasanna-venkatachalapathi',
    name: 'Prasanna Venkatachalapathi Temple, Gunaseelam',
    city: 'Gunaseelam, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 10.9022,
    lng: 78.5714,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Gunaseelam_Temple.jpg/800px-Gunaseelam_Temple.jpg',
    period: 'Ancient Chola & Pandya period',
    category: 'Vishnu',
    designation: 'Sacred Healing Sthalam for Mental Peace',
    history: 'Prasanna Venkatachalapathi Temple at Gunaseelam, situated on the northern banks of the sacred Kaveri River about 24 km from Trichy, is an ancient temple renowned for curing psychiatric, psychological, and nervous afflictions through prayer and the holy theertham. Sage Gunaseela performed intense penance here, and Lord Venkatachalapathi appeared to grant blessings. The temple runs a licensed Rehabilitation Centre combining medical science with divine grace.',
    timings: 'Morning: 6:30 AM – 1:00 PM | Evening: 4:00 PM – 8:30 PM',
    festivals: ['Purattasi Brahmotsavam (11 days)', 'Chithirai Theppotsavam', 'Vaikunta Ekadasi'],
    significance: 'Renowned healing temple for mental health and emotional well-being on the Kaveri river banks. Holy water and sacred prayers bring tranquility and relief to troubled minds.',
    mapsUrl: 'https://maps.google.com/?q=Gunaseelam+Temple+Trichy',
    sourceUrl: 'https://en.wikipedia.org/wiki/Prasanna_Venkatachalapathy_Temple',
    translations: {
      ta: {
        name: 'பிரசன்ன வெங்கடாசலபதி திருக்கோயில், குணசீலம்',
        city: 'குணசீலம், திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய வைணவத் திருத்தலம்',
        category: 'விஷ்ணு',
        designation: 'மன அமைதி மற்றும் மனநோய்களைத் தீர்க்கும் பரிகார தலம்',
        history: 'காவிரிக் கரையில் அமைந்துள்ள குணசீலம் பிரசன்ன வெங்கடாசலபதி திருக்கோயில், மனநலம் குன்றியவர்கள், மன அழுத்தம் மற்றும் நரம்பு நோய்களால் பாதிக்கப்பட்டவர்களுக்கு தீர்வு தரும் சக்தி வாய்ந்த பரிகார தலமாகும். குணசீல முனிவரின் தவத்திற்கு இணங்கி திருப்பதி வேங்கடேசப் பெருமாள் இங்கு எழுந்தருளினார்.',
        timings: 'காலை: 6:30 – 1:00 | மாலை: 4:00 – 8:30',
        festivals: ['புரட்டாசி பிரம்மோற்சவம்', 'சித்திரை தெப்ப உற்சவம்', 'வைகுண்ட ஏகாதசி'],
        significance: 'மனநலம் மற்றும் மன அமைதி அருளும் புகழ்பெற்ற காவிரிக்கரை பெருமாள் கோயில்.',
      },
      hi: {
        name: 'प्रसन्न वेंकटाचलपति मंदिर, गुणशीलम',
        city: 'गुणशीलम, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: 'प्राचीन वैष्णव मंदिर',
        category: 'विष्णु',
        designation: 'मानसिक शांति व स्वास्थ्य प्रदायक तीर्थ',
        history: 'कावेरी नदी के तट पर स्थित यह मंदिर मानसिक शांति एवं मानसिक व्याधियों के निवारण हेतु प्रसिद्ध है। महर्षि गुणशील की तपस्या से प्रसन्न होकर भगवान वेंकटेश्वर यहाँ प्रकट हुए थे।',
        timings: 'प्रातः: 6:30 – 1:00 | सायं: 4:00 – 8:30',
        festivals: ['पुरट्टासी ब्रह्मोत्सवम', 'चित्तिरई फ्लोट फेस्टिवल'],
        significance: 'कावेरी तट पर मानसिक शांति एवं आरोग्य प्रदायक दिव्य स्थल।',
      },
    },
  },
  {
    id: 'thuraiyur-prasanna-venkatachalapathy',
    name: 'Prasanna Venkatachalapathy Temple, Thuraiyur',
    city: 'Thuraiyur, Tiruchirappalli',
    state: 'Tamil Nadu',
    lat: 11.1392,
    lng: 78.5982,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Thuraiyur_Perumal_Hill.jpg/800px-Thuraiyur_Perumal_Hill.jpg',
    period: 'Chola Dynasty & Vijayanagara expansion',
    category: 'Vishnu',
    designation: 'Then Thirupathi (South Tirupati)',
    history: 'Situated atop the Perumalmalai hillock near Thuraiyur, 60 km from Trichy, this temple is revered as Then Thirupathi (Southern Tirupati). Built by King Karikala Chola and later expanded by the Vijayanagara rulers, devotees who cannot undertake the pilgrimage to Tirupati offer their vows, hair tonsuring, and prayers here. The hilltop offers panoramic views of the Pachamalai hills and surrounding greenery.',
    timings: 'Morning: 7:00 AM – 1:00 PM | Evening: 4:00 PM – 8:00 PM',
    festivals: ['Purattasi Saturdays', 'Vaikunta Ekadasi', 'Brahmotsavam'],
    significance: 'Known as "Then Tirupati". Revered hill temple for fulfilling vows and offering prayers in place of Tirumala Tirupati.',
    mapsUrl: 'https://maps.google.com/?q=Prasanna+Venkatachalapathi+Temple+Thuraiyur',
    sourceUrl: 'https://en.wikipedia.org/wiki/Prasanna_Venkatachalapathi_Temple,_Thuraiyur',
    translations: {
      ta: {
        name: 'பிரசன்ன வெங்கடாசலபதி திருக்கோயில், துறையூர் (தென் திருப்பதி)',
        city: 'துறையூர், திருச்சிராப்பள்ளி',
        state: 'தமிழ்நாடு',
        period: 'கரிகால் சோழன் காலம் மற்றும் விஜயநகர விரிவாக்கம்',
        category: 'விஷ்ணு',
        designation: 'தென் திருப்பதி',
        history: 'துறையூர் அருகே பெருமாள்மலையின் மீது வீற்றிருக்கும் அருள்மிகு பிரசன்ன வெங்கடாசலபதி திருக்கோயில் "தென் திருப்பதி" என்று பக்தர்களால் போற்றப்படுகிறது. திருப்பதிக்கு செல்ல முடியாதவர்கள் இங்கு வந்து முடி காணிக்கை செலுத்தி பிரார்த்தனைகளை நிறைவேற்றுகின்றனர்.',
        timings: 'காலை: 7:00 – 1:00 | மாலை: 4:00 – 8:00',
        festivals: ['புரட்டாசி சனிக்கிழமைகள்', 'வைகுண்ட ஏகாதசி', 'பிரம்மோற்சவம்'],
        significance: 'தென் திருப்பதி என போற்றப்படும் வரலாற்று சிறப்புமிக்க மலைக்கோயில்.',
      },
      hi: {
        name: 'प्रसन्न वेंकटाचलपति मंदिर, तुरैयूर (दक्षिण तिरुपति)',
        city: 'तुरैयूर, तिरुचिरापल्ली',
        state: 'तमिलनाडु',
        period: 'चोल व विजयनगर काल',
        category: 'विष्णु',
        designation: 'दक्षिण तिरुपति',
        history: 'पचमलई पहाड़ियों की तलहटी में स्थित यह मंदिर "दक्षिण तिरुपति" के रूप में विख्यात है। जो श्रद्धालु तिरुपति नहीं जा पाते, वे यहाँ आकर अपनी मन्नतें पूरी करते हैं।',
        timings: 'प्रातः: 7:00 – 1:00 | सायं: 4:00 – 8:00',
        festivals: ['पुरट्टासी शनिवार', 'वैकुंठ एकादशी'],
        significance: 'दक्षिण तिरुपति के नाम से प्रसिद्ध पावन पहाड़ी मंदिर।',
      },
    },
  },

  // ─── MADURAI RELIGIOUS DESTINATIONS (MakeMyTrip & Divya Desams) ────────────
  {
    id: 'alagar-kovil-kallazhagar',
    name: 'Arulmigu Kallazhagar Temple, Alagar Kovil',
    city: 'Alagar Kovil, Madurai',
    state: 'Tamil Nadu',
    lat: 10.0768,
    lng: 78.2144,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Alagar_Koil.jpg/800px-Alagar_Koil.jpg',
    period: 'Sangam Era origin; Pandya & Nayak Dynasty',
    category: 'Vishnu',
    designation: '108 Divya Desams — Scenic Alagar Hills Shrine',
    history: 'Arulmigu Kallazhagar Temple at Alagar Kovil is nestled at the foothills of the scenic Alagar hills (Solaimalai), 21 km northeast of Madurai. Celebrated in the Divya Prabandham by Bhoothathalwar, Peyalwar, Nammalwar, and Andal, Lord Vishnu is worshipped as Sundararajan (Kallazhagar). The temple is central to the world-famous Chithirai Festival of Madurai, when Lord Kallazhagar rides on a golden horse into the Vaigai River to bless his sister Goddess Meenakshi\\'s wedding.',
    timings: 'Morning: 6:00 AM – 12:30 PM | Evening: 4:00 PM – 8:00 PM',
    festivals: ['Chithirai Festival (Lakhs of devotees in Vaigai River)', 'Vaikunta Ekadasi', 'Navaratri'],
    significance: 'One of the most famous Divya Desams in Tamil Nadu. The Chithirai procession where Kallazhagar enters the Vaigai River on a golden horse draws over a million pilgrims.',
    mapsUrl: 'https://maps.google.com/?q=Alagar+Kovil+Madurai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kallazhagar_Temple',
    translations: {
      ta: {
        name: 'அருள்மிகு கள்ளழகர் திருக்கோயில், அழகர்கோவில்',
        city: 'அழகர்கோவில், மதுரை',
        state: 'தமிழ்நாடு',
        period: 'சங்க காலம் முதல் பாண்டியர் & நாயக்கர் காலம் வரை',
        category: 'விஷ்ணு',
        designation: '108 திவ்ய தேசங்களில் ஒன்று — அழகர்மலை திருத்தலம்',
        history: 'மதுரைக்கு வடகிழக்கே அழகர் மலையின் அடிவாரத்தில் அமைந்துள்ள கள்ளழகர் திருக்கோயில் 108 திவ்ய தேசங்களில் ஒன்றாகும். ஆண்டாள், நம்மாழ்வார், பூதத்தாழ்வார் பாடிய தலம். சித்திரைத் திருவிழாவில் கள்ளழகர் தங்கக் குதிரையில் வைகை ஆற்றில் இறங்கும் வைபவம் உலகப் புகழ்பெற்ற திருவிழாவாகும்.',
        timings: 'காலை: 6:00 – 12:30 | மாலை: 4:00 – 8:00',
        festivals: ['சித்திரைத் திருவிழா (வைகை ஆற்றில் இறங்குதல்)', 'வைகுண்ட ஏகாதசி', 'நவராத்திரி'],
        significance: 'வைகை ஆற்றில் தங்கக் குதிரை ஏறி இறங்கும் கள்ளழகர் உற்சவம். 108 திவ்ய தேச தலம்.',
      },
      hi: {
        name: 'कल्लाझगर मंदिर, अलगार कोविल',
        city: 'अलगार कोविल, मदुरै',
        state: 'तमिलनाडु',
        period: 'संगम काल, पांड्य व नायक राजवंश',
        category: 'विष्णु',
        designation: '108 दिव्य देशम — चित्तिरई महोत्सव',
        history: 'अलगार पहाड़ियों की तलहटी में स्थित 108 दिव्य देशमों में से एक। चित्तिरई महोत्सव में भगवान कल्लाझगर का सुनहरे घोड़े पर सवार होकर वैगई नदी में प्रवेश करने का दृश्य लाखों श्रद्धालुओं को आकर्षित करता है।',
        timings: 'प्रातः: 6:00 – 12:30 | सायं: 4:00 – 8:00',
        festivals: ['चित्तिरई महोत्सव', 'वैकुंठ एकादशी'],
        significance: 'वैगई नदी में भगवान कल्लाझगर का दिव्य प्रवेश। 108 दिव्य देशम।',
      },
    },
  },
  {
    id: 'koodal-azhagar-temple-madurai',
    name: 'Koodal Azhagar Temple, Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    lat: 9.9161,
    lng: 78.1139,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Koodal_Azhagar_Temple_Gopuram.jpg/800px-Koodal_Azhagar_Temple_Gopuram.jpg',
    period: 'Sangam Era origin; Pandya & Nayak Dynasty',
    category: 'Vishnu',
    designation: '108 Divya Desams — Unique 3-Tier Posture Shrine',
    history: 'Koodal Azhagar Temple in the heart of Madurai is one of the ancient 108 Divya Desams mentioned in Sangam literature. Uniquely, the temple sanctum rises into three tiers, enshrining Lord Vishnu in three postures: Koodal Azhagar in seated posture (Asana) on the ground floor, Sri Suryanarayana standing (Sthanaka) on the second tier, and Sri Ananthasayanam reclining (Sayana) on the third tier. The Ashtanga Vimanam is an architectural masterpiece adorned with delicate stucco figures.',
    timings: 'Morning: 5:30 AM – 12:00 PM | Evening: 4:00 PM – 9:00 PM',
    festivals: ['Vaikunta Ekadasi', 'Brahmotsavam (14 days)', 'Masi Float Festival', 'Navaratri'],
    significance: 'One of the rare temples where Lord Vishnu is enshrined in all three postures (sitting, standing, reclining) on three distinct storeys under an Ashtanga Vimanam.',
    mapsUrl: 'https://maps.google.com/?q=Koodal+Azhagar+Temple+Madurai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Koodal_Azhagar_Temple',
    translations: {
      ta: {
        name: 'கூடல் அழகர் திருக்கோயில், மதுரை',
        city: 'மதுரை',
        state: 'தமிழ்நாடு',
        period: 'சங்க காலம், பாண்டியர் காலம்',
        category: 'விஷ்ணு',
        designation: '108 திவ்ய தேசங்களில் ஒன்று — அஷ்டாங்க விமான தலம்',
        history: 'மதுரை நகரின் மையப்பகுதியில் அமைந்துள்ள கூடல் அழகர் திருக்கோயில் 108 திவ்ய தேசங்களில் ஒன்றாகும். இக்கோயிலின் அஷ்டாங்க விமானத்தில் பெருமாள் மூன்று நிலைகளில் — நின்ற, இருந்த, கிடந்த கோலங்களில் மூன்று தளங்களில் காட்சி தருகிறார்.',
        timings: 'காலை: 5:30 – 12:00 | மாலை: 4:00 – 9:00',
        festivals: ['வைகுண்ட ஏகாதசி', 'பிரம்மோற்சவம்', 'மாசி தெப்பத் திருவிழா'],
        significance: 'நின்ற, இருந்த, கிடந்த மூன்று கோலங்களிலும் பெருமாள் அருளும் அஷ்டாங்க விமான தலம்.',
      },
      hi: {
        name: 'कूडल अलगार मंदिर, मदुरै',
        city: 'मदुरै',
        state: 'तमिलनाडु',
        period: 'संगम काल, पांड्य राजवंश',
        category: 'विष्णु',
        designation: '108 दिव्य देशम — त्रितल अष्टांग विमान',
        history: '108 दिव्य देशमों में से एक। यहाँ अष्टांग विमान के तीन तलों पर भगवान विष्णु बैठे, खड़े और शयन मुद्रा में दर्शन देते हैं।',
        timings: 'प्रातः: 5:30 – 12:00 | सायं: 4:00 – 9:00',
        festivals: ['वैकुंठ एकादशी', 'ब्रह्मोत्सवम', 'मासी फ्लोट फेस्टिवल'],
        significance: 'तीनों मुद्राओं (बैठे, खड़े, शयन) में भगवान विष्णु का दुर्लभ दर्शन।',
      },
    },
  },
  {
    id: 'immayilum-nanmai-tharuvar-madurai',
    name: 'Immayilum Nanmai Tharuvar Temple, Madurai',
    city: 'Madurai',
    state: 'Tamil Nadu',
    lat: 9.9178,
    lng: 78.1128,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Madurai_Meenakshi_Amman_Temple.jpg/800px-Madurai_Meenakshi_Amman_Temple.jpg',
    period: 'Ancient Pandya period tradition',
    category: 'Shiva',
    designation: 'Where Shiva Worshipped Shiva for Rulership',
    history: 'Immayilum Nanmai Tharuvar Temple (He who gives boons in this birth itself) is a distinctive Shiva temple in West Masi Street, Madurai. According to Thiruvilayadal Puranam, after Lord Sundareswarar married Goddess Meenakshi and was crowned king of Madurai, He installed a Shiva lingam here and worshipped it to obtain the wisdom and virtue to rule the Pandyan kingdom righteously. Uniquely, the sanctum features Lord Shiva sitting behind the Lingam in prayer posture.',
    timings: 'Morning: 6:00 AM – 12:00 PM | Evening: 4:30 PM – 9:00 PM',
    festivals: ['Maha Shivaratri', 'Masi Magam', 'Pradosham', 'Navaratri'],
    significance: 'Unique temple where Lord Shiva worshipped Himself. Devotees receive worldly blessings and spiritual fulfillment in this present lifetime itself.',
    mapsUrl: 'https://maps.google.com/?q=Immayilum+Nanmai+Tharuvar+Temple+Madurai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Immayilum_Nanmai_Tharuvar_Temple',
    translations: {
      ta: {
        name: 'இம்மையில் நன்மை தருவார் திருக்கோயில், மதுரை',
        city: 'மதுரை',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய பாண்டியர் காலம்',
        category: 'சிவன்',
        designation: 'சிவபெருமான் சிவனை வழிபட்ட அரிய தலம்',
        history: 'மதுரை மேலமாசி வீதியில் அமைந்துள்ள இம்மையில் நன்மை தருவார் கோயில், சிவனே சிவனை வழிபட்ட விசேஷ தலமாகும். மீனாட்சி அம்மையை மணந்து மதுரையை ஆட்சி செய்யும் மன்னனாக முடிசூடிய சுந்தரேஸ்வரர், நாட்டை நல்ல முறையில் ஆள இங்கு சிவலிங்கம் அமைத்து வழிபட்டார்.',
        timings: 'காலை: 6:00 – 12:00 | மாலை: 4:30 – 9:00',
        festivals: ['மகா சிவராத்திரி', 'மாசி மகம்', 'பிரதோஷம்'],
        significance: 'இப்பிறவியிலேயே நன்மை அருளும் ஈசன். சிவபெருமான் சிவனை பூஜித்த அபூர்வ தலம்.',
      },
      hi: {
        name: 'इम्मयिलुम नन्मै तरुवार मंदिर, मदुरै',
        city: 'मदुरै',
        state: 'तमिलनाडु',
        period: 'प्राचीन पांड्य काल',
        category: 'शिव',
        designation: 'जहाँ शिव ने शिव की पूजा की',
        history: 'मदुरै का राजा बनने के बाद भगवान सुंदरेश्वर ने धर्मपूर्वक राज करने के लिए स्वयं शिव लिंग की स्थापना कर पूजा की थी। इस जन्म में ही समस्त सुख-समृद्धि देने वाले महादेव।',
        timings: 'प्रातः: 6:00 – 12:00 | सायं: 4:30 – 9:00',
        festivals: ['महाशिवरात्रि', 'मासी मगम', 'प्रदोषम'],
        significance: 'भगवान शिव द्वारा स्वयं की गई शिव आराधना का अद्वितीय मंदिर।',
      },
    },
  },
  {
    id: 'vandiyur-mariamman-teppakulam',
    name: 'Vandiyur Mariamman Teppakulam Temple, Madurai',
    city: 'Vandiyur, Madurai',
    state: 'Tamil Nadu',
    lat: 9.9075,
    lng: 78.1517,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Vandiyur_Mariamman_Teppakulam.jpg/800px-Vandiyur_Mariamman_Teppakulam.jpg',
    period: '1645 CE built by King Thirumalai Nayak',
    category: 'Shakti',
    designation: 'Largest Temple Tank in South India',
    history: 'Vandiyur Mariamman Teppakulam is an enormous rectangular temple tank covering approximately 16 acres, built in 1645 CE by the Nayak king Thirumalai Nayakar. Legend says the massive Mukkuruni Pillayar (Ganesh) idol in the Meenakshi Temple was unearthed while digging this sacred tank. In the center of the tank sits a stunning island garden mandapam (Maiya Mandapam) housing Lord Vigneshwara. During the annual Float Festival (Theppotsavam) on Thai Poosam full moon day, illuminated floats carry Goddess Meenakshi and Lord Sundareswarar across the water.',
    timings: 'Morning: 6:00 AM – 12:00 PM | Evening: 4:00 PM – 8:30 PM',
    festivals: ['Theppotsavam (Float Festival in Thai / Jan-Feb)', 'Navaratri', 'Panguni Uthiram'],
    significance: 'South India\\'s largest temple tank (16 acres) with an island mandapam. The spectacular Float Festival brings thousands to witness illuminated rafts gliding across the sacred water.',
    mapsUrl: 'https://maps.google.com/?q=Vandiyur+Mariamman+Teppakulam+Madurai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Vandiyur_Mariamman_Teppakulam',
    translations: {
      ta: {
        name: 'வண்டியூர் மாரியம்மன் தெப்பக்குளம், மதுரை',
        city: 'வண்டியூர், மதுரை',
        state: 'தமிழ்நாடு',
        period: '1645 கி.பி. திருமலை நாயக்கர் காலம்',
        category: 'சக்தி',
        designation: 'தென்னிந்தியாவின் மிகப் பெரிய தெப்பக்குளம்',
        history: 'மதுரை வண்டியூரில் 16 ஏக்கர் பரப்பளவில் அமைந்துள்ள தெப்பக்குளம் 1645-ல் மன்னர் திருமலை நாயக்கரால் கட்டப்பட்டது. இந்த குளத்தைத் தோண்டிய போதுதான் மீனாட்சி அம்மன் கோயிலில் உள்ள முக்குறுணி விநாயகர் சிலை கிடைத்தது. குளத்தின் நடுவே அழகிய மைய மண்டபம் உள்ளது. தைப்பூச பௌர்ணமியில் நடைபெறும் தெப்பத்திருவிழா பிரசித்தி பெற்றது.',
        timings: 'காலை: 6:00 – 12:00 | மாலை: 4:00 – 8:30',
        festivals: ['தைப்பூச தெப்பத்திருவிழா', 'நவராத்திரி', 'பங்குனி உத்திரம்'],
        significance: '16 ஏக்கர் பிரம்மாண்ட தெப்பக்குளம். கண்கவர் தைப்பூச தெப்பத்திருவிழா.',
      },
      hi: {
        name: 'वंडियूर मरियम्मन तेप्पाकुलम, मदुरै',
        city: 'वंडियूर, मदुरै',
        state: 'तमिलनाडु',
        period: '1645 ईस्वी, राजा तिरुमलै नायक',
        category: 'शक्ति',
        designation: 'दक्षिण भारत का सबसे बड़ा मंदिर तालाब',
        history: '16 एकड़ में फैला विशाल आयताकार कुंड जिसके केंद्र में एक सुंदर द्वीप मंडप है। थाई पूसम पर आयोजित होने वाला नौका उत्सव (फ्लोट फेस्टिवल) अत्यंत दर्शनीय होता है।',
        timings: 'प्रातः: 6:00 – 12:00 | सायं: 4:00 – 8:30',
        festivals: ['थाई पूसम तेप्पम उत्सव', 'नवरात्रि'],
        significance: 'दक्षिण भारत का सबसे बड़ा मंदिर तालाब एवं भव्य नौका उत्सव।',
      },
    },
  },
  {
    id: 'pandi-muneeswaran-temple-madurai',
    name: 'Arulmigu Sri Pandi Muneeswaran Temple, Madurai',
    city: 'Melamadai, Madurai',
    state: 'Tamil Nadu',
    lat: 9.9248,
    lng: 78.1633,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Madurai_Meenakshi_Amman_Temple.jpg/800px-Madurai_Meenakshi_Amman_Temple.jpg',
    period: 'Ancient Guardian Deity Tradition',
    category: 'Other',
    designation: 'Supreme Guardian Deity & Nyaya Sthalam',
    history: 'Pandi Muneeswaran Temple at Melamadai on the Ring Road in Madurai is the most revered guardian deity (Kaval Deivam) temple of the southern districts. Devotees believe Lord Pandi Muneeswaran is the divine incarnation of the Pandyan king Nedunjeliyan (from the epic Silappadikaram), sitting in eternal penance to dispense righteous justice. Devotees flock to seek solutions to complex disputes, protection from evil spirits, and blessings for new vehicles and businesses.',
    timings: 'Morning: 6:00 AM – 1:00 PM | Evening: 4:00 PM – 9:00 PM',
    festivals: ['Aadi Festival', 'Maha Shivaratri', 'Panguni Uthiram', 'Thai Pongal'],
    significance: 'Powerful guardian deity of Madurai dispensing justice and protection. Highly popular for vehicle poojas, resolving life disputes, and seeking defense against negative energies.',
    mapsUrl: 'https://maps.google.com/?q=Pandi+Muneeswarar+Temple+Madurai',
    sourceUrl: 'https://www.makemytrip.com/tripideas/religious-madurai',
    translations: {
      ta: {
        name: 'அருள்மிகு பாண்டி முனீஸ்வரர் திருக்கோயில், மதுரை',
        city: 'மேலமடை, மதுரை',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய காவல் தெய்வ மரபு',
        category: 'காவல் தெய்வம்',
        designation: 'தென்மாவட்டங்களின் காவல் தெய்வம் & நீதி ஸ்தலம்',
        history: 'மதுரை மேலமடையில் அமைந்துள்ள பாண்டி முனீஸ்வரர் கோயில் தென்மாவட்டங்களில் மிகவும் புகழ்பெற்ற காவல் தெய்வ ஆலயமாகும். சிலப்பதிகாரப் பாண்டிய மன்னன் நெடுஞ்செழியனே இங்கு முனீஸ்வரராக தவம் இருந்து நீதி வழங்குவதாக ஐதீகம். வாகன பூஜை, வழக்கு விவகாரங்கள் மற்றும் காவல் வேண்டி பக்தர்கள் பெருமளவில் வருகின்றனர்.',
        timings: 'காலை: 6:00 – 1:00 | மாலை: 4:00 – 9:00',
        festivals: ['ஆடிப் பெருவிழா', 'மகா சிவராத்திரி', 'தைப்பொங்கல்'],
        significance: 'நீதி வழங்கும் காவல் தெய்வம். வாகன பூஜைக்கும் பாதுகாப்புக்கும் புகழ்பெற்ற தலம்.',
      },
      hi: {
        name: 'श्री पांडी मुनीश्वरन मंदिर, मदुरै',
        city: 'मेलमडई, मदुरै',
        state: 'तमिलनाडु',
        period: 'प्राचीन संरक्षक देवता परंपरा',
        category: 'अन्य',
        designation: 'मदुरै के संरक्षक देवता',
        history: 'मदुरै का प्रसिद्ध संरक्षक देवता (कावल दैवम) मंदिर। मान्यता है कि पांड्य राजा नेदुंजेळियन यहाँ मुनीश्वर रूप में न्याय और सुरक्षा प्रदान करते हैं।',
        timings: 'प्रातः: 6:00 – 1:00 | सायं: 4:00 – 9:00',
        festivals: ['आदि उत्सव', 'महाशिवरात्रि'],
        significance: 'न्याय और सुरक्षा प्रदाता पावन मंदिर। नए वाहनों की पूजा हेतु प्रसिद्ध।',
      },
    },
  },

  // ─── THANJAVUR DISTRICT (Shaivam.org & Paadal Petra Sthalams) ──────────────
  {
    id: 'thiruvaiyaru-aiyarappar-temple',
    name: 'Thiruvaiyaru Aiyarappar Temple (Panchanadeeswarar)',
    city: 'Thiruvaiyaru, Thanjavur',
    state: 'Tamil Nadu',
    lat: 10.8797,
    lng: 79.1028,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Thiruvaiyaru_temple.jpg/800px-Thiruvaiyaru_temple.jpg',
    period: 'Ancient Chola & Pallava era; Paadal Petra Sthalam',
    category: 'Shiva',
    designation: 'Head of Sapthasthanam — Land of Five Rivers',
    history: 'Thiruvaiyaru Aiyarappar Temple (Panchanadeeswarar) is the foremost among the Sapthasthanam (seven sacred Shiva shrines around Thiruvaiyaru) and a glorious Paadal Petra Sthalam celebrated in the Thevaram hymns. Located where five sacred rivers converge (Arisilaaru, Vennaaru, Vettaaru, Kudamuruttiyaaru, and Kaveri), the presiding deity is Aiyarappar and Goddess Dharmasamvardhini. Thiruvaiyaru is internationally celebrated as the resting place of Saint Thyagaraja, where the annual Thyagaraja Aradhana music festival takes place.',
    timings: 'Morning: 6:00 AM – 12:30 PM | Evening: 4:00 PM – 8:30 PM',
    festivals: ['Sapthasthanam Festival (Chithirai)', 'Thyagaraja Aradhana (Jan)', 'Maha Shivaratri', 'Arudra Darshan'],
    significance: 'Head temple of the Sapthasthanam circuit. Famous for the cosmic Kailasa darshan granted to Saint Appar. International cultural center for Carnatic music and Saint Thyagaraja.',
    mapsUrl: 'https://maps.google.com/?q=Aiyarappar+Temple+Thiruvaiyaru',
    sourceUrl: 'https://shaivam.org/temples-of-lord-shiva/lord-shiva-temples-of-thanjavur-district/',
    translations: {
      ta: {
        name: 'திருவையாறு ஐயாரப்பர் திருக்கோயில் (பஞ்சநதீஸ்வரர்)',
        city: 'திருவையாறு, தஞ்சாவூர்',
        state: 'தமிழ்நாடு',
        period: 'பாடல் பெற்ற தேவாரத் தலம் & சப்தஸ்தான முதன்மை கோயில்',
        category: 'சிவன்',
        designation: 'ஐந்து நதிகள் பாயும் சப்தஸ்தானத் தலைமைத் தலம்',
        history: 'காவிரி, அரசலாறு, வெண்ணாறு, வெட்டாறு, குடமுருட்டி ஆகிய ஐந்து நதிகள் பாயும் திருவையாற்றில் அமைந்துள்ள ஐயாரப்பர் கோயில், சப்தஸ்தான தலங்களின் தலைமைத் தலமாகும். அப்பர் பெருமானுக்கு கயிலாயக் காட்சி அருளிய புண்ணிய பூமி. கர்நாடக சங்கீத மும்மூர்த்திகளில் ஒருவரான தியாகராஜ சுவாமிகளின் ஜீவ சமாதியும் தியாகராஜ ஆராதனையும் இத்தலத்தின் பெருமையாகும்.',
        timings: 'காலை: 6:00 – 12:30 | மாலை: 4:00 – 8:30',
        festivals: ['சித்திரை சப்தஸ்தான பெருவிழா', 'தியாகராஜ ஆராதனை', 'மகா சிவராத்திரி'],
        significance: 'சப்தஸ்தான தலங்களின் தலைக்கோயில். அப்பருக்கு கயிலாயக் காட்சி அளித்த தலம். தியாகராஜர் சமாதி.',
      },
      hi: {
        name: 'तिरुवैय्यारु अय्यारप्पर मंदिर (पंचनदीश्वरर)',
        city: 'तिरुवैय्यारु, तंजावुर',
        state: 'तमिलनाडु',
        period: 'प्राचीन चोल काल, पादल पेत्र स्थलम्',
        category: 'शिव',
        designation: 'सप्तस्थान का प्रमुख मंदिर — पंचनद तीर्थ',
        history: 'पाँच पवित्र नदियों के संगम पर स्थित यह मंदिर सप्तस्थान तीर्थों में सर्वोच्च है। संत अप्पर को यहाँ भगवान शिव ने कैलाश दर्शन कराए थे। संत त्यागराज की समाधि और वार्षिक त्यागराज आराधना का विश्वप्रसिद्ध केंद्र।',
        timings: 'प्रातः: 6:00 – 12:30 | सायं: 4:00 – 8:30',
        festivals: ['सप्तस्थानम उत्सव', 'त्यागराज आराधना', 'महाशिवरात्रि'],
        significance: 'सप्तस्थानम का प्रधान मंदिर। संत त्यागराज की समाधि स्थली।',
      },
    },
  },
  {
    id: 'thirukkarugavur-garbarakshambigai',
    name: 'Thirukkarugavur Garbarakshambigai Temple',
    city: 'Thirukkarugavur, Thanjavur',
    state: 'Tamil Nadu',
    lat: 10.8583,
    lng: 79.2714,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Thirukkarugavur_Temple.jpg/800px-Thirukkarugavur_Temple.jpg',
    period: '7th Century CE Chola era; Paadal Petra Sthalam',
    category: 'Shakti',
    designation: 'Paadal Petra Sthalam — Divine Protector of Motherhood & Womb',
    history: 'Arulmigu Mullaivananathar and Garbarakshambigai Temple at Thirukkarugavur is world-renowned as the divine haven for couples praying for fertility, safe conception, and blessed childbirth (Garba = womb, Raksha = protect, Ambigai = Mother). Goddess Garbarakshambigai stands in magnificent grace; sanctified ghee is distributed as prasadam for conception, and castor oil is given to ensure safe, complication-free delivery. Lord Shiva is worshipped as Mullaivananathar in a swayambhu lingam formed of jasmine vines.',
    timings: 'Morning: 5:30 AM – 1:00 PM | Evening: 4:00 PM – 8:30 PM',
    festivals: ['Vaikasi Visakam (10 days)', 'Navaratri', 'Aadi Pooram', 'Maha Shivaratri'],
    significance: 'World-famous pilgrimage site for safe pregnancy, child boon, and motherhood protection. Millions of families worldwide testify to the grace of Mother Garbarakshambigai.',
    mapsUrl: 'https://maps.google.com/?q=Garbarakshambigai+Temple+Thirukkarugavur',
    sourceUrl: 'https://shaivam.org/temples-of-lord-shiva/lord-shiva-temples-of-thanjavur-district/',
    translations: {
      ta: {
        name: 'திருக்கருகாவூர் கர்ப்பரட்சாம்பிகை திருக்கோயில்',
        city: 'திருக்கருகாவூர், தஞ்சாவூர்',
        state: 'தமிழ்நாடு',
        period: '7-ஆம் நூற்றாண்டு சோழர் காலம், பாடல் பெற்ற தலம்',
        category: 'சக்தி',
        designation: 'கருவறையைக் காக்கும் அன்னை கர்ப்பரட்சாம்பிகை',
        history: 'திருக்கருகாவூர் முல்லைவனநாதர் சமேத கர்ப்பரட்சாம்பிகை திருக்கோயில் பிள்ளைப்பேறு அருளும், கர்ப்பத்தைக் காக்கும் உலகப் புகழ்பெற்ற சக்தி தலமாகும். குழந்தைப் பேறு இல்லாத தம்பதியருக்கு நெய் பிரசாதமும், கர்ப்பிணிப் பெண்களுக்கு சுகப்பிரசவம் ஆக விளக்கெண்ணெய் பிரசாதமும் இங்கு வழங்கப்படுகிறது.',
        timings: 'காலை: 5:30 – 1:00 | மாலை: 4:00 – 8:30',
        festivals: ['வைகாசி விசாகம்', 'நவராத்திரி', 'ஆடிப் பூரம்', 'மகா சிவராத்திரி'],
        significance: 'சந்தான பாக்கியம் மற்றும் சுகப்பிரசவம் அருளும் உலகப் புகழ்பெற்ற தாய்மைத் திருத்தலம்.',
      },
      hi: {
        name: 'तिरुक्करुगावूर गर्भरक्षांबिका मंदिर',
        city: 'तिरुक्करुगावूर, तंजावुर',
        state: 'तमिलनाडु',
        period: '7वीं सदी चोल काल, पादल पेत्र स्थलम्',
        category: 'शक्ति',
        designation: 'मातृत्व व गर्भ रक्षक शक्तिपीठ',
        history: 'संतान प्राप्ति और सुरक्षित प्रसव के लिए विश्वप्रसिद्ध मंदिर। देवी गर्भरक्षांबिका को संतान वरदायिनी माना जाता है। यहाँ संतान प्राप्ति हेतु औषधीय घी और सुरक्षित प्रसव हेतु तेल का प्रसाद दिया जाता है।',
        timings: 'प्रातः: 5:30 – 1:00 | सायं: 4:00 – 8:30',
        festivals: ['वैकासी विशाखम', 'नवरात्रि', 'आदि पूरम'],
        significance: 'संतान सुख एवं सुरक्षित प्रसव हेतु विश्वविख्यात पावन मंदिर।',
      },
    },
  },
  {
    id: 'patteeswaram-dhenupureeswarar-durga',
    name: 'Patteeswaram Dhenupureeswarar & Sri Durga Temple',
    city: 'Patteeswaram, Kumbakonam / Thanjavur',
    state: 'Tamil Nadu',
    lat: 10.9167,
    lng: 79.3333,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Patteeswaram_temple_Durga.jpg/800px-Patteeswaram_temple_Durga.jpg',
    period: 'Chola Dynasty (Chola Queen Sembiyan Mahadevi reconstruction)',
    category: 'Shakti',
    designation: 'Paadal Petra Sthalam — Benevolent Sri Durga Shrine',
    history: 'Sri Dhenupureeswarar Temple at Patteeswaram is a celebrated Paadal Petra Sthalam where Patti, the divine calf daughter of Kamadhenu, worshipped Lord Shiva with milk. The temple is internationally revered for its north-facing Sri Durga shrine, where Goddess Durga is depicted in a remarkably benevolent, peaceful (Shantha Swaroopa) posture with three eyes, eight arms, and smiling grace, worshipped especially during Rahu Kalam for breaking obstacles and doshas. Legend holds that Lord Shiva ordered Nandi to shift sideways so Child Saint Sambandar could receive shade under a pearl canopy.',
    timings: 'Morning: 6:00 AM – 1:00 PM | Evening: 4:00 PM – 9:00 PM',
    festivals: ['Muthu Pandal Festival (Aani)', 'Navaratri (grand celebrations)', 'Maha Shivaratri', 'Margazhi'],
    significance: 'World-famous Shantha Swaroopa Sri Durga shrine. Worshipped especially during Rahu Kalam to remove obstacles, family afflictions, and bring prosperity.',
    mapsUrl: 'https://maps.google.com/?q=Dhenupureeswarar+Temple+Patteeswaram',
    sourceUrl: 'https://shaivam.org/temples-of-lord-shiva/lord-shiva-temples-of-thanjavur-district/',
    translations: {
      ta: {
        name: 'பட்டீஸ்வரம் தேனுபுரீஸ்வரர் & சாந்த துர்க்கை திருக்கோயில்',
        city: 'பட்டீஸ்வரம், தஞ்சாவூர் / கும்பகோணம்',
        state: 'தமிழ்நாடு',
        period: 'சோழர் காலம் (செம்பியன் மாதேவி திருப்பணி)',
        category: 'சக்தி',
        designation: 'பாடல் பெற்ற தலம் — சாந்த சொரூபி துர்க்கை அம்மன்',
        history: 'காமதேனுவின் மகள் பட்டி வழிபட்டதால் பட்டீஸ்வரம் எனப் பெயர் பெற்றது. திருஞானசம்பந்தருக்கு சிவபெருமான் நந்தியை விலகச் சொல்லி முத்துப்பந்தல் அருளிய அற்புத தலம். இத்தலத்தில் உள்ள வடக்கு நோக்கிய துர்க்கை அம்மன் சாந்த சொரூபியாக, சிரித்த முகத்துடன் அருள்பாலிப்பது உலகப் புகழ் பெற்றது. ராகு கால வழிபாட்டிற்குரிய முதன்மை தலம்.',
        timings: 'காலை: 6:00 – 1:00 | மாலை: 4:00 – 9:00',
        festivals: ['முத்துப்பந்தல் பெருவிழா (ஆனி)', 'நவராத்திரி', 'மகா சிவராத்திரி'],
        significance: 'சாந்த சொரூப துர்க்கை அம்மன். ராகு கால வழிபாட்டிற்கு உலகப் புகழ்பெற்ற சக்தி தலம்.',
      },
      hi: {
        name: 'पट्टीश्वरम धेनुपुरीश्वरर एवं दुर्गा मंदिर',
        city: 'पट्टीश्वरम, तंजावुर / कुंभकोणम',
        state: 'तमिलनाडु',
        period: 'चोल राजवंश, पादल पेत्र स्थलम्',
        category: 'शक्ति',
        designation: 'शांत स्वरूपा माँ दुर्गा का विख्यात धाम',
        history: 'कामधेनु की पुत्री पट्टी द्वारा पूजित शिवालय। यहाँ माँ दुर्गा उग्र रूप में नहीं बल्कि शांत, सौम्य और मुस्कुराती मुद्रा (शांत स्वरूपा) में विराजमान हैं। राहुकाल पूजा हेतु यह मंदिर अत्यंत प्रसिद्ध है।',
        timings: 'प्रातः: 6:00 – 1:00 | सायं: 4:00 – 9:00',
        festivals: ['मुथु पंदल उत्सव', 'नवरात्रि', 'महाशिवरात्रि'],
        significance: 'शांत स्वरूपा माँ दुर्गा। राहुकाल में कष्ट निवारण हेतु प्रसिद्ध तीर्थ।',
      },
    },
  },
  {
    id: 'kandiyur-brahmasiras-khandeeswarar',
    name: 'Kandiyur Brahmasiras Khandeeswarar Temple',
    city: 'Kandiyur, Thanjavur',
    state: 'Tamil Nadu',
    lat: 10.8601,
    lng: 79.1102,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Kandiyur_temple.jpg/800px-Kandiyur_temple.jpg',
    period: 'Ancient Chola era; Ashta Veerattana Sthalam',
    category: 'Shiva',
    designation: 'Ashta Veerattanam Sthalam — Decapitation of Brahma\\'s Ego',
    history: 'Brahmasiras Khandeeswarar Temple at Kandiyur is one of the celebrated Ashta Veerattana Sthalams (eight sacred places representing the valorous feats of Lord Shiva). At this spot on the banks of Kudamurutti River, Lord Shiva severed the fifth head of Lord Brahma with his fingernail to extinguish Brahma\\'s pride. Lord Shiva is worshipped as Brahmasiras Khandeeswarar with Goddess Mangalanayaki. Thirunavukkarasar, Sambandar, and Sundarar have all composed Thevaram hymns praising this ancient temple.',
    timings: 'Morning: 6:30 AM – 12:00 PM | Evening: 4:30 PM – 8:30 PM',
    festivals: ['Sapthasthanam Festival', 'Maha Shivaratri', 'Pradosham', 'Panguni Uthiram'],
    significance: 'One of the eight sacred Veerattana temples of Shiva. Decapitation of Brahma\\'s fifth head, teaching humility and eradication of pride.',
    mapsUrl: 'https://maps.google.com/?q=Kandiyur+Shiva+Temple+Thanjavur',
    sourceUrl: 'https://shaivam.org/temples-of-lord-shiva/lord-shiva-temples-of-thanjavur-district/',
    translations: {
      ta: {
        name: 'கண்டியூர் பிரம்மசிரக்கண்டீஸ்வரர் திருக்கோயில்',
        city: 'கண்டியூர், தஞ்சாவூர்',
        state: 'தமிழ்நாடு',
        period: 'அஷ்ட வீரட்ட தலங்களில் ஒன்று, பாடல் பெற்ற தலம்',
        category: 'சிவன்',
        designation: 'அட்ட வீரட்ட தலம் — பிரம்மனின் தலையை கொய்த தலம்',
        history: 'சிவபெருமானின் எட்டு வீரட்ட தலங்களில் ஒன்றான கண்டியூர், கர்வம்கொண்ட பிரம்மனின் ஐந்தாவது தலையை சிவபெருமான் நகத்தினால் கிள்ளி எறிந்த தலமாகும். மூவர் தேவாரம் பாடிய பாடல் பெற்ற தலம்.',
        timings: 'காலை: 6:30 – 12:00 | மாலை: 4:30 – 8:30',
        festivals: ['சப்தஸ்தான விழா', 'மகா சிவராத்திரி', 'பிரதோஷம்'],
        significance: 'அட்ட வீரட்ட தலம். பிரம்மனின் ஆணவம் அழிக்கப்பட்ட புண்ணிய பூமி.',
      },
      hi: {
        name: 'कंडियूर ब्रह्मशिरः खंडीश्वरर मंदिर',
        city: 'कंडियूर, तंजावुर',
        state: 'तमिलनाडु',
        period: 'अष्ट वीरट्टनम स्थलों में से एक',
        category: 'शिव',
        designation: 'अष्ट वीरट्टनम — ब्रह्मा के अहंकार का दमन',
        history: 'भगवान शिव के आठ पराक्रम (अष्ट वीरट्टनम) स्थलों में से एक। यहाँ शिवजी ने ब्रह्माजी के पांचवें शीश का छेदन कर उनके अहंकार को नष्ट किया था।',
        timings: 'प्रातः: 6:30 – 12:00 | सायं: 4:30 – 8:30',
        festivals: ['सप्तस्थानम उत्सव', 'महाशिवरात्रि'],
        significance: 'अष्ट वीरट्टनम में से एक पावन तीर्थ।',
      },
    },
  },
  {
    id: 'thirunallur-kalyanasundareswarar',
    name: 'Thirunallur Kalyanasundareswarar Temple',
    city: 'Thirunallur, Papanasam / Thanjavur',
    state: 'Tamil Nadu',
    lat: 10.9258,
    lng: 79.2882,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Thirunallur_Kalyanasundareswarar_temple.jpg/800px-Thirunallur_Kalyanasundareswarar_temple.jpg',
    period: 'Ancient Chola era; Paadal Petra Sthalam',
    category: 'Shiva',
    designation: 'Paadal Petra Sthalam — Swayambhu Lingam Changing 5 Colors Daily',
    history: 'Kalyanasundareswarar Temple at Thirunallur near Papanasam is a wondrous Paadal Petra Sthalam. The Swayambhu Lingam is celebrated for changing colors five times every single day (copper, light red, gold, emerald green, and an indescribable hue). Sage Agasthya was blessed with the vision of Shiva and Parvati\\'s divine wedding here to balance the Earth. It is also the sacred place where Saint Appar received the sacred Thiruvadi Deeksha (feet of the Lord placed on his head).',
    timings: 'Morning: 6:00 AM – 12:30 PM | Evening: 4:00 PM – 8:30 PM',
    festivals: ['Maha Shivaratri', 'Panguni Uthiram (Divine Wedding)', 'Navaratri', 'Pradosham'],
    significance: 'Miraculous Lingam changing 5 distinct hues daily. Agasthya witnessed the celestial wedding here. Appar received holy feet deeksha.',
    mapsUrl: 'https://maps.google.com/?q=Kalyanasundareswarar+Temple+Thirunallur',
    sourceUrl: 'https://shaivam.org/temples-of-lord-shiva/lord-shiva-temples-of-thanjavur-district/',
    translations: {
      ta: {
        name: 'திருநல்லூர் கல்யாணசுந்தரேஸ்வரர் திருக்கோயில்',
        city: 'திருநல்லூர், பாபநாசம், தஞ்சாவூர்',
        state: 'தமிழ்நாடு',
        period: 'பாடல் பெற்ற தலம், சோழர் காலம்',
        category: 'சிவன்',
        designation: 'ஒரு நாளைக்கு 5 நிறங்கள் மாறும் அற்புத லிங்கம்',
        history: 'திருநல்லூர் கல்யாணசுந்தரேஸ்வரர் கோயிலில் உள்ள சுயம்பு லிங்கம் தினமும் ஐந்து முறை நிறம் மாறும் அற்புதம் வாய்ந்தது (செம்பு, இளஞ்சிவப்பு, பொன், மரகதம் மற்றும் அறியவொண்ணாத வர்ணம்). அகஸ்தியருக்கு கல்யாணக் காட்சி அருளிய தலம். அப்பருக்கு இறைவன் தன் திருவடி தீட்சை அளித்த தலம்.',
        timings: 'காலை: 6:00 – 12:30 | மாலை: 4:00 – 8:30',
        festivals: ['மகா சிவராத்திரி', 'பங்குனி உத்திரம் (திருமண உற்சவம்)', 'பிரதோஷம்'],
        significance: 'தினமும் 5 வண்ணங்கள் மாறும் அதிசய லிங்கம். அப்பருக்கு திருவடி தீட்சை தந்த தலம்.',
      },
      hi: {
        name: 'तिरुणल्लूर कल्याणसुंदरेश्वरर मंदिर',
        city: 'तिरुणल्लूर, पापनाशम, तंजावुर',
        state: 'तमिलनाडु',
        period: 'प्राचीन चोल काल, पादल पेत्र स्थलम्',
        category: 'शिव',
        designation: 'प्रतिदिन 5 रंग बदलने वाला चमत्कारी शिवलिंग',
        history: 'यहाँ का स्वयंभू शिवलिंग दिन में 5 बार अलग-अलग रंग बदलता है। महर्षि अगस्त्य को यहाँ शिव-पार्वती के दिव्य विवाह के दर्शन हुए थे। संत अप्पर को भगवान ने अपने चरण कमलों की दीक्षा दी थी।',
        timings: 'प्रातः: 6:00 – 12:30 | सायं: 4:00 – 8:30',
        festivals: ['महाशिवरात्रि', 'पंगुनि उत्तिरम'],
        significance: '5 रंग बदलने वाला चमत्कारी शिवलिंग। महर्षि अगस्त्य की तपोभूमि।',
      },
    },
  },
`;

const lastBracketIndex = tnContent.lastIndexOf('];');
if (lastBracketIndex !== -1) {
  tnContent = tnContent.slice(0, lastBracketIndex) + newTemplesCode + tnContent.slice(lastBracketIndex);
  fs.writeFileSync(tnFilePath, tnContent, 'utf8');
  console.log('Successfully updated tamilnaduTemples.js with 14 new temples!');
} else {
  console.error('Could not find closing bracket in tamilnaduTemples.js');
}
