const fs = require('fs');

// --- 1. TIRUVALLUR TEMPLES ---
const tiruvallurAdditions = [
  {
    id: 'alarmatheeswarar-alamathi',
    name: 'Sri Alarmatheeswarar Temple',
    city: 'Alamathi',
    state: 'Tamil Nadu',
    image: 'https://www.visittemples.com/uploads/temple/thumb/250/20260627110643_1783900800.jpg',
    period: 'Ancient, Chola era',
    category: 'Shiva',
    designation: '',
    history: 'Sri Alarmatheeswarar Temple is an ancient Shiva temple located in Alamathi village, Tiruvallur district, situated near Redhills on the northern outskirts of Chennai. The presiding deity is Lord Shiva worshipped as Alarmatheeswarar and the Goddess is Alarmelvalli Thayar. The temple is revered by local villagers for peaceful darshan and removal of ancestral doshas.',
    timings: '6:30 AM – 11:30 AM | 4:30 PM – 8:00 PM',
    festivals: ['Maha Shivaratri', 'Arudra Darshan', 'Pradosham', 'Panguni Uthiram'],
    significance: 'Ancient rural Shaiva shrine in Alamathi near Redhills. Believed to bestow peace of mind and agricultural prosperity to the surrounding region.',
    mapsUrl: 'https://maps.google.com/?q=Alarmatheeswarar+Temple+Alamathi+Tiruvallur',
    sourceUrl: 'https://www.visittemples.com/hindu/srialarmatheeswarartemplealamathithiruvallurdistricttamilnadu',
    lat: 13.2385, lng: 80.1245,
    translations: {
      ta: {
        name: 'அருள்மிகு அலர்மதீஸ்வரர் திருக்கோயில், அலமதி',
        city: 'அலமதி',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: '',
        history: 'திருவள்ளூர் மாவட்டம் அலமதி கிராமத்தில் (செங்குன்றம் அருகே) அமைந்துள்ள தொன்மையான சிவாலயம் அலர்மதீஸ்வரர் திருக்கோயில். மூலவர்: அலர்மதீஸ்வரர். அம்பாள்: அலர்மேல்வல்லி. கிராமப்புற அமைதியில் அருள்பாலிக்கும் ஈசனை வழிபட்டால் மன அமைதியும் நல்வாழ்வும் கிட்டும் என்பது ஐதீகம்.',
        timings: 'காலை 6:30 – 11:30 | மாலை 4:30 – 8:00',
        festivals: ['மஹா சிவராத்திரி', 'பிரதோஷம்', 'பங்குனி உத்திரம்'],
        significance: 'அலமதி கிராமத்தில் அமைந்துள்ள புராதன சிவத்தலம். விவசாய வளம் மற்றும் மன நிம்மதி அருளும் ஆலயம்.',
      },
      hi: {
        name: 'श्री अलर्मथीश्वरर मंदिर, अलमथी',
        city: 'अलमथी',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: '',
        history: 'तिरुवल्लुर जिले के अलमथी गांव में स्थित प्राचीन शिव मंदिर। मूलवर अलर्मथीश्वरर और देवी अलर्मेलवल्ली हैं। यह मंदिर ग्रामीण शांति और आध्यात्मिक शांति प्रदान करने हेतु प्रसिद्ध है।',
        timings: 'प्रातः 6:30 – 11:30 | सायं 4:30 – 8:00',
        festivals: ['महाशिवरात्रि', 'प्रदोषम', 'पंगुनि उत्तिरम'],
        significance: 'चेन्नई के निकट अलमथी का शांत और पवित्र शिव धाम।',
      },
    },
  },
  {
    id: 'udaiyavar-kottai-elavur',
    name: 'Sri Udaiyavar Kottai Temple, Chengalsoolaimedu',
    city: 'Elavur',
    state: 'Tamil Nadu',
    image: '',
    period: 'Medieval era',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Udaiyavar Kottai Temple is located at Chengalsoolaimedu near Elavur in Gummidipoondi Taluk, Tiruvallur district. "Udaiyavar" is the revered honorific for Acharya Sri Ramanuja. The temple preserves the sacred memories of Vaishnava acharyas and houses deities worshipped by the local agrarian community for generations.',
    timings: '7:00 AM – 11:00 AM | 5:00 PM – 7:30 PM',
    festivals: ['Vaikunta Ekadasi', 'Ramanuja Jayanthi', 'Panguni Uthiram'],
    significance: 'Historic Vaishnava heritage shrine near the Tamil Nadu-Andhra border in Gummidipoondi taluk, honoring Sri Ramanuja (Udaiyavar).',
    mapsUrl: 'https://maps.google.com/?q=Udaiyavar+Kottai+Temple+Elavur+Tiruvallur',
    sourceUrl: 'https://www.visittemples.com/hindu/sriudaiyavarkottaitemplechengalsoolaimedunearelavurthiruvallurdistricttamilnadu',
    lat: 13.4320, lng: 80.1150,
    translations: {
      ta: {
        name: 'அருள்மிகு உடையவர் கோட்டை திருக்கோயில், எளாவூர்',
        city: 'எளாவூர் (கும்மிடிப்பூண்டி)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'திருவள்ளூர் மாவட்டம் கும்மிடிப்பூண்டி அருகே எளாவூர் செங்கற்சூளைமேடு பகுதியில் அமைந்துள்ள திருக்கோயில். "உடையவர்" என்பது வைணவ ஆச்சார்யர் ஸ்ரீ ராமானுஜரின் சிறப்பு திருநாமமாகும். ஆச்சார்ய பக்தி மற்றும் வைணவ மரபுகளைப் போற்றும் புனிதத் தலம்.',
        timings: 'காலை 7:00 – 11:00 | மாலை 5:00 – 7:30',
        festivals: ['வைகுண்ட ஏகாதசி', 'ராமானுஜர் ஜெயந்தி'],
        significance: 'ஸ்ரீ ராமானுஜரின் (உடையவர்) திருநாமத்தில் விளங்கும் வைணவ வரலாற்றுத் திருத்தலம்.',
      },
      hi: {
        name: 'श्री उदयवर कोट्टई मंदिर, एलावूर',
        city: 'एलावूर',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'तिरुवल्लुर जिले के एलावूर के निकट स्थित वैष्णव मंदिर। "उदयवर" आचार्य श्री रामानुज का आदरसूचक नाम है। यह मंदिर रामानुज परंपरा और वैष्णव संस्कृति को समर्पित है।',
        timings: 'प्रातः 7:00 – 11:00 | सायं 5:00 – 7:30',
        festivals: ['वैकुंठ एकादशी', 'रामानुज जयंती'],
        significance: 'आचार्य श्री रामानुज की स्मृति में निर्मित पवित्र वैष्णव स्थल।',
      },
    },
  },
  {
    id: 'thirupandi-kodumudinathar-elavur',
    name: 'Sri Thirupandi Kodumudinathar Temple, Salai',
    city: 'Elavur',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, Pandya/Chola era',
    category: 'Shiva',
    designation: '',
    history: 'Sri Thirupandi Kodumudinathar Temple is situated at Salai village near Elavur in Tiruvallur district. Dedicated to Lord Shiva as Thirupandi Kodumudinathar, the temple reflects ancient Pandya influence in northern Thondai Nadu. Devotees visit this serene rural temple to pray for liberation from karmic hurdles and family peace.',
    timings: '6:30 AM – 11:00 AM | 5:00 PM – 8:00 PM',
    festivals: ['Maha Shivaratri', 'Pradosham', 'Karthigai Deepam'],
    significance: 'Ancient Shiva temple near the northern border of Tamil Nadu bearing testimony to early Pandya Shaiva devotional footprints.',
    mapsUrl: 'https://maps.google.com/?q=Thirupandi+Kodumudinathar+Temple+Elavur+Tiruvallur',
    sourceUrl: 'https://www.visittemples.com/hindu/srithirupandikodumudinathartemplesalaielavurthiruvallurdistricttamilnadu',
    lat: 13.4410, lng: 80.1210,
    translations: {
      ta: {
        name: 'அருள்மிகு திருப்பண்டி கொடுமுடிநாதர் திருக்கோயில், எளாவூர்',
        city: 'எளாவூர் (சாலை)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: '',
        history: 'திருவள்ளூர் மாவட்டம் எளாவூர் சாலை கிராமத்தில் அமைந்த பழமையான சிவத்தலம். மூலவர்: திருப்பண்டி கொடுமுடிநாதர். பாண்டிய மன்னர்களின் வழிபாட்டு மரபோடு தொடர்புடைய இத்தலத்தில் வழிபட்டால் மனக்கவலைகள் நீங்கி ஈசனின் பேரருள் கிட்டும்.',
        timings: 'காலை 6:30 – 11:00 | மாலை 5:00 – 8:00',
        festivals: ['மஹா சிவராத்திரி', 'பிரதோஷம்', 'கார்த்திகை தீபம்'],
        significance: 'தொண்டை மண்டலத்தில் பாண்டிய மன்னர்களின் சைவத் தடம் தாங்கிய வரலாற்றுச் சிறப்புமிக்க சிவத்தலம்.',
      },
      hi: {
        name: 'श्री तिरुपांडी कोडुमुडीनाथर मंदिर, एलावूर',
        city: 'एलावूर',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: '',
        history: 'तिरुवल्लुर जिले के एलावूर के निकट सालाई गांव में स्थित प्राचीन शिव मंदिर। मूलवर तिरुपांडी कोडुमुडीनाथर हैं। यह मंदिर पांड्य राजाओं के धार्मिक योगदान को दर्शाता है।',
        timings: 'प्रातः 6:30 – 11:00 | सायं 5:00 – 8:00',
        festivals: ['महाशिवरात्रि', 'प्रदोषम', 'कार्तिगई दीपम'],
        significance: 'शांति और भक्ति का पावन ग्रामीण शिव धाम।',
      },
    },
  },
  {
    id: 'kasi-viswanathar-nazarathpettai',
    name: 'Sri Kasi Viswanathar Temple, Nazarathpettai',
    city: 'Nazarathpettai (Poonamallee)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Medieval era',
    category: 'Shiva',
    designation: '',
    history: 'Sri Kasi Viswanathar Temple is situated at Nazarathpettai near Poonamallee, on the western outskirts of Chennai along the Chennai-Bangalore highway. The temple enshrines Lord Shiva as Kasi Viswanathar alongside Goddess Visalakshi. Worshipping here is believed to grant the divine spiritual merit of visiting sacred Varanasi (Kasi).',
    timings: '6:30 AM – 11:30 AM | 4:30 PM – 8:00 PM',
    festivals: ['Maha Shivaratri', 'Pradosham', 'Arudra Darshan', 'Aani Thirumanjanam'],
    significance: 'Revered Dakshina Kasi kshetram near Poonamallee. Cleanses planetary doshas and bestows the spiritual blessings of Varanasi pilgrimage.',
    mapsUrl: 'https://maps.google.com/?q=Kasi+Viswanathar+Temple+Nazarathpettai+Poonamallee',
    sourceUrl: 'https://www.visittemples.com/hindu/srikasiviswanathartemplenazarathpettainearpoonamalleechennaitamilnadu',
    lat: 13.0489, lng: 80.0512,
    translations: {
      ta: {
        name: 'அருள்மிகு காசி விஸ்வநாதர் திருக்கோயில், நசரத்பேட்டை',
        city: 'நசரத்பேட்டை (பூந்தமல்லி)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: '',
        history: 'பூந்தமல்லி அருகே நசரத்பேட்டையில் (சென்னை-பெங்களூரு நெடுஞ்சாலை) அமைந்துள்ள அருள்மிகு காசி விஸ்வநாதர் திருக்கோயில். மூலவர்: காசி விஸ்வநாதர். அம்பாள்: விசாலாட்சி. காசிக்குச் சென்று கங்கையில் நீராடி விஸ்வநாதரை தரிசித்த பலனைத் தரும் தட்சிண காசி தலமாக போற்றப்படுகிறது.',
        timings: 'காலை 6:30 – 11:30 | மாலை 4:30 – 8:00',
        festivals: ['மஹா சிவராத்திரி', 'பிரதோஷம்', 'ஆருத்ரா தரிசனம்'],
        significance: 'பூந்தமல்லி அருகேயுள்ள தட்சிண காசி தலம். விஸ்வநாதர்-விசாலாட்சி அருள் பெற்று சகல தோஷங்களும் நீங்க வழிபடும் தலம்.',
      },
      hi: {
        name: 'श्री काशी विश्वनाथर मंदिर, नज़रथपेट्टई',
        city: 'नज़रथपेट्टई (पूनमल्ली)',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: '',
        history: 'चेन्नई के पूनमल्ली के पास नज़रथपेट्टई में स्थित पावन शिव मंदिर। मूलवर काशी विश्वनाथर और माता विशालाक्षी हैं। यहाँ दर्शन करने से काशी विश्वनाथ के दर्शन का पुण्य फल प्राप्त होता है।',
        timings: 'प्रातः 6:30 – 11:30 | सायं 4:30 – 8:00',
        festivals: ['महाशिवरात्रि', 'प्रदोषम', 'आर्द्रा दर्शन'],
        significance: 'दक्षिण का काशी स्वरूप पवित्र शिव धाम।',
      },
    },
  },
  {
    id: 'haritha-vaarana-perumal-nazarathpettai',
    name: 'Sri Haritha Vaarana Perumal Temple, Nazarathpettai',
    city: 'Nazarathpettai (Poonamallee)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, Pallava era',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Haritha Vaarana Perumal Temple is located in Nazarathpettai near Poonamallee. The temple is dedicated to Lord Vishnu worshipped in a lustrous emerald-green hue as Haritha Vaarana Perumal (Pachai Varna Perumal), alongside Consort Sri Amirthavalli Thayar. Legend connects this sacred spot to Sage Haritha, who performed penance here to behold the divine emerald manifestation of Lord Narayana.',
    timings: '7:00 AM – 11:00 AM | 5:00 PM – 8:00 PM',
    festivals: ['Vaikunta Ekadasi', 'Panguni Uthiram', 'Purattasi Saturdays', 'Krishna Jayanti'],
    significance: 'Ancient Vishnu temple dedicated to Haritha Vaarana Perumal (Emerald Green Narayana), revered for bringing prosperity, good harvest, and relief from Budha (Mercury) dosha.',
    mapsUrl: 'https://maps.google.com/?q=Haritha+Vaarana+Perumal+Temple+Nazarathpettai',
    sourceUrl: 'https://www.visittemples.com/hindu/sriharithavaaranaperumaltemplenazarathpettainearpoonamalleechennaitamilnadu',
    lat: 13.0475, lng: 80.0530,
    translations: {
      ta: {
        name: 'அருள்மிகு ஹரித வாரண பெருமாள் திருக்கோயில், நசரத்பேட்டை',
        city: 'நசரத்பேட்டை (பூந்தமல்லி)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'பூந்தமல்லி அருகே நசரத்பேட்டையில் அமைந்துள்ள பழமையான பெருமாள் கோயில். மூலவர்: ஹரித வாரண பெருமாள் (பச்சை வண்ணப் பெருமாள்). தாயார்: அமிர்தவல்லி தாயார். ஹரித மகரிஷி தவம் புரிந்து பெருமாளின் பச்சை வண்ண திவ்ய வடிவைக் கண்டு தரிசித்த புண்ணிய தலம்.',
        timings: 'காலை 7:00 – 11:00 | மாலை 5:00 – 8:00',
        festivals: ['வைகுண்ட ஏகாதசி', 'புரட்டாசி சனிக்கிழமைகள்', 'பங்குனி உத்திரம்'],
        significance: 'பச்சை வண்ணப் பெருமாளாக அருள்பாலிக்கும் ஹரித வாரண பெருமாள். புதன் கிரக தோஷம் நீங்கவும், தொழில் மேன்மை பெறவும் அருளும் தலம்.',
      },
      hi: {
        name: 'श्री हरित वारण पेरुमाल मंदिर, नज़रथपेट्टई',
        city: 'नज़रथपेट्टई (पूनमल्ली)',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'पूनमल्ली के नज़रथपेट्टई में स्थित प्राचीन वैष्णव मंदिर। भगवान विष्णु यहाँ मनोहारी हरित (श्याम-हरित) वर्ण में "हरित वारण पेरुमाल" के रूप में पूजे जाते हैं। महर्षि हरित ने यहाँ तपस्या कर भगवान के दर्शन पाए थे।',
        timings: 'प्रातः 7:00 – 11:00 | सायं 5:00 – 8:00',
        festivals: ['वैकुंठ एकादशी', 'पुरट्टासी शनिवार', 'पंगुनि उत्तिरम'],
        significance: 'हरित स्वरूप भगवान विष्णु का पावन धाम। बुध ग्रह की शांति एवं समृद्धि प्रदायक।',
      },
    },
  },
  {
    id: 'poorimara-thava-muneeswarar-kattupakkam',
    name: 'Sri Poorimara Thava Muneeswarar Temple, Kattupakkam',
    city: 'Kattupakkam (Poonamallee)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Centuries old tradition',
    category: 'Other',
    designation: '',
    history: 'Sri Poorimara Thava Muneeswarar Temple is a celebrated rural guardian deity shrine located at Kattupakkam near Poonamallee, on the Mount-Poonamallee High Road in western Chennai. Lord Muneeswarar is depicted in profound ascetic penance (Thavam) beneath the sacred sacred neem/poorimaram tree. Devotees revere Him as a powerful protective deity who eradicates evil spirits, illnesses, and legal complications.',
    timings: '6:00 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Aadi Festival', 'Thai Pongal', 'Maha Shivaratri', 'Aavani Moolam'],
    significance: 'Famous guardian and protective shrine (Kaaval Deivam) in western Chennai, sought after for removal of negative energies, drishti (evil eye), and safety.',
    mapsUrl: 'https://maps.google.com/?q=Poorimara+Thava+Muneeswarar+Temple+Kattupakkam',
    sourceUrl: 'https://www.visittemples.com/hindu/sripoorimarathavamuneeswarartemplekattupakkamnearpoonamalleechennaitamilnadu',
    lat: 13.0375, lng: 80.1285,
    translations: {
      ta: {
        name: 'அருள்மிகு பூரிமர தவ முனீஸ்வரர் திருக்கோயில், காட்டுப்பாக்கம்',
        city: 'காட்டுப்பாக்கம் (பூந்தமல்லி)',
        state: 'தமிழ்நாடு',
        category: 'மற்றவை',
        designation: '',
        history: 'சென்னை மவுண்ட்-பூந்தமல்லி சாலையில் காட்டுப்பாக்கத்தில் அமைந்துள்ள புகழ்பெற்ற காவல் தெய்வத் திருத்தலம். மூலவர் தவ முனீஸ்வரர் தவம் இயற்றும் திருக்கோலத்தில் கம்பீரமாக அருள்பாலிக்கிறார். செய்வினை, கண் திருஷ்டி, பயம் நீங்கி குடும்பப் பாதுகாப்பு பெற பக்தர்கள் இங்கு திரளாக வந்து ஆடு, கோழி காணிக்கை செலுத்தி வழிபடுகின்றனர்.',
        timings: 'காலை 6:00 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['ஆடிப் பெருவிழா', 'தை பொங்கல்', 'மஹா சிவராத்திரி'],
        significance: 'மேற்கு சென்னையின் சக்திவாய்ந்த காவல் தெய்வம். கண் திருஷ்டி, பயம், எதிர்மறை ஆற்றல்களை அகற்றி காவல் காக்கும் முனீஸ்வரர்.',
      },
      hi: {
        name: 'श्री पूरीमर तव मुनीश्वरर मंदिर, काट्टुपाक्कम',
        city: 'काट्टुपाक्कम (पूनमल्ली)',
        state: 'तमिलनाडु',
        category: 'अन्य',
        designation: '',
        history: 'चेन्नई के काट्टुपाक्कम में स्थित प्रसिद्ध रक्षक देवता मंदिर। भगवान मुनीश्वरर यहाँ घोर तपस्या मुद्रा में विराजमान हैं। बुरी शक्तियों, नजर दोष और भय से मुक्ति हेतु श्रद्धालु यहाँ नमन करते हैं।',
        timings: 'प्रातः 6:00 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['आदि उत्सव', 'थाई पोंगल', 'महाशिवरात्रि'],
        significance: 'नजर दोष और संकटों से रक्षा करने वाले शक्तिशाली क्षेत्रपाल मुनीश्वरर।',
      },
    },
  },
];

// Append to tiruvallurTemples.js
let tiruvallurCode = fs.readFileSync('src/data/tiruvallurTemples.js', 'utf8');
const lastIndexTiruvallur = tiruvallurCode.lastIndexOf('];');
if (lastIndexTiruvallur !== -1) {
  const newItemsStr = ',\n' + JSON.stringify(tiruvallurAdditions, null, 2).slice(1, -1).trim() + '\n';
  tiruvallurCode = tiruvallurCode.slice(0, lastIndexTiruvallur) + newItemsStr + tiruvallurCode.slice(lastIndexTiruvallur);
  fs.writeFileSync('src/data/tiruvallurTemples.js', tiruvallurCode, 'utf8');
  console.log('Successfully appended 6 temples to tiruvallurTemples.js');
}

// --- 2. CHENNAI TEMPLES ---
const chennaiAdditions = [
  {
    id: 'asalathamman-nungambakkam',
    name: 'Sri Asalathamman Temple, Nungambakkam',
    city: 'Chennai (Nungambakkam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, approx. 300 years old',
    category: 'Shakti',
    designation: '',
    history: 'Sri Asalathamman Temple is a renowned Grama Devata (guardian goddess) shrine situated on Tank Bund Road in Nungambakkam, Chennai. Mother Asalathamman is an aspect of Goddess Mariamman / Parvati, reverently worshipped as the primordial protective deity ("Asal" meaning genuine / original) of Nungambakkam village. Devotees offer neem leaves, lemon garlands, and porridge (Koozh) to seek protection against chickenpox, viral fevers, and family troubles.',
    timings: '6:00 AM – 12:00 PM | 4:30 PM – 9:00 PM',
    festivals: ['Aadi Thiruvizha', 'Thai Velli', 'Navaratri', 'Panguni Uthiram'],
    significance: 'Celebrated guardian mother of Nungambakkam. Bestows health, cures viral fevers, and safeguards the neighborhood.',
    mapsUrl: 'https://maps.google.com/?q=Asalathamman+Temple+Nungambakkam+Chennai',
    sourceUrl: 'https://www.visittemples.com/hindu/sriasalathammantemplenungambakkamchennaitamilnadu',
    lat: 13.0610, lng: 80.2415,
    translations: {
      ta: {
        name: 'அருள்மிகு அசலாத்தம்மன் திருக்கோயில், நுங்கம்பாக்கம்',
        city: 'சென்னை (நுங்கம்பாக்கம்)',
        state: 'தமிழ்நாடு',
        category: 'சக்தி',
        designation: '',
        history: 'சென்னையின் மையப்பகுதியான நுங்கம்பாக்கம் டேங்க் பண்ட் சாலையில் அமைந்துள்ள பழமையான கிராம தேவதை திருக்கோயில். "அசல்" என்றால் உண்மையான, ஆதி அம்மன் என்று பொருள். அம்மை நோய், வெப்ப வியாதிகள் நீங்கவும், குடும்ப மேன்மை பெறவும் பக்தர்கள் வேப்பிலை மற்றும் கூழ் படைத்து வழிபடுகின்றனர்.',
        timings: 'காலை 6:00 – 12:00 | மாலை 4:30 – 9:00',
        festivals: ['ஆடித் திருவிழா', 'தை வெள்ளி', 'நவராத்திரி'],
        significance: 'நுங்கம்பாக்கத்தின் ஆதி காவல் அன்னை. நோய் தீர்க்கும் சக்தி வாய்ந்த மாரியம்மன் வடிவம்.',
      },
      hi: {
        name: 'श्री असलाथम्मन मंदिर, नुंगमबाक्कम',
        city: 'चेन्नई (नुंगमबाक्कम)',
        state: 'तमिलनाडु',
        category: 'शक्ति',
        designation: '',
        history: 'चेन्नई के नुंगमबाक्कम में स्थित प्राचीन ग्राम देवी मंदिर। माता असलाथम्मन देवी पार्वती एवं मरियम्मन का कल्याणकारी स्वरूप हैं। भक्तजन स्वास्थ्य रक्षा एवं संकट निवारण हेतु माता की आराधना करते हैं।',
        timings: 'प्रातः 6:00 – 12:00 | सायं 4:30 – 9:00',
        festivals: ['आदि उत्सव', 'थाई शुक्रवार', 'नवरात्रि'],
        significance: 'नुंगमबाक्कम की रक्षक देवी। आरोग्य और पारिवारिक शांति प्रदायिनी।',
      },
    },
  },
  {
    id: 'sringeri-sharadambal-kodambakkam',
    name: 'Sri Sringeri Sharadambal Temple, Kodambakkam',
    city: 'Chennai (Kodambakkam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Modern, Sringeri Sharada Peetham branch',
    category: 'Shakti',
    designation: '',
    history: 'Sri Sringeri Sharadambal Temple is a serene spiritual sanctuary located in Kodambakkam, Chennai, functioning under the direct auspices of the sacred Dakshinamnaya Sri Sharada Peetham, Sringeri. The sanctum enshrines the radiant golden icon of Mother Sharadambal seated in divine grace, alongside shrines for Adi Sankaracharya and Lord Varasiddhi Vinayaka. The temple is a hub of Vedic chanting, Lalitha Sahasranama parayana, and spiritual study.',
    timings: '6:30 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Sharad Navaratri', 'Sankara Jayanthi', 'Vasantha Panchami', 'Guru Poornima'],
    significance: 'Chennai branch of the ancient Sringeri Sharada Peetham. Radiates supreme serenity, granting wisdom, academic brilliance, and spiritual enlightenment.',
    mapsUrl: 'https://maps.google.com/?q=Sringeri+Sharadambal+Temple+Kodambakkam+Chennai',
    sourceUrl: 'https://www.visittemples.com/hindu/srisringerisharadambaltemplekodambakkamchennaitamilnadu',
    lat: 13.0515, lng: 80.2225,
    translations: {
      ta: {
        name: 'அருள்மிகு சிருங்கேரி சாரதாம்பாள் திருக்கோயில், கோடம்பாக்கம்',
        city: 'சென்னை (கோடம்பாக்கம்)',
        state: 'தமிழ்நாடு',
        category: 'சக்தி',
        designation: '',
        history: 'சென்னையில் கோடம்பாக்கம் பகுதியில் அமைந்துள்ள சிருங்கேரி சாரதா பீடத்தின் கிளைத் திருக்கோயில். கல்விக்கும் ஞானத்திற்கும் அதிபதியான அன்னை சாரதாம்பாள் மற்றும் ஆதி சங்கரர் சன்னதிகள் இங்கு அமைந்துள்ளன. வேதம், லலிதா சகஸ்ரநாம பாராயணம் மற்றும் வித்யா வழிபாடுகளுக்கு மிகவும் உகந்த புண்ணிய தலம்.',
        timings: 'காலை 6:30 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['சாரதா நவராத்திரி', 'சங்கர ஜெயந்தி', 'வசந்த பஞ்சமி'],
        significance: 'சிருங்கேரி சாரதா பீடத்தின் சென்னை கிளை. கல்வி ஞானமும் மன அமைதியும் அருளும் சாரதாம்பாள் சன்னதி.',
      },
      hi: {
        name: 'श्री शृंगेरी शारदाम्बा मंदिर, कोडमबाक्कम',
        city: 'चेन्नई (कोडमबाक्कम)',
        state: 'तमिलनाडु',
        category: 'शक्ति',
        designation: '',
        history: 'चेन्नई के कोडमबाक्कम में स्थित दक्षिणाम्नाय शृंगेरी शारदा पीठ की शाखा। माँ शारदाम्बा की मनमोहक मूर्ति और आदि शंकराचार्य का मंदिर यहाँ स्थापित है। वेद पाठ एवं साधना का प्रमुख केंद्र।',
        timings: 'प्रातः 6:30 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['शारदीय नवरात्रि', 'शंकर जयंती', 'वसंत पंचमी'],
        significance: 'शृंगेरी पीठ की चेन्नई स्थित पावन शाखा। विद्या, ज्ञान और मानसिक शांति प्रदायिनी।',
      },
    },
  },
];

let chennaiCode = fs.readFileSync('src/data/chennaiTemples.js', 'utf8');
const lastIndexChennai = chennaiCode.lastIndexOf('];');
if (lastIndexChennai !== -1) {
  const newItemsStr = ',\n' + JSON.stringify(chennaiAdditions, null, 2).slice(1, -1).trim() + '\n';
  chennaiCode = chennaiCode.slice(0, lastIndexChennai) + newItemsStr + chennaiCode.slice(lastIndexChennai);
  fs.writeFileSync('src/data/chennaiTemples.js', chennaiCode, 'utf8');
  console.log('Successfully appended 2 temples to chennaiTemples.js');
}

// --- 3. INDIA TEMPLES (UJJAIN, MADHYA PRADESH) ---
const indiaAdditions = [
  {
    id: 'harsiddhi-mata-ujjain',
    name: 'Shri Harsiddhi Mata Temple',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Harsiddhi_Temple_Ujjain.jpg/320px-Harsiddhi_Temple_Ujjain.jpg',
    period: 'Ancient, Vikramaditya era (approx. 2000 years old)',
    category: 'Shakti',
    designation: '51 Shakti Peethas',
    history: 'Shri Harsiddhi Mata Temple, situated on the banks of the sacred Shipra River in Jaisinghpura, Ujjain, is one of the revered 51 Shakti Peethas. According to the Shiva Purana, the elbow of Goddess Sati fell here when Lord Vishnu cleaved Her mortal remains with the Sudarshana Chakra. The presiding deity Goddess Harsiddhi was the patron deity (Kuldevi) of the legendary King Vikramaditya, who ruled Ujjain. The temple is globally celebrated for its two monumental 50-foot tall stone deepstambhas (lamp towers) bearing 1,008 oil lamps, which create an enchanting sight of blazing golden light when lit during Navaratri.',
    timings: '5:00 AM – 11:00 PM',
    festivals: ['Chaitra Navaratri', 'Sharad Navaratri', 'Diwali', 'Maha Shivaratri'],
    significance: 'One of the 51 Shakti Peethas (elbow of Sati). Kuldevi of King Vikramaditya. Famous for two massive 50-foot lamp towers illuminated with over a thousand oil lamps.',
    mapsUrl: 'https://maps.google.com/?q=Harsiddhi+Mata+Temple+Ujjain+Madhya+Pradesh',
    sourceUrl: 'https://www.visittemples.com/hindu/shriharsiddhimatatempleujjainmadhyapradesh',
    lat: 23.1812, lng: 75.7665,
    translations: {
      ta: {
        name: 'ஸ்ரீ ஹர்சித்தி மாதா திருக்கோயில், உஜ்ஜைன்',
        city: 'உஜ்ஜைன்',
        state: 'மத்தியப் பிரதேசம்',
        category: 'சக்தி',
        designation: '51 சக்தி பீடங்கள்',
        history: 'மத்தியப் பிரதேச மாநிலம் உஜ்ஜைனில் ஷிப்ரா நதிக்கரையில் அமைந்துள்ள புகழ்பெற்ற 51 சக்தி பீடங்களில் ஒன்று. சதி தேவியின் முழங்கை விழுந்த புண்ணிய தலம். உஜ்ஜைனை ஆண்ட விக்கிரமாதித்த மன்னனின் குலதெய்வம். இக்கோயிலின் முன்புறம் 1008 தீபங்கள் ஏற்றக்கூடிய இரு பிரம்மாண்ட 50 அடி தீப ஸ்தம்பங்கள் அமைந்துள்ளன. நவராத்திரி இரவுகளில் இவை ஏற்றப்படும்போது பேரொளியுடன் காட்சி தரும்.',
        timings: 'காலை 5:00 – இரவு 11:00',
        festivals: ['நவராத்திரி பெருவிழா', 'தீபாவளி', 'மஹா சிவராத்திரி'],
        significance: '51 சக்தி பீடங்களில் ஒன்று (முழங்கை விழுந்த இடம்). விக்கிரமாதித்த மன்னனின் குலதெய்வம். 1008 தீபங்கள் ஒளிரும் பிரம்மாண்ட தீப ஸ்தம்பங்கள்.',
      },
      hi: {
        name: 'श्री हरसिद्धि माता मंदिर, उज्जैन',
        city: 'उज्जैन',
        state: 'मध्य प्रदेश',
        category: 'शक्ति',
        designation: '51 शक्तिपीठ',
        history: 'उज्जैन में क्षिप्रा नदी के तट पर स्थित 51 पवित्र शक्तिपीठों में से एक। पौराणिक मान्यता के अनुसार यहाँ माता सती की कोहनी गिरी थी। यह न्यायप्रिय सम्राट विक्रमादित्य की कुलदेवी हैं। मंदिर प्रांगण में 1008 दीपों वाले दो विशाल 50 फीट ऊंचे दीप स्तंभ स्थित हैं, जो नवरात्रि की संध्या पर प्रज्वलित होकर अनुपम आलौकिक दृश्य प्रस्तुत करते हैं।',
        timings: 'प्रातः 5:00 – रात्रि 11:00',
        festivals: ['चैत्र नवरात्रि', 'शारदीय नवरात्रि', 'दीपावली'],
        significance: '51 शक्तिपीठों में शामिल (सती की कोहनी पीठ)। सम्राट विक्रमादित्य की आराध्य कुलदेवी। 1008 दीपों से सुसज्जित प्राचीन दीप स्तंभ।',
      },
    },
  },
  {
    id: 'kaal-bhairav-ujjain',
    name: 'Shri Kaal Bhairav Temple',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Kal_Bhairav_Temple_Ujjain.jpg/320px-Kal_Bhairav_Temple_Ujjain.jpg',
    period: 'Ancient, Maratha/Scindia reconstructed',
    category: 'Shiva',
    designation: '',
    history: 'Shri Kaal Bhairav Temple is situated on Jail Road in Bhairavgarh, Ujjain, on the banks of the Shipra River. Lord Kaal Bhairav is revered as the supreme Kotwal (Guardian Protector) of the holy city of Avantika (Ujjain). The temple is world-renowned for an astonishing divine mystery: devotees offer liquor (Madira) to Lord Bhairav, and when the priest places the saucer to the lips of the deity, the liquid mysteriously disappears in seconds with no reservoir or drainage beneath! Worshipping Kaal Bhairav removes malefic planetary influences (Rahu-Ketu), black magic, and fear of death.',
    timings: '5:00 AM – 10:00 PM',
    festivals: ['Kaal Bhairav Jayanti', 'Maha Shivaratri', 'Bhairav Utsav'],
    significance: 'Supreme guardian deity (Kotwal) of Ujjain. World-famous for the miraculous phenomenon where the deity swallows liquid offerings. Destroys fears and negative energies.',
    mapsUrl: 'https://maps.google.com/?q=Kal+Bhairav+Temple+Ujjain',
    sourceUrl: 'https://www.visittemples.com/hindu/shrikaalbhairavtempleujjainmadhyapradesh',
    lat: 23.2120, lng: 75.7820,
    translations: {
      ta: {
        name: 'ஸ்ரீ கால பைரவர் திருக்கோயில், உஜ்ஜைன்',
        city: 'உஜ்ஜைன்',
        state: 'மத்தியப் பிரதேசம்',
        category: 'சிவன்',
        designation: '',
        history: 'உஜ்ஜைன் நகரின் காவல் தெய்வமாக போற்றப்படும் கால பைரவர் திருக்கோயில். இத்தலத்தின் உலக அதிசயமான அம்சம்: இறைவனின் திருவாயில் சமர்ப்பிக்கப்படும் திரவ நைவேத்தியத்தை விக்கிரகம் கண் எதிரிலேயே உறிஞ்சி உட்கொள்ளும் அற்புத நிகழ்வு. ராகு-கேது தோஷம், செய்வினை பயம் மற்றும் மரண பயம் நீங்க பக்தர்கள் இங்கு வழிபடுகின்றனர்.',
        timings: 'காலை 5:00 – இரவு 10:00',
        festivals: ['பைரவர் ஜெயந்தி', 'மஹா சிவராத்திரி'],
        significance: 'உஜ்ஜைன் நகரின் தலைமை காவல் தெய்வம் (கொத்வால்). விக்கிரகம் நைவேத்தியத்தை ஏற்கும் அரிய அற்புதத் தலம்.',
      },
      hi: {
        name: 'श्री काल भैरव मंदिर, उज्जैन',
        city: 'उज्जैन',
        state: 'मध्य प्रदेश',
        category: 'शिव',
        designation: '',
        history: 'उज्जैन के भैरवगढ़ में स्थित भगवान काल भैरव का मंदिर जो अवंतिका नगरी के कोतवाल (रक्षक) कहलाते हैं। यह मंदिर विश्वभर में अपने अनूठे चमत्कार के लिए प्रसिद्ध है, जहाँ भगवान के मुख पर मदिरा का पात्र लगाने पर वह पलक झपकते ही अंतर्धान हो जाती है। काल भैरव की आराधना से भय, अकाल मृत्यु, तंत्र बाधा और राहु-केतु के दोष शांत होते हैं।',
        timings: 'प्रातः 5:00 – रात्रि 10:00',
        festivals: ['काल भैरव जयंती', 'महाशिवरात्रि'],
        significance: 'उज्जैन के मुख्य संरक्षक कोतवाल। असाधारण चमत्कारिक तीर्थ जो अकाल मृत्यु और भय का नाश करता है।',
      },
    },
  },
  {
    id: 'mangalnath-ujjain',
    name: 'Shri Mangalnath Temple',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mangalnath_Temple_Ujjain.jpg/320px-Mangalnath_Temple_Ujjain.jpg',
    period: 'Ancient, Matsya Purana era',
    category: 'Shiva',
    designation: 'Navagraha Mars Birthplace',
    history: 'Shri Mangalnath Temple, built atop a hillock overlooking the Shipra River in Ujjain, is celebrated across India as the sacred birthplace of Planet Mars (Mangal Graha / Angarakan). According to the Matsya Purana, when Lord Shiva battled the demon Andhakasura, a drop of divine perspiration fell from His forehead onto the earth at this exact spot, giving birth to Mars (Bhauma / Mangal). Ancient Indian astronomers considered this point on earth as the prime meridian intersecting the Tropic of Cancer. It is the foremost shrine in India for performing Bhat Pooja (cooked rice offering) to alleviate severe Mangal Dosha (Manglik Dosha) and marital obstacles.',
    timings: '6:00 AM – 10:00 PM',
    festivals: ['Angaraki Chaturthi', 'Maha Shivaratri', 'Navaratri', 'Tuesdays special poojas'],
    significance: 'Astrological birthplace of Planet Mars (Mangal Graha). Premier all-India pilgrimage center for Manglik Dosha Bhat Pooja and overcoming obstacles in marriage and blood-related ailments.',
    mapsUrl: 'https://maps.google.com/?q=Mangalnath+Temple+Ujjain',
    sourceUrl: 'https://www.visittemples.com/hindu/shrimangalnathtempleujjainmadhyapradesh',
    lat: 23.2185, lng: 75.7875,
    translations: {
      ta: {
        name: 'ஸ்ரீ மங்களநாதர் திருக்கோயில், உஜ்ஜைன்',
        city: 'உஜ்ஜைன்',
        state: 'மத்தியப் பிரதேசம்',
        category: 'சிவன்',
        designation: 'செவ்வாய் பகவான் அவதார தலம்',
        history: 'மத்தியப் பிரதேச மாநிலம் உஜ்ஜைனில் அமைந்துள்ள மங்களநாதர் திருக்கோயில், செவ்வாய் பகவான் அவதரித்த உலகப் புகழ்பெற்ற திருத்தலமாகும். சிவபெருமானின் நெற்றி வியர்வையிலிருந்து செவ்வாய் பகவான் பூமாதேவியின் புதல்வனாக அவதரித்த இடம் இதுவென மத்ஸ்ய புராணம் கூறுகிறது. செவ்வாய் தோஷம், மாங்கல்ய தோஷம் உள்ளவர்கள் இங்கு வந்து அன்ன அபிஷேகம் (பாத் பூஜை) செய்து வழிபட்டால் திருமணத் தடைகள் நீங்கி நல்வாழ்வு பெறுவர்.',
        timings: 'காலை 6:00 – இரவு 10:00',
        festivals: ['அங்காரக சதுர்த்தி', 'மஹா சிவராத்திரி', 'செவ்வாய்க்கிழமைகள் சிறப்பு வழிபாடு'],
        significance: 'செவ்வாய் பகவானின் பிறப்பிட தலம். செவ்வாய் தோஷம், மாங்கல்ய தடை நீங்க பாத் பூஜை செய்யும் முதன்மை தலம்.',
      },
      hi: {
        name: 'श्री मंगलनाथ मंदिर, उज्जैन',
        city: 'उज्जैन',
        state: 'मध्य प्रदेश',
        category: 'शिव',
        designation: 'मंगल ग्रह जन्मस्थान',
        history: 'उज्जैन में क्षिप्रा तट पर स्थित मंगलनाथ मंदिर को मत्स्य पुराण के अनुसार मंगल ग्रह की जन्मभूमि माना जाता है। अंधकासुर वध के समय भगवान शिव के मस्तक से गिरे स्वेद बिंदु से पृथ्वी पर मंगल देव का प्राकट्य हुआ। प्राचीन भारतीय खगोल विज्ञान के अनुसार यह स्थान कर्क रेखा का केंद्र बिंदु है। यहाँ की जाने वाली "भात पूजा" (चावल से अभिषेक) मांगलिक दोष, विवाह बाधा एवं रक्त विकारों के निवारण हेतु भारत में सर्वश्रेष्ठ मानी जाती है।',
        timings: 'प्रातः 6:00 – रात्रि 10:00',
        festivals: ['अंगारकी चतुर्थी', 'महाशिवरात्रि', 'मंगलवार विशेष पूजा'],
        significance: 'मंगल ग्रह की पौराणिक जन्मस्थली। मांगलिक दोष निवारण एवं भात पूजा का सर्वोच्च राष्ट्रीय तीर्थ।',
      },
    },
  },
  {
    id: 'sandipani-ashram-ujjain',
    name: 'Shri Sandipani Ashram Temple',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    image: '',
    period: 'Ancient, Dvapara Yuga heritage',
    category: 'Vishnu',
    designation: '',
    history: 'Shri Sandipani Ashram Temple, located on Mangalnath Marg in Ujjain, is the venerated hermitage where Lord Sri Krishna, His brother Balarama, and friend Sudama resided as disciples to study the 64 arts (Chausath Kalas), 14 sciences, and the four Vedas under Maharishi Sandipani. The ashram houses the ancient "Ankapata" (where numbers were inscribed by Krishna), the holy Gomti Kund water tank, and a rare standing Nandi statue facing Lord Shiva. It is revered as the ultimate sanctuary for students, scholars, and spiritual seekers seeking mastery in education.',
    timings: '7:00 AM – 7:00 PM',
    festivals: ['Krishna Janmashtami', 'Guru Poornima', 'Gopashtami'],
    significance: 'The ancient Gurukula of Lord Sri Krishna and Balarama. Enshrines the sacred Ankapata and Gomti Kund. Revered for education, wisdom, and student success.',
    mapsUrl: 'https://maps.google.com/?q=Sandipani+Ashram+Ujjain',
    sourceUrl: 'https://www.visittemples.com/hindu/shrisandipaniashramtempleujjainmadhyapradesh',
    lat: 23.2085, lng: 75.7760,
    translations: {
      ta: {
        name: 'ஸ்ரீ சாந்தீபனி ஆசிரமம் திருக்கோயில், உஜ்ஜைன்',
        city: 'உஜ்ஜைன்',
        state: 'மத்தியப் பிரதேசம்',
        category: 'விஷ்ணு',
        designation: '',
        history: 'துவாபர யுகத்தில் ஸ்ரீ கிருஷ்ணர், பலராமர் மற்றும் சுதாமா ஆகியோர் சாந்தீபனி முனிவரிடம் சீடர்களாக தங்கி 64 கலைகள், வேதங்கள் மற்றும் சாஸ்திரங்களைக் கற்றுத் தேர்ந்த புண்ணிய குருகுலம். இங்குள்ள கோமதி குண்டம் மற்றும் கிருஷ்ணர் எண்களை எழுதிய அங்கபாத தளம் மிகவும் புனிதமானது. மாணவர்கள் கல்வி ஞானம் பெற வழிபடும் உன்னத தலம்.',
        timings: 'காலை 7:00 – மாலை 7:00',
        festivals: ['கிருஷ்ண ஜெயந்தி', 'குரு பூர்ணிமா'],
        significance: 'ஸ்ரீ கிருஷ்ண பரமாத்மா கல்வி பயின்ற குருகுல ஆசிரமம். கல்வி மற்றும் ஞானப் பேறு அருளும் ஆலயம்.',
      },
      hi: {
        name: 'श्री सांदीपनि आश्रम मंदिर, उज्जैन',
        city: 'उज्जैन',
        state: 'मध्य प्रदेश',
        category: 'विष्णु',
        designation: '',
        history: 'द्वापर युग का वह पावन गुरुकुल जहाँ भगवान श्री कृष्ण, बलराम और सुदामा ने महर्षि सांदीपनि के चरणों में बैठकर 64 कलाओं, 14 विद्याओं और चारों वेदों का अध्ययन किया था। यहाँ पवित्र गोमती कुंड और वह शिला स्थित है जहाँ श्री कृष्ण ने अंक लिखना सीखा था (अंकपात)। विद्यार्थियों के लिए विद्या और ज्ञान प्राप्ति का यह अद्वितीय तीर्थ है।',
        timings: 'प्रातः 7:00 – सायं 7:00',
        festivals: ['श्री कृष्ण जन्माष्टमी', 'गुरु पूर्णिमा'],
        significance: 'भगवान श्री कृष्ण और बलराम की शिक्षा स्थली। विद्या, बुद्धि और ज्ञान वृद्धि का पावन आश्रम।',
      },
    },
  },
];

let indiaCode = fs.readFileSync('src/data/indiaTemples.js', 'utf8');
const lastIndexIndia = indiaCode.lastIndexOf('];');
if (lastIndexIndia !== -1) {
  const newItemsStr = ',\n' + JSON.stringify(indiaAdditions, null, 2).slice(1, -1).trim() + '\n';
  indiaCode = indiaCode.slice(0, lastIndexIndia) + newItemsStr + indiaCode.slice(lastIndexIndia);
  fs.writeFileSync('src/data/indiaTemples.js', indiaCode, 'utf8');
  console.log('Successfully appended 4 Ujjain temples to indiaTemples.js');
}

// --- 4. KUMBAKONAM / CAUVERY DELTA TEMPLES ---
const kumbakonamAdditions = [
  {
    id: 'abathsagayeswarar-alangudi',
    name: 'Sri Abathsagayeswarar Temple (Guru Sthalam), Alangudi',
    city: 'Alangudi (Kumbakonam/Valangaiman)',
    state: 'Tamil Nadu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Alangudi_Guru_Temple.jpg/320px-Alangudi_Guru_Temple.jpg',
    period: 'Ancient, Chola era',
    category: 'Shiva',
    designation: 'Navagraha & Paadal Petra Sthalam',
    history: 'Sri Abathsagayeswarar Temple in Alangudi near Kumbakonam is the pre-eminent Navagraha temple for Lord Guru (Jupiter / Brihaspati). Presiding deity is Lord Shiva as Abathsagayeswarar (the Savior in Times of Danger) and Goddess Elavarkuzhali. The South-facing Dakshinamoorthy shrine here is worshipped as the supreme manifestation of Guru Bhagavan. When the cosmic churning produced the deadly poison Alakala, Lord Shiva consumed it here to save the devas, hence named Alangudi and Abathsagayeswarar.',
    timings: '6:00 AM – 1:00 PM | 4:00 PM – 9:00 PM',
    festivals: ['Guru Peyarchi (Jupiter Transit)', 'Maha Shivaratri', 'Panguni Uthiram', 'Chithirai Pournami'],
    significance: 'Paramount Navagraha Guru Sthalam (Jupiter). Sung by Saint Sambandar in Devaram hymns. Lakhs of devotees gather for Guru Peyarchi to ward off unfavorable planetary transits.',
    mapsUrl: 'https://maps.google.com/?q=Alangudi+Guru+Temple+Kumbakonam',
    sourceUrl: 'https://www.visittemples.com/hindu/sriabathsagayeswarartempleorgurusthalamalangudithiruvarurdistricttamilnadu',
    lat: 10.8356, lng: 79.4089,
    translations: {
      ta: {
        name: 'அருள்மிகு ஆபத்சகாயேஸ்வரர் திருக்கோயில் (குரு ஸ்தலம்), ஆலங்குடி',
        city: 'ஆலங்குடி (கும்பகோணம்)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: 'நவக்கிரகம் & பாடல் பெற்ற தலம்',
        history: 'கும்பகோணம் அருகே உள்ள ஆலங்குடி, நவகிரகங்களில் முதன்மையான குரு பகவானின் சிறப்பு வழிபாட்டுத் தலமாகும். ஆலகால விஷத்தை அருந்தி உலகைக் காத்ததால் ஈசனுக்கு "ஆபத்சகாயேஸ்வரர்" என்று பெயர். மூலவர் சன்னதி பிரகாரத்தில் தெற்கு நோக்கிய தட்சிணாமூர்த்தி "குரு பகவானாக" வழிபடப்படுகிறார். சம்பந்தரால் தேவாரம் பாடப்பட்ட தலம். குரு பெயர்ச்சியின் போது குரு தோஷம் நீங்க பக்தர்கள் இங்கு திரளாக வழிபாடு செய்கின்றனர்.',
        timings: 'காலை 6:00 – மதியம் 1:00 | மாலை 4:00 – இரவு 9:00',
        festivals: ['குரு பெயர்ச்சி விழா', 'மஹா சிவராத்திரி', 'பங்குனி உத்திரம்'],
        significance: 'நவகிரகங்களில் குரு ஸ்தலம். குரு பார்வை பெறவும், உத்தியோகம் மற்றும் புத்திர பாக்கியம் கைகூடவும் தொழும் முதன்மைத் தலம்.',
      },
      hi: {
        name: 'श्री आपत्सहायेश्वरर मंदिर (गुरु स्थल), आलंगुडी',
        city: 'आलंगुडी (कुम्भकोणम)',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: 'नवग्रह एवं पादल पेत्र स्थलम',
        history: 'कुम्भकोणम के निकट आलंगुडी नवग्रहों में देवगुरु बृहस्पति का परम प्रसिद्ध तीर्थ है। हलाहल विष का पान कर देवताओं की रक्षा करने के कारण शिव जी "आपत्सहायेश्वरर" (संकटमोचक) कहलाए। यहाँ दक्षिणामूर्ति भगवान ही गुरु रूप में पूजे जाते हैं। गुरु गोचर के समय यहाँ लाखों श्रद्धालु दर्शन करते हैं।',
        timings: 'प्रातः 6:00 – दोपहर 1:00 | सायं 4:00 – रात्रि 9:00',
        festivals: ['गुरु गोचर (गुरु पेयार्ची)', 'महाशिवरात्रि'],
        significance: 'नवग्रहों में गुरु (बृहस्पति) का प्रधान धाम। विद्या, ज्ञान और उन्नति प्रदायक।',
      },
    },
  },
  {
    id: 'somanatha-swamy-keezha-pazhayarai',
    name: 'Sri Somanatha Swamy Temple, Keezha Pazhayarai',
    city: 'Keezha Pazhayarai (Kumbakonam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, Medieval Chola Capital',
    category: 'Shiva',
    designation: 'Devaram Paadal Petra Sthalams',
    history: 'Sri Somanatha Swamy Temple is situated at Keezha Pazhayarai near Kumbakonam, which served as the secondary royal capital and military camp of the Imperial Cholas. Lord Shiva is worshipped as Somanatheswarar and the Goddess as Somanayaki. Sung in the Devaram padhigams of Thirunavukkarasar (Appar), this historic temple is steeped in Chola royal legends and was patronized by Rajaraja Chola and his sister Kundavai Pirattiyar.',
    timings: '7:00 AM – 12:00 PM | 4:30 PM – 8:00 PM',
    festivals: ['Maha Shivaratri', 'Panguni Uthiram', 'Pradosham'],
    significance: 'Ancient Chola royal capital temple sung by Saint Appar. Radiates the grandeur of Chola heritage and spiritual solace.',
    mapsUrl: 'https://maps.google.com/?q=Somanatha+Swamy+Temple+Keezha+Pazhayarai+Kumbakonam',
    sourceUrl: 'https://www.visittemples.com/hindu/srisomanathaswamytemplekeezhapazhayarainearkumbakonamtamilnadu',
    lat: 10.9234, lng: 79.3512,
    translations: {
      ta: {
        name: 'அருள்மிகு சோமநாத சுவாமி திருக்கோயில், கீழப் பழையாறை',
        city: 'கீழப் பழையாறை (கும்பகோணம்)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: 'தேவாரம் பாடல் பெற்ற தலம்',
        history: 'சோழர்களின் இரண்டாவது தலைநகரமாகவும் அரச குடும்பத்தின் உறைவிடமாகவும் விளங்கிய பழையாறையில் அமைந்த வரலாற்றுப் புகழ்மிக்க தலம். அப்பர் பெருமானால் தேவாரம் பாடப்பெற்ற தலம். மூலவர்: சோமநாதேஸ்வரர். அம்பாள்: சோமநாயகி. ராஜராஜ சோழன் மற்றும் குந்தவை பிராட்டியார் திருப்பணி செய்த புராதன ஆலயம்.',
        timings: 'காலை 7:00 – 12:00 | மாலை 4:30 – 8:00',
        festivals: ['மஹா சிவராத்திரி', 'பிரதோஷம்', 'பங்குனி உத்திரம்'],
        significance: 'சோழர் தலைநகரப் பெருமை கொண்ட தேவாரம் பாடல் பெற்ற சிவத்தலம்.',
      },
      hi: {
        name: 'श्री सोमनाथ स्वामी मंदिर, कीळा पळैयारै',
        city: 'कीळा पळैयारै (कुम्भकोणम)',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: 'देवारम पादल पेत्र स्थलम',
        history: 'चोल साम्राज्य की द्वितीय राजधानी पळैयारै में स्थित ऐतिहासिक शिव मंदिर। संत अप्पर द्वारा देवारम में स्तुत। सम्राट राजराज चोल और राजकुमारी कुंदवई द्वारा सेवित पावन तीर्थ।',
        timings: 'प्रातः 7:00 – 12:00 | सायं 4:30 – 8:00',
        festivals: ['महाशिवरात्रि', 'प्रदोषम'],
        significance: 'चोल स्थापत्य एवं इतिहास का अनुपम शिव धाम।',
      },
    },
  },
  {
    id: 'kothandaramar-mudikondan',
    name: 'Sri Kothandaramar Temple, Mudikondan',
    city: 'Mudikondan (Tiruvarur/Nannilam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, Chola era',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Kothandaramar Temple in Mudikondan is an ancient and celebrated Rama shrine located between Kumbakonam and Tiruvarur. According to the Ramayana sthala purana, Sage Bharadwaja invited Sri Rama for a royal feast during His return to Ayodhya. Rama accepted the feast in His coronation crown (Mudi) posture, hence the village earned the holy name "Mudi-Kondan" (He who wore the Crown). Worshipping here grants victory in endeavours, political leadership, and elevation in career.',
    timings: '7:00 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Sri Rama Navami', 'Vaikunta Ekadasi', 'Hanumath Jayanthi'],
    significance: 'Revered temple where Sri Rama gave darshan wearing His coronation crown (Mudi) to Sage Bharadwaja. Bestows leadership, career growth, and victory.',
    mapsUrl: 'https://maps.google.com/?q=Kothandaramar+Temple+Mudikondan',
    sourceUrl: 'https://www.visittemples.com/hindu/srikothandaramartemplemudikondanthiruvarurdistricttamilnadu',
    lat: 10.9120, lng: 79.5820,
    translations: {
      ta: {
        name: 'அருள்மிகு கோதண்டராமர் திருக்கோயில், முடிகொண்டான்',
        city: 'முடிகொண்டான் (திருவாரூர்)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'கும்பகோணம்-மயிலாடுதுறை வழித்தடத்தில் அமைந்துள்ள வரலாற்றுச் சிறப்புமிக்க ராமர் கோயில். பரத்வாஜ முனிவரின் விருந்தை ஏற்பதற்காக ஸ்ரீ ராமர் பட்டாபிஷேக முடியுடன் (கிரீடத்துடன்) காட்சியளித்ததால் இவ்வூர் "முடிகொண்டான்" என அழைக்கப்படுகிறது. உத்தியோக உயர்வு மற்றும் தலைமைப் பண்பு பெற அருளும் தலம்.',
        timings: 'காலை 7:00 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['ஸ்ரீ ராம நவமி', 'வைகுண்ட ஏகாதசி', 'ஹனுமத் ஜெயந்தி'],
        significance: 'ஸ்ரீ ராமர் மகுடத்துடன் முனிவருக்குக் காட்சி தந்த திருத்தலம். அரசு வேலை மற்றும் தலைமைப் பொறுப்புகள் பெறச் சிறந்த தலம்.',
      },
      hi: {
        name: 'श्री कोदंडरामार मंदिर, मुडिकोंडन',
        city: 'मुडिकोंडन',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'कुम्भकोणम के पास स्थित पावन राम मंदिर। महर्षि भारद्वाज के आग्रह पर भगवान श्री राम ने यहाँ राज्याभिषेक का मुकुट धारण कर दर्शन दिए थे, अतः इसे "मुडिकोंडन" कहा जाता है। कार्य में सफलता और पदोन्नति हेतु विशेष फलदायी।',
        timings: 'प्रातः 7:00 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['श्री राम नवमी', 'वैकुंठ एकादशी'],
        significance: 'मुकुटधारी श्री राम का दुर्लभ दर्शन। नेतृत्व क्षमता एवं सफलता प्रदायक।',
      },
    },
  },
  {
    id: 'uma-maheswarar-konerirajapuram',
    name: 'Sri Uma Maheswarar Temple (Swayambhu Natarajar), Konerirajapuram',
    city: 'Konerirajapuram (Kumbakonam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Chola era (built by Queen Sembiyan Mahadevi)',
    category: 'Shiva',
    designation: 'Paadal Petra Sthalam',
    history: 'Sri Uma Maheswarar Temple in Konerirajapuram (Thirunallam) near Kumbakonam was constructed by the illustrious Chola Queen Sembiyan Mahadevi. The temple enshrines the LARGEST bronze Nataraja idol in the world, sculpted as a direct manifestation (Swayambhu) of Lord Shiva. The sthala purana recounts that when the sculptor was troubled by the king\'s deadline, Lord Shiva and Parvati came as elderly mendicants, drank water, and transformed into the magnificent bronze icon. Devotees also worship here to cure leprosy, skin ailments, and Vaatha disorders.',
    timings: '6:30 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Arudra Darshan', 'Aani Thirumanjanam', 'Maha Shivaratri', 'Panguni Uthiram'],
    significance: 'World\'s largest bronze Nataraja icon. Direct swayambhu manifestation of Nataraja. Queen Sembiyan Mahadevi\'s architectural masterpiece. Cures severe skin diseases and Vaatha afflictions.',
    mapsUrl: 'https://maps.google.com/?q=Uma+Maheswarar+Temple+Konerirajapuram',
    sourceUrl: 'https://www.visittemples.com/hindu/sriumamaheswararorsriswayambhunatarajartemplekonerirajapuramnearkumbakonamtamilnadu',
    lat: 10.9850, lng: 79.5540,
    translations: {
      ta: {
        name: 'அருள்மிகு உமாமகேஸ்வரர் திருக்கோயில் (சுயம்பு நடராஜர்), கோனேரிராஜபுரம்',
        city: 'கோனேரிராஜபுரம் (கும்பகோணம்)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: 'பாடல் பெற்ற தலம்',
        history: 'செம்பியன் மாதேவியால் கட்டப்பட்ட உலகப் புகழ்பெற்ற சோழர் கால கலைப் பொக்கிஷம். உலகிலேயே மிகப்பெரிய வெண்கல நடராஜர் திருமேனி இங்கு அமைந்துள்ளது. சிற்பிக்கு உதவ ஈசனே நேரில் வந்து வெண்கலச் சிலையாக காட்சியளித்த அற்புதத் தலம். தோல் வியாதிகள் மற்றும் வாத நோய்கள் தீர அருள்பாலிக்கும் தலம்.',
        timings: 'காலை 6:30 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['ஆருத்ரா தரிசனம்', 'ஆனி திருமஞ்சனம்', 'மஹா சிவராத்திரி'],
        significance: 'உலகின் மிகப்பெரிய வெண்கல நடராஜர் சிலை. செம்பியன் மாதேவி கட்டிய சோழர் காலப் பொக்கிஷம்.',
      },
      hi: {
        name: 'श्री उमामहेश्वरर मंदिर (स्वयंभू नटराज), कोनेरीराजपुरम',
        city: 'कोनेरीराजपुरम (कुम्भकोणम)',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: 'पादल पेत्र स्थलम',
        history: 'चोल महारानी सेम्बियन महादेवी द्वारा निर्मित पावन धाम। यहाँ विश्व की सबसे बड़ी कांस्य नटराज प्रतिमा स्थापित है। साक्षात शिव जी ने स्वयं प्रकट होकर मूर्तिकार को दर्शन दिए थे। असाध्य रोगों और त्वचा विकारों के निवारण हेतु विख्यात।',
        timings: 'प्रातः 6:30 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['आर्द्रा दर्शन', 'आनि तिरुमंजनम', 'महाशिवरात्रि'],
        significance: 'विश्व की विशालतम कांस्य नटराज प्रतिमा का पावन धाम।',
      },
    },
  },
  {
    id: 'palaivananathar-papanasam',
    name: 'Sri Palaivananathar Temple, Papanasam',
    city: 'Papanasam (Kumbakonam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, Chola era',
    category: 'Shiva',
    designation: 'Paadal Petra Sthalam',
    history: 'Sri Palaivananathar Temple in Papanasam near Kumbakonam is celebrated in the Devaram padhigams of Appar. "Papanasam" translates to "the Annihilator of Sins". The temple is unique for enshrining 108 Shivalingas within its sacred precincts. The presiding deity is Palaivananathar and the Goddess is Dhavala Vennagai Ammai. Legend says that worshipping the 108 Lingas here absolves all lingering sins and ancestral afflictions.',
    timings: '6:30 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Panguni Uthiram', 'Maha Shivaratri', 'Arudra Darshan'],
    significance: 'Celebrated Paadal Petra Sthalam enshrining 108 Shivalingas. Eradicates deep-seated sins (Papa Vinasanam) and restores peace of mind.',
    mapsUrl: 'https://maps.google.com/?q=Palaivananathar+Temple+Papanasam',
    sourceUrl: 'https://www.visittemples.com/hindu/sripalaivananathartemplepapanasamnearkumbakonamtamilnadu',
    lat: 10.9250, lng: 79.2890,
    translations: {
      ta: {
        name: 'அருள்மிகு பாலைவனநாதர் திருக்கோயில், பாபநாசம்',
        city: 'பாபநாசம் (கும்பகோணம்)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: 'பாடல் பெற்ற தலம்',
        history: 'கும்பகோணம் அருகே உள்ள பாபநாசத்தில் அமைந்த தேவாரம் பாடல் பெற்ற தலம். "பாபநாசம்" என்றால் பாவங்களை நாசம் செய்யும் தலம் என்று பொருள். அப்பர் பெருமானால் பாடப்பட்டது. இக்கோயிலில் 108 சிவலிங்கங்கள் பிரதிஷ்டை செய்யப்பட்டுள்ளது தனிச்சிறப்பாகும். சகல பாவங்களும் நீங்க இத்தல தரிசனம் விசேஷம்.',
        timings: 'காலை 6:30 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['பங்குனி உத்திரம்', 'மஹா சிவராத்திரி'],
        significance: '108 சிவலிங்கங்கள் அருளும் தலம். பாவங்களை நீக்கி புனிதம் நல்கும் பாபநாசம்.',
      },
      hi: {
        name: 'श्री पालैवनानाथर मंदिर, पापनासम',
        city: 'पापनासम (कुम्भकोणम)',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: 'पादल पेत्र स्थलम',
        history: 'कुम्भकोणम के निकट पापनासम समस्त पापों का नाश करने वाला देवारम पादल पेत्र तीर्थ है। मंदिर परिसर में 108 शिवलिंग स्थापित हैं। संत अप्पर द्वारा रचित भजनों में इसकी महिमा वर्णित है।',
        timings: 'प्रातः 6:30 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['पंगुनि उत्तिरम', 'महाशिवरात्रि'],
        significance: '108 शिवलिंगों का पावन धाम जो समस्त पापों का समूल नाश करता है।',
      },
    },
  },
  {
    id: 'soundararaja-perumal-sundaraperumalkoil',
    name: 'Sri Soundararaja Perumal Temple, Sundaraperumalkoil',
    city: 'Sundaraperumalkoil (Papanasam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient, Kulothunga Chola era',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Soundararaja Perumal Temple is located in Sundaraperumalkoil near Papanasam in the Cauvery delta region. Dedicated to Lord Vishnu in His captivatingly handsome manifestation as Soundararaja Perumal (the King of Supreme Beauty) with Consort Soundaravalli Thayar, the temple features exquisite Chola stone carvings and a sacred temple tank. Worshippers pray for family prosperity and handsome, virtuous progeny.',
    timings: '7:00 AM – 11:30 AM | 5:00 PM – 8:00 PM',
    festivals: ['Vaikunta Ekadasi', 'Panguni Brahmotsavam', 'Purattasi Saturdays'],
    significance: 'Historic Chola era Vishnu temple renowned for the sublime beauty of Lord Soundararaja Perumal.',
    mapsUrl: 'https://maps.google.com/?q=Soundararaja+Perumal+Temple+Sundaraperumalkoil',
    sourceUrl: 'https://www.visittemples.com/hindu/srisoundararajaperumaltemplesundaraperumalkoilnearpapanasamkumbakonamtamilnadu',
    lat: 10.9180, lng: 79.3120,
    translations: {
      ta: {
        name: 'அருள்மிகு சௌந்தரராஜ பெருமாள் திருக்கோயில், சுந்தரபெருமாள்கோவில்',
        city: 'சுந்தரபெருமாள்கோவில் (பாபநாசம்)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'பாபநாசம் அருகே சுந்தரபெருமாள்கோவிலில் அமைந்துள்ள சோழர் கால விஷ்ணு ஆலயம். பேரழகு மிளிரும் சௌந்தரராஜ பெருமாள் மற்றும் சௌந்தரவல்லி தாயார் அருள்பாலிக்கின்றனர். குடும்ப அமைதி மற்றும் சந்ததி மேன்மை பெற பக்தர்கள் வழிபடுகின்றனர்.',
        timings: 'காலை 7:00 – 11:30 | மாலை 5:00 – 8:00',
        festivals: ['வைகுண்ட ஏகாதசி', 'புரட்டாசி சனிக்கிழமைகள்'],
        significance: 'சோழர் கால அழகிய பெருமாள் திருக்கோயில். மங்கல வாழ்வு தரும் சௌந்தரராஜர்.',
      },
      hi: {
        name: 'श्री सौंदरराज पेरुमाल मंदिर, सुंदरपेरुमालकोइल',
        city: 'सुंदरपेरुमालकोइल (पापनासम)',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'पापनासम के निकट चोल काल का भव्य विष्णु मंदिर। भगवान विष्णु अपने अति सुंदर सौंदरराज रूप में माँ सौंदरवल्ली के साथ विराजमान हैं।',
        timings: 'प्रातः 7:00 – 11:30 | सायं 5:00 – 8:00',
        festivals: ['वैकुंठ एकादशी', 'पंगुनि ब्रह्मोत्सव'],
        significance: 'अति मनोहारी स्वरूप वाले भगवान सौंदरराज का पावन धाम।',
      },
    },
  },
];

let kumbakonamCode = fs.readFileSync('src/data/kumbakonamTemples.js', 'utf8');
const lastIndexKumbakonam = kumbakonamCode.lastIndexOf('];');
if (lastIndexKumbakonam !== -1) {
  const newItemsStr = ',\n' + JSON.stringify(kumbakonamAdditions, null, 2).slice(1, -1).trim() + '\n';
  kumbakonamCode = kumbakonamCode.slice(0, lastIndexKumbakonam) + newItemsStr + kumbakonamCode.slice(lastIndexKumbakonam);
  fs.writeFileSync('src/data/kumbakonamTemples.js', kumbakonamCode, 'utf8');
  console.log('Successfully appended 6 temples to kumbakonamTemples.js');
}

// --- 5. TAMIL NADU TEMPLES (COIMBATORE, ERODE, TIRUPPUR, RAMANATHAPURAM) ---
const tamilnaduAdditions = [
  {
    id: 'pamban-swamigal-pirappanvalasai',
    name: 'Sri Pamban Swamigal Temple, Pirappanvalasai',
    city: 'Pirappanvalasai (Ramanathapuram)',
    state: 'Tamil Nadu',
    image: '',
    period: '19th–20th Century CE',
    category: 'Murugan',
    designation: 'Jeeva Samadhi / Avatara Sthalam',
    history: 'Sri Pamban Swamigal Temple at Pirappanvalasai in Ramanathapuram district is the sacred birthplace of the great 20th-century Murugan saint-poet Srimat Pamban Kumaragurudasa Swamigal (1848–1929). Located on the route to Rameswaram, this serene shrine houses a south-facing welcome arch leading to the sanctum where Pamban Swamigal performed rigorous tapasya and composed immortal Tamil devotional hymns including Shanmuga Kavasam. Murugan devotees revere this shrine for healing, spiritual awakening, and protection from all adversaries.',
    timings: '6:00 AM – 12:00 PM | 4:30 PM – 8:00 PM',
    festivals: ['Pamban Swamigal Guru Pooja', 'Skanda Sashti', 'Thai Poosam', 'Panguni Uthiram'],
    significance: 'Sacred birthplace and penance hermitage of Saint Pamban Swamigal, author of Shanmuga Kavasam. Powerful shrine for Murugan grace and disease healing.',
    mapsUrl: 'https://maps.google.com/?q=Pamban+Swamigal+Temple+Pirappanvalasai+Ramanathapuram',
    sourceUrl: 'https://www.visittemples.com/hindu/sripambanswamigaltemplepirappanvalasairamanathapuramdistricttamilnadu',
    lat: 9.3520, lng: 78.9510,
    translations: {
      ta: {
        name: 'அருள்மிகு பாம்பன் சுவாமிகள் திருக்கோயில், பிரப்பன்வலசை',
        city: 'பிரப்பன்வலசை (ராமநாதபுரம்)',
        state: 'தமிழ்நாடு',
        category: 'முருகன்',
        designation: 'அவதாரத் தலம்',
        history: 'சண்முக கவசம் அருளிய ஒப்பற்ற முருக பக்தரான ஸ்ரீமத் பாம்பன் குமரகுருதாச சுவாமிகள் அவதரித்த புண்ணிய பூமி பிரப்பன்வலசை (ராமேஸ்வரம் செல்லும் வழி). சுவாமிகள் தவம் இயற்றி முருகனின் பேரருள் பெற்ற தலம். நோய்கள் தீரவும், எதிர்ப்புகள் அகலவும் சண்முக கவச பாராயணம் செய்வோருக்கு இது கண்கண்ட புண்ணிய பூமி.',
        timings: 'காலை 6:00 – 12:00 | மாலை 4:30 – 8:00',
        festivals: ['பாம்பன் சுவாமிகள் குருபூஜை', 'கந்த சஷ்டி', 'தைப்பூசம்'],
        significance: 'பாம்பன் சுவாமிகளின் அவதாரத் தலம். சண்முக கவசம் பிறந்த புண்ணிய பூமி. முருகப் பெருமானின் விசேஷ அருள் தலம்.',
      },
      hi: {
        name: 'श्री पाम्बन स्वामीगल मंदिर, पिरप्पनवलसै',
        city: 'पिरप्पनवलसै (रामनाथपुरम)',
        state: 'तमिलनाडु',
        category: 'मुरुगन',
        designation: 'अवतार स्थल',
        history: 'रामेश्वरम मार्ग पर स्थित महान मुरुगन संत पाम्बन स्वामीगल की पावन जन्मस्थली। उन्होंने यहाँ घोर तपस्या कर प्रसिद्ध "षण्मुख कवचं" की रचना की थी। मुरुगन भक्तों के लिए यह अत्यंत सिद्ध और कल्याणकारी तीर्थ है।',
        timings: 'प्रातः 6:00 – 12:00 | सायं 4:30 – 8:00',
        festivals: ['पाम्बन स्वामी गुरु पूजा', 'स्कंद षष्ठी', 'थाई पूसम'],
        significance: 'षण्मुख कवचं के रचयिता संत पाम्बन स्वामीगल की जन्मस्थली। मुरुगन कृपा का पावन केंद्र।',
      },
    },
  },
  {
    id: 'subramaniya-swamy-chennimalai',
    name: 'Sri Subramaniya Swamy Temple, Chennimalai',
    city: 'Chennimalai (Erode)',
    state: 'Tamil Nadu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Chennimalai_Murugan_Temple.jpg/320px-Chennimalai_Murugan_Temple.jpg',
    period: 'Ancient, Kongu Chola era',
    category: 'Murugan',
    designation: '',
    history: 'Sri Subramaniya Swamy Temple in Chennimalai, Erode district, is a celebrated hill shrine situated atop a hill of 1,320 steps. Lord Muruga is worshipped here as Siragiri Velan. Legend says that the divine serpents Adisesha and Garuda fought here, creating this hill resembling the head of the serpent. The celebrated poet Saravana Munivar composed the famous "Kanda Sashti Kavasam" hymns linked to this shrine. A miraculous feature of Chennimalai is that curd and milk offered to Lord Muruga here do not sour for days.',
    timings: '6:00 AM – 8:30 PM continuously',
    festivals: ['Thai Poosam (Grand 15-day chariot festival)', 'Panguni Uthiram', 'Skanda Sashti', 'Vaikasi Visakam'],
    significance: 'Famous Kongu Nadu hill temple of Lord Muruga (1,320 steps). Celebrated for Thai Poosam ther (car festival). Sacred soil associated with Kanda Sashti Kavasam.',
    mapsUrl: 'https://maps.google.com/?q=Chennimalai+Murugan+Temple+Erode',
    sourceUrl: 'https://www.visittemples.com/hindu/srisubramaniyaswamytemplechennimalaierodedistricttamilnadu',
    lat: 11.1685, lng: 77.6110,
    translations: {
      ta: {
        name: 'அருள்மிகு சுப்பிரமணிய சுவாமி திருக்கோயில், சென்னிமலை',
        city: 'சென்னிமலை (ஈரோடு)',
        state: 'தமிழ்நாடு',
        category: 'முருகன்',
        designation: '',
        history: 'ஈரோடு மாவட்டம் சென்னிமலையில் 1320 படிகளுடன் கூடிய மலை மீது அமைந்த பிரசித்தி பெற்ற முருகன் திருக்கோயில். மூலவர்: சிரகிரி வேலவன் (சென்னிமலை ஆண்டவர்). ஆதிசேஷனுக்கும் கருடனுக்கும் நடந்த போரில் உருவான மலை என்பது புராண வரலாறு. கந்த சஷ்டி கவசம் அரங்கேறிய தலங்களில் ஒன்றாக போற்றப்படுகிறது. இங்கு முருகனுக்கு அபிஷேகம் செய்யப்படும் தயிர் புளிப்பதில்லை என்பது ஓர் அற்புத உண்மை.',
        timings: 'காலை 6:00 – இரவு 8:30',
        festivals: ['தைப்பூசத் தேர்த்திருவிழா', 'பங்குனி உத்திரம்', 'கந்த சஷ்டி'],
        significance: 'கொங்கு மண்டலத்தின் தலைசிறந்த மலைக்கோயில். 1320 படிகள் கொண்ட மலை மீது சிரகிரி வேலவன் அருள்வடிவம்.',
      },
      hi: {
        name: 'श्री सुब्रमण्य स्वामी मंदिर, चेन्निमलई',
        city: 'चेन्निमलई (इरोड)',
        state: 'तमिलनाडु',
        category: 'मुरुगन',
        designation: '',
        history: 'इरोड जिले में 1320 सीढ़ियों वाली रमणीय पहाड़ी पर स्थित भगवान मुरुगन का प्रसिद्ध मंदिर। भगवान यहाँ "शिरगिरि वेलन" रूप में पूजे जाते हैं। यहाँ मुरुगन को अर्पित दही दिनों तक खट्टा नहीं होता। प्रसिद्ध स्कंद षष्ठी कवचं से संबंधित पावन स्थल।',
        timings: 'प्रातः 6:00 – रात्रि 8:30',
        festivals: ['थाई पूसम रथोत्सव', 'पंगुनि उत्तिरम', 'स्कंद षष्ठी'],
        significance: 'कोंगुनाडु का प्रसिद्ध पर्वत धाम। 1320 सीढ़ियों वाला जाग्रत मुरुगन मंदिर।',
      },
    },
  },
  {
    id: 'subramaniya-swamy-sivanmalai',
    name: 'Sri Subramaniya Swamy Temple, Sivanmalai',
    city: 'Sivanmalai (Kangeyam/Tiruppur)',
    state: 'Tamil Nadu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sivanmalai_Murugan_temple.jpg/320px-Sivanmalai_Murugan_temple.jpg',
    period: 'Ancient, Chera–Chola era',
    category: 'Murugan',
    designation: '',
    history: 'Sri Subramaniya Swamy Temple in Sivanmalai near Kangeyam, Tiruppur district, is renowned throughout India for its unique "Aandavan Utharavu" (Divine Command Miracle Box). Lord Muruga appears in the dream of a devotee and commands a specific item (such as gold, water, grain, sand, iron) to be placed inside a sealed glass box in the sanctum. Whatever item is placed inside heralds real-world events affecting the nation and society, a prophetic tradition that has unfailingly come true for centuries.',
    timings: '6:00 AM – 12:30 PM | 4:00 PM – 8:30 PM',
    festivals: ['Thai Poosam (Famous 3-day car festival)', 'Panguni Uthiram', 'Soorasamharam', 'Karthigai Deepam'],
    significance: 'World-famous for the prophetic "Aandavan Utharavu" miracle box where items placed by divine dream command predict future social events. 18-step sacred Kangeyam hill temple.',
    mapsUrl: 'https://maps.google.com/?q=Sivanmalai+Murugan+Temple+Kangeyam',
    sourceUrl: 'https://www.visittemples.com/hindu/srisubramaniyaswamytemplesivanmalainearkangeyamtiruppurdistricttamilnadu',
    lat: 11.0289, lng: 77.5612,
    translations: {
      ta: {
        name: 'அருள்மிகு சுப்பிரமணிய சுவாமி திருக்கோயில், சிவன்மலை',
        city: 'சிவன்மலை (காங்கேயம், திருப்பூர்)',
        state: 'தமிழ்நாடு',
        category: 'முருகன்',
        designation: '',
        history: 'திருப்பூர் மாவட்டம் காங்கேயம் அருகே சிவன்மலையில் அமைந்துள்ள புகழ்பெற்ற முருகன் திருக்கோயில். இக்கோயிலின் உலகப் பிரசித்தி பெற்ற அம்சம் "ஆண்டவன் உத்தரவுப் பெட்டி" ஆகும். முருகன் பக்தரின் கனவில் தோன்றி உத்தரவிடும் பொருளை (தங்கம், நீர், மணல், தானியம், இரும்பு போன்றவை) கண்ணாடிப் பெட்டியில் வைத்து பூஜிப்பர். அந்த பொருள் சார்ந்த நிகழ்வுகள் உலகளவில் தாக்கத்தை ஏற்படுத்தும் என்பது நூற்றாண்டுகளாக நடக்கும் அதிசயம்.',
        timings: 'காலை 6:00 – மதியம் 12:30 | மாலை 4:00 – இரவு 8:30',
        festivals: ['தைப்பூசத் தேரோட்டம்', 'பங்குனி உத்திரம்', 'சூரசம்ஹாரம்'],
        significance: 'எதிர்காலத்தை உணர்த்தும் ஆண்டவன் உத்தரவுப் பெட்டி கொண்ட அதிசயத் தலம். காங்கேயம் காளைகளின் பூமிக்கு மகுடமாய் விளங்கும் சிவன்மலை.',
      },
      hi: {
        name: 'श्री सुब्रमण्य स्वामी मंदिर, शिवन्मलई',
        city: 'शिवन्मलई (कांगेयम, तिरुप्पुर)',
        state: 'तमिलनाडु',
        category: 'मुरुगन',
        designation: '',
        history: 'तिरुप्पुर जिले के कांगेयम में स्थित भगवान मुरुगन का चमत्कारी मंदिर। यह मंदिर अपनी "आंडवन उत्तरवु" (दिव्य आज्ञा पेटी) के लिए प्रसिद्ध है, जिसमें भगवान स्वप्न में जो वस्तु रखने का आदेश देते हैं, उसे कांच के बक्से में रखा जाता है और वह भविष्यवाणी के रूप में समाज में घटित होती है।',
        timings: 'प्रातः 6:00 – दोपहर 12:30 | सायं 4:00 – रात्रि 8:30',
        festivals: ['थाई पूसम रथोत्सव', 'पंगुनि उत्तिरम', 'सूरसंहारम'],
        significance: 'चमत्कारिक भविष्यसूचक दिव्य पेटी वाला प्रसिद्ध मुरुगन पर्वत धाम।',
      },
    },
  },
  {
    id: 'avinashi-lingeshwarar-temple',
    name: 'Sri Avinashilingeshwarar Temple, Avinashi',
    city: 'Avinashi (Tiruppur)',
    state: 'Tamil Nadu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Avinashiappar_temple.jpg/320px-Avinashiappar_temple.jpg',
    period: 'Ancient, Kongu Chola/Pandya era (7th Century CE)',
    category: 'Shiva',
    designation: 'Devaram Paadal Petra Sthalams',
    history: 'Sri Avinashilingeshwarar Temple in Avinashi, Tiruppur district, is the most celebrated Devaram Paadal Petra Sthalam of the Kongu region. Presiding deity is Lord Shiva as Avinashiappar (the Indestructible Lord) and Mother Karunambigai. The temple is immortalized by Saint Sundaramoorthy Nayanar, who sang the Devaram padhigam and miraculously resurrected a young boy swallowed by a crocodile from the dry river tank three years prior. Devotees pray here to ward off unnatural death (Akalamrithyu) and protect children.',
    timings: '6:00 AM – 1:00 PM | 4:00 PM – 8:30 PM',
    festivals: ['Chithirai Ther Thiruvizha (Grand Chariot)', 'Maha Shivaratri', 'Arudra Darshan'],
    significance: 'Supreme Paadal Petra Sthalam of Kongu Nadu. Famous for Sundarar\'s crocodile miracle (Mudalai Vaai Pillai). Cures mortal fears and protects children.',
    mapsUrl: 'https://maps.google.com/?q=Avinashilingeshwarar+Temple+Avinashi',
    sourceUrl: 'https://www.visittemples.com/hindu/sriavinashilingeshwarartempleavinashitiruppurdistricttamilnadu',
    lat: 11.1920, lng: 77.2685,
    translations: {
      ta: {
        name: 'அருள்மிகு அவிநாசிலிங்கேஸ்வரர் திருக்கோயில், அவிநாசி',
        city: 'அவிநாசி (திருப்பூர்)',
        state: 'தமிழ்நாடு',
        category: 'சிவன்',
        designation: 'தேவாரம் பாடல் பெற்ற தலம்',
        history: 'கொங்கு மண்டலத்தின் முதன்மை தேவாரம் பாடல் பெற்ற சிவத்தலம் அவிநாசி. மூலவர்: அவிநாசியப்பர். அம்பாள்: கருணாம்பிகை. சுந்தரமூர்த்தி நாயனார் பாடிய "எற்றான் மறக்கேன்" பதிகத்தின் மகிமையால், மூன்று ஆண்டுகளுக்கு முன்பு முதலையால் விழுங்கப்பட்ட சிறுவன் குளத்திலிருந்து உயிருடன் மீட்டுத் தரப்பட்ட அற்புதம் நிகழ்ந்த தலம். அவிநாசி தேர்த்திருவிழா தென்னிந்தியாவின் மிகப்பெரிய தேர்களில் ஒன்றாகும்.',
        timings: 'காலை 6:00 – மதியம் 1:00 | மாலை 4:00 – இரவு 8:30',
        festivals: ['சித்திரைத் தேர்த்திருவிழா', 'மஹா சிவராத்திரி', 'முதலை வாய் பிள்ளை உற்சவம்'],
        significance: 'சுந்தரரின் முதலை வாய் பிள்ளை மீட்ட வரலாற்றுப் பாடல் பெற்ற தலம். அகால மரணம் நீங்கவும் குழந்தைகள் நலம் பெறவும் அருளும் தலம்.',
      },
      hi: {
        name: 'श्री अविनाशीलिंगेश्वरर मंदिर, अविनाशी',
        city: 'अविनाशी (तिरुप्पुर)',
        state: 'तमिलनाडु',
        category: 'शिव',
        designation: 'देवारम पादल पेत्र स्थलम',
        history: 'कोंगु क्षेत्र का सबसे प्रतिष्ठित देवारम पादल पेत्र शिव मंदिर। भगवान अविनाशीअप्पर और माता करुणाम्बिका यहाँ विराजमान हैं। संत सुंदरर ने यहाँ देवारम भजन गाकर मगरमच्छ द्वारा निगले गए बालक को तीन वर्ष बाद पुनः जीवित निकाला था। यहाँ का रथ उत्सव दक्षिण भारत के विशालतम उत्सवों में है।',
        timings: 'प्रातः 6:00 – दोपहर 1:00 | सायं 4:00 – रात्रि 8:30',
        festivals: ['चित्तिरै महा रथोत्सव', 'महाशिवरात्रि'],
        significance: 'अकाल मृत्यु निवारण एवं बाल रक्षा का सर्वोच्च तीर्थ। संत सुंदरर का मगरमच्छ चमत्कार स्थल।',
      },
    },
  },
  {
    id: 'ranganatha-swamy-karamadai',
    name: 'Sri Ranganatha Swamy Temple, Karamadai',
    city: 'Karamadai (Coimbatore)',
    state: 'Tamil Nadu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Karamadai_Ranganathar_temple.jpg/320px-Karamadai_Ranganathar_temple.jpg',
    period: 'Ancient, Hoysala/Vijayanagara era (over 1000 years old)',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Ranganatha Swamy Temple in Karamadai is the oldest and most prominent Vaishnava temple in Coimbatore district, located near Mettupalayam. The presiding deity is a Swayambhu (self-manifested) stone Linga-form transformed into Ranganatha Swamy, alongside Goddess Ranganayaki. The temple is famous for the "Bandaru Seva" where devotees toss betel nut powder in jubilation during the annual car festival. Devotees seeking relief from eye ailments and business success flock to this holy shrine.',
    timings: '6:00 AM – 12:30 PM | 4:30 PM – 9:00 PM',
    festivals: ['Masi Magam Chariot Festival', 'Vaikunta Ekadasi', 'Panguni Uthiram', 'Purattasi Saturdays'],
    significance: 'The premier Vaishnava pilgrimage center of Coimbatore. Swayambhu Ranganatha idol worshipped for over a millennium. Renowned for Masi Magam Bandaru Seva.',
    mapsUrl: 'https://maps.google.com/?q=Ranganatha+Swamy+Temple+Karamadai+Coimbatore',
    sourceUrl: 'https://www.visittemples.com/hindu/sriranganathaswamytemplekaramadaicoimbatoredistricttamilnadu',
    lat: 11.2435, lng: 76.9585,
    translations: {
      ta: {
        name: 'அருள்மிகு ரங்கநாத சுவாமி திருக்கோயில், காரமடை',
        city: 'காரமடை (கோவை)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'கோவை மாவட்டத்தில் மேட்டுப்பாளையம் அருகே காரமடையில் அமைந்துள்ள 1000 ஆண்டுகளுக்கு முற்பட்ட தொன்மையான வைணவத் தலம். மூலவர் சுயம்புவாக காரை மரத்தடியில் தோன்றிய ஸ்ரீ ரங்கநாதர். தாயார்: ரங்கநாயகி. மாசி மகத் தேர்த்திருவிழாவின் போது பக்தர்கள் பாண்டார சேவை செய்து பாக்குத்தூள் தூவி வழிபடுவது தனிச்சிறப்பு. கண் பார்வைக் கோளாறுகள் நீங்க இத்தல தரிசனம் விசேஷம்.',
        timings: 'காலை 6:00 – மதியம் 12:30 | மாலை 4:30 – இரவு 9:00',
        festivals: ['மாசி மகத் தேர்த்திருவிழா', 'வைகுண்ட ஏகாதசி', 'புரட்டாசி சனிக்கிழமைகள்'],
        significance: 'கோவை மண்டலத்தின் முதன்மை திவ்ய வைணவத் தலம். சுயம்பு ரங்கநாதர் அருள்பாலிக்கும் 1000 ஆண்டு புராதன தலம்.',
      },
      hi: {
        name: 'श्री रंगनाथ स्वामी मंदिर, कारामडई',
        city: 'कारामडई (कोयंबटूर)',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'कोयंबटूर जिले के कारामडई में स्थित 1000 वर्ष से अधिक प्राचीन वैष्णव धाम। यहाँ भगवान रंगनाथ स्वयंभू रूप में प्रकट हुए थे। मासी मघम पर यहाँ का "बंडारु सेवा" और रथ उत्सव अत्यंत प्रसिद्ध है। नेत्र रोगों के निवारण हेतु भक्त यहाँ दर्शन करते हैं।',
        timings: 'प्रातः 6:00 – दोपहर 12:30 | सायं 4:30 – रात्रि 9:00',
        festivals: ['मासी मघम रथोत्सव', 'वैकुंठ एकादशी'],
        significance: 'कोयंबटूर का सबसे प्रमुख प्राचीन रंगनाथ मंदिर। स्वयंभू विग्रह।',
      },
    },
  },
  {
    id: 'kothandaramar-ramnagar-coimbatore',
    name: 'Sri Kothandaramar Temple, Ram Nagar',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    image: '',
    period: '20th Century CE (approx. 1955)',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Kothandaramar Temple in Ram Nagar, Coimbatore, is revered as the "Ayodhya of Coimbatore". Modelled after the classical Ayodhya temple style, the sanctum enshrines Sri Rama holding His celestial bow Kothandam, along with Sita Devi, Lakshmana, and Anjaneya. Devotees participate in year-round Rama bhajans, Akhanda Nama Sankirtanam, and celebrate a grand 10-day Sri Rama Navami Mahotsavam.',
    timings: '6:30 AM – 11:30 AM | 5:00 PM – 8:30 PM',
    festivals: ['Sri Rama Navami (10 days)', 'Hanumath Jayanthi', 'Vaikunta Ekadasi'],
    significance: 'Celebrated as the Ayodhya of Coimbatore. Centre of spiritual discourse, Rama Nama Japa, and peace.',
    mapsUrl: 'https://maps.google.com/?q=Kothandaramar+Temple+Ram+Nagar+Coimbatore',
    sourceUrl: 'https://www.visittemples.com/hindu/srikothandaramartempleramnagarcoimbatoretamilnadu',
    lat: 11.0165, lng: 76.9630,
    translations: {
      ta: {
        name: 'அருள்மிகு கோதண்டராமர் திருக்கோயில், ராம் நகர்',
        city: 'கோவை (ராம் நகர்)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'கோவையின் மையப்பகுதியான ராம் நகரில் அமைந்துள்ள புகழ்பெற்ற ராமர் கோயில். "கோவையின் அயோத்தி" என்று போற்றப்படும் இத்தலத்தில் ஸ்ரீ கோதண்டராமர், சீதா பிராட்டி, லட்சுமணர், ஆஞ்சநேயர் சமேதராக அருள்பாலிக்கிறார். ராம நாம பஜனை மற்றும் ராம நவமி உற்சவத்திற்கு மிகவும் பிரசித்தி பெற்றது.',
        timings: 'காலை 6:30 – 11:30 | மாலை 5:00 – 8:30',
        festivals: ['ஸ்ரீ ராம நவமி', 'வைகுண்ட ஏகாதசி', 'ஹனுமத் ஜெயந்தி'],
        significance: 'கோவையின் அயோத்தி எனப் போற்றப்படும் தலம். ராம நாமம் ஜெபித்து மன அமைதி பெறும் புனிதத் தலம்.',
      },
      hi: {
        name: 'श्री कोदंडरामार मंदिर, राम नगर',
        city: 'कोयंबटूर',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'कोयंबटूर के राम नगर में स्थित "कोयंबटूर की अयोध्या" कहा जाने वाला भव्य राम मंदिर। धनुर्धारी श्री कोदंडराम, सीता माता, लक्ष्मण जी और हनुमान जी यहाँ मनोहारी रूप में विराजित हैं।',
        timings: 'प्रातः 6:30 – 11:30 | सायं 5:00 – 8:30',
        festivals: ['श्री राम नवमी', 'वैकुंठ एकादशी'],
        significance: 'कोयंबटूर का प्रतिष्ठित राम धाम। राम नाम संकीर्तन का प्रमुख केंद्र।',
      },
    },
  },
  {
    id: 'panchamugha-anjaneyar-vadavalli',
    name: 'Sri Panchamugha Anjaneyar Temple, Vadavalli',
    city: 'Vadavalli (Coimbatore)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Contemporary',
    category: 'Other',
    designation: '',
    history: 'Sri Panchamugha Anjaneyar Temple is situated at Vadavalli at the foothills of Marudhamalai in Coimbatore. The temple enshrines a gigantic, awe-inspiring monolithic statue of Sri Panchamukha Anjaneya (Five-faced Hanuman combining the faces of Anjaneya, Narasimha, Garuda, Varaha, and Hayagriva). Devotees offer butter, betel leaf garlands, and vadas to obtain relief from Sani (Saturn) dosha, evil spirits, and critical obstacles.',
    timings: '6:30 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Hanumath Jayanthi', 'Maha Shivaratri', 'Tamil New Year', 'Saturdays special pooja'],
    significance: 'Majestic five-faced Anjaneya temple near Marudhamalai. Destroys fears, evil spirits, and malefic planetary afflictions.',
    mapsUrl: 'https://maps.google.com/?q=Panchamukha+Anjaneyar+Temple+Vadavalli+Coimbatore',
    sourceUrl: 'https://www.visittemples.com/hindu/sripanchamughaanjaneyartemplevadavallicoimbatoredistricttamilnadu',
    lat: 11.0265, lng: 76.9015,
    translations: {
      ta: {
        name: 'அருள்மிகு பஞ்சமுக ஆஞ்சநேயர் திருக்கோயில், வடவள்ளி',
        city: 'வடவள்ளி (கோவை)',
        state: 'தமிழ்நாடு',
        category: 'மற்றவை',
        designation: '',
        history: 'கோவை மருதமலை அடிவாரத்தில் வடவள்ளியில் அமைந்துள்ள கம்பீரமான பஞ்சமுக ஆஞ்சநேயர் கோயில். ஆஞ்சநேயர், நரசிம்மர், கருடன், வராகர், ஹயக்ரீவர் ஆகிய ஐந்து முகங்களுடன் கூடிய பிரம்மாண்ட திருவுருவம். சனி தோஷம், பயம், எதிரிகள் தொல்லை நீங்க வெற்றிலை மாலை மற்றும் வெண்ணெய் சாற்றி வழிபடும் தலம்.',
        timings: 'காலை 6:30 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['ஹனுமத் ஜெயந்தி', 'சனிக்கிழமை சிறப்பு வழிபாடு'],
        significance: 'ஐந்து திருமுகங்களுடன் அருளும் பிரம்மாண்ட பஞ்சமுக ஆஞ்சநேயர் தலம். சகல பயங்களையும் போக்கும் தலம்.',
      },
      hi: {
        name: 'श्री पंचमुख आंजनेयर मंदिर, वडवल्ली',
        city: 'वडवल्ली (कोयंबटूर)',
        state: 'तमिलनाडु',
        category: 'अन्य',
        designation: '',
        history: 'मरुदमलई की तलहटी में स्थित पंचमुख हनुमान जी का दिव्य मंदिर (हनुमान, नरसिंह, गरुड़, वराह, हयग्रीव मुख)। शनि दोष और भय से मुक्ति हेतु यहाँ मक्खन और पान की माला अर्पित की जाती है।',
        timings: 'प्रातः 6:30 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['हनुमान जयंती', 'शनिवार विशेष दर्शन'],
        significance: 'शक्तिशाली पंचमुख हनुमान धाम जो समस्त संकटों का नाश करता है।',
      },
    },
  },
  {
    id: 'venkateswara-swamy-peelamedu',
    name: 'Sri Venkateswara Swamy Temple, Peelamedu',
    city: 'Coimbatore (Peelamedu)',
    state: 'Tamil Nadu',
    image: '',
    period: '20th Century CE',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Venkateswara Swamy Temple in Peelamedu, Coimbatore, is reverently known as the "Chinna Tirupati" of Coimbatore. Built according to Tirumala Vaikhanasa Agama traditions, the presiding deity is an exact manifestation of Lord Venkateswara (Balaji) in standing pose with Padmavathi Thayar. Devotees who cannot undertake the physical journey to Tirumala offer their vows and hair offerings (Mundan) here.',
    timings: '6:00 AM – 12:00 PM | 4:30 PM – 8:30 PM',
    festivals: ['Brahmotsavam', 'Vaikunta Ekadasi', 'Purattasi Saturdays', 'Pavithrotsavam'],
    significance: 'Known as the Chinna Tirupati of Coimbatore. Provides the divine spiritual experience of Tirumala Balaji darshan.',
    mapsUrl: 'https://maps.google.com/?q=Venkateswara+Swamy+Temple+Peelamedu+Coimbatore',
    sourceUrl: 'https://www.visittemples.com/hindu/srivenkateswaraswamytemplepeelameducoimbatoretamilnadu',
    lat: 11.0255, lng: 77.0125,
    translations: {
      ta: {
        name: 'அருள்மிகு வெங்கடேஸ்வர சுவாமி திருக்கோயில், பீளமேடு',
        city: 'கோவை (பீளமேடு)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'கோவையில் பீளமேடு பகுதியில் அமைந்துள்ள "சின்ன திருப்பதி" எனப் போற்றப்படும் பாலாஜி திருக்கோயில். திருப்பதி ஏழுமலையான் வடிவிலேயே பத்மாவதி தாயாருடன் அருள்பாலிக்கிறார். திருப்பதி செல்ல முடியாத பக்தர்கள் இங்கு வந்து காணிக்கை செலுத்தி வழிபடுகின்றனர்.',
        timings: 'காலை 6:00 – 12:00 | மாலை 4:30 – 8:30',
        festivals: ['வைகுண்ட ஏகாதசி', 'புரட்டாசி சனிக்கிழமைகள்', 'பிரம்மோற்சவம்'],
        significance: 'கோவையின் சின்ன திருப்பதி. திருப்பதி பெருமாளின் அதே அருட்காட்சி தரும் தலம்.',
      },
      hi: {
        name: 'श्री वेंकटेश्वर स्वामी मंदिर, पीलामेडु',
        city: 'कोयंबटूर (पीलामेडु)',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'कोयंबटूर के पीलामेडु में स्थित "छोटा तिरुपति" के रूप में विख्यात भगवान वेंकटेश्वर बालाजी का मंदिर। तिरुमला परंपरा अनुसार पूजा और अर्चना होती है।',
        timings: 'प्रातः 6:00 – 12:00 | सायं 4:30 – 8:30',
        festivals: ['वैकुंठ एकादशी', 'पुरट्टासी शनिवार'],
        significance: 'कोयंबटूर का मिनी तिरुपति बालाजी मंदिर।',
      },
    },
  },
  {
    id: 'lakshmi-narasimha-swamy-ukkadam',
    name: 'Sri Lakshmi Narasimha Swamy Temple, Ukkadam',
    city: 'Coimbatore (Ukkadam)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient tradition',
    category: 'Vishnu',
    designation: '',
    history: 'Sri Lakshmi Narasimha Swamy Temple is situated near Ukkadam in Coimbatore. The presiding deity Lord Narasimha is in His benevolent Shanta Lakshmi Narasimha posture holding Mother Lakshmi on His lap. Devotees visit on Swathi nakshatra days and Pradosham to pray for debt relief, freedom from legal litigations, and eradication of enemy obstacles.',
    timings: '6:30 AM – 11:30 AM | 5:00 PM – 8:30 PM',
    festivals: ['Narasimha Jayanthi', 'Vaikunta Ekadasi', 'Swathi Nakshatram monthly pooja'],
    significance: 'Revered Lakshmi Narasimha shrine in Coimbatore. Eradicates debts, fears, legal disputes, and provides protective armor.',
    mapsUrl: 'https://maps.google.com/?q=Lakshmi+Narasimha+Swamy+Temple+Ukkadam+Coimbatore',
    sourceUrl: 'https://www.visittemples.com/hindu/srilakshminarasimhaswamytempleukkadamcoimbatoretamilnadu',
    lat: 10.9912, lng: 76.9615,
    translations: {
      ta: {
        name: 'அருள்மிகு லட்சுமி நரசிம்ம சுவாமி திருக்கோயில், உக்கடம்',
        city: 'கோவை (உக்கடம்)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'கோவையில் உக்கடம் பகுதியில் அமைந்துள்ள லட்சுமி நரசிம்ம சுவாமி திருக்கோயில். மூலவர் சாந்த லட்சுமி நரசிம்மராக தாயாரை மடியில் தாங்கி அருள்பாலிக்கிறார். கடன் சுமை, எதிரிகள் பயம், வழக்குகள் தீர சுவாதி நட்சத்திர நாளில் பானகம் படைத்து வழிபடுவது விசேஷம்.',
        timings: 'காலை 6:30 – 11:30 | மாலை 5:00 – 8:30',
        festivals: ['நரசிம்ம ஜெயந்தி', 'சுவாதி நட்சத்திர வழிபாடு', 'வைகுண்ட ஏகாதசி'],
        significance: 'கடன் தொல்லை மற்றும் பயம் நீக்கும் சாந்த லட்சுமி நரசிம்மர் தலம்.',
      },
      hi: {
        name: 'श्री लक्ष्मी नरसिंह स्वामी मंदिर, उक्कडम',
        city: 'कोयंबटूर (उक्कडम)',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'कोयंबटूर के उक्कडम में स्थित भगवान लक्ष्मी नरसिंह का शांत रूपी मंदिर। स्वाति नक्षत्र पर यहाँ ऋण मुक्ति और संकट निवारण हेतु विशेष पूजा की जाती है।',
        timings: 'प्रातः 6:30 – 11:30 | सायं 5:00 – 8:30',
        festivals: ['नरसिंह जयंती', 'स्वाति नक्षत्र पूजा'],
        significance: 'ऋण मुक्ति एवं शत्रु भय निवारक पावन नरसिंह तीर्थ।',
      },
    },
  },
  {
    id: 'chinnamalai-sundararaja-senjerimalai',
    name: 'Chinnamalai Sri Sundararaja Perumal Temple, Senjerimalai',
    city: 'Senjerimalai (Coimbatore/Sulur)',
    state: 'Tamil Nadu',
    image: '',
    period: 'Ancient hill temple',
    category: 'Vishnu',
    designation: '',
    history: 'Chinnamalai Sri Sundararaja Perumal Temple is a picturesque hill temple located at Senjerimalai near Sulur in Coimbatore district. Presiding deity Sundararaja Perumal stands atop the scenic hillock surrounded by verdant nature. Worshippers climb the hill to pray for child boon, rainfall, and peace of mind.',
    timings: '7:00 AM – 12:00 PM | 4:30 PM – 7:30 PM',
    festivals: ['Purattasi Saturdays', 'Vaikunta Ekadasi', 'Panguni Uthiram'],
    significance: 'Scenic hill shrine of Lord Vishnu in Coimbatore rural countryside, bestowing health and agricultural prosperity.',
    mapsUrl: 'https://maps.google.com/?q=Sundararaja+Perumal+Temple+Senjerimalai+Coimbatore',
    sourceUrl: 'https://www.visittemples.com/hindu/chinnamalaisrisundararajaperumaltemplesenjerimalaicoimbatoredistricttamilnadu',
    lat: 10.8920, lng: 77.1610,
    translations: {
      ta: {
        name: 'சின்னமலை அருள்மிகு சுந்தரராஜ பெருமாள் திருக்கோயில், செஞ்சேரிமலை',
        city: 'செஞ்சேரிமலை (கோவை)',
        state: 'தமிழ்நாடு',
        category: 'விஷ்ணு',
        designation: '',
        history: 'கோவை மாவட்டம் சூலூர் அருகே செஞ்சேரிமலையில் அமைந்துள்ள இயற்கை எழில் சூழ்ந்த மலைக் கோயில். மூலவர் சுந்தரராஜ பெருமாள். மழை வளம் மற்றும் குடும்ப நலன் வேண்டி பக்தர்கள் இம்மலை ஏறி வழிபடுகின்றனர்.',
        timings: 'காலை 7:00 – 12:00 | மாலை 4:30 – 7:30',
        festivals: ['புரட்டாசி சனிக்கிழமைகள்', 'வைகுண்ட ஏகாதசி'],
        significance: 'செஞ்சேரிமலை மீது அருள்பாலிக்கும் சுந்தரராஜ பெருமாள் கோயில்.',
      },
      hi: {
        name: 'चिन्नमलई श्री सौंदरराज पेरुमाल मंदिर, सेन्जेरीमलई',
        city: 'सेन्जेरीमलई (कोयंबटूर)',
        state: 'तमिलनाडु',
        category: 'विष्णु',
        designation: '',
        history: 'कोयंबटूर के पास सेन्जेरीमलई पहाड़ी पर स्थित सुंदर विष्णु मंदिर। प्राकृतिक सुंदरता और शांति का पावन स्थल।',
        timings: 'प्रातः 7:00 – 12:00 | सायं 4:30 – 7:30',
        festivals: ['पुरट्टासी शनिवार', 'वैकुंठ एकादशी'],
        significance: 'पहाड़ी पर स्थित सुंदर सौंदरराज पेरुमाल मंदिर।',
      },
    },
  },
];

let tamilnaduCode = fs.readFileSync('src/data/tamilnaduTemples.js', 'utf8');
const lastIndexTamilnadu = tamilnaduCode.lastIndexOf('];');
if (lastIndexTamilnadu !== -1) {
  const newItemsStr = ',\n' + JSON.stringify(tamilnaduAdditions, null, 2).slice(1, -1).trim() + '\n';
  tamilnaduCode = tamilnaduCode.slice(0, lastIndexTamilnadu) + newItemsStr + tamilnaduCode.slice(lastIndexTamilnadu);
  fs.writeFileSync('src/data/tamilnaduTemples.js', tamilnaduCode, 'utf8');
  console.log('Successfully appended 10 temples to tamilnaduTemples.js');
}

console.log('ALL VISITTEMPLES ADDED CLEANLY WITHOUT DUPLICATES!');
