const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/data/chennaiTemples.js');
let content = fs.readFileSync(filePath, 'utf8');

const coords = {
  'kapaleeshwarar-chennai': { lat: 13.0336, lng: 80.2699 },
  'parthasarathy-triplicane': { lat: 13.0537, lng: 80.2771 },
  'marundeeswarar-thiruvanmiyur': { lat: 12.9863, lng: 80.2592 },
  'ashtabhuja-kochi-perumal-thiruneermalai': { lat: 12.9602, lng: 80.1139 },
  'vadapalani-murugan': { lat: 13.0524, lng: 80.2127 },
  'ashtabhuja-perumal-thirukoshtiyur': { lat: 13.0722, lng: 80.1945 },
  'ashtalakshmi-besant-nagar': { lat: 12.9972, lng: 80.2689 },
  'kalikambal-temple-chennai': { lat: 13.0903, lng: 80.2882 },
  'thiruvottriyur-thyagaraja': { lat: 13.1611, lng: 80.3015 },
  'vedapureeswaran-purasaiwakkam': { lat: 13.0889, lng: 80.2536 },
  'mangadu-kamakshi-amman': { lat: 13.0416, lng: 80.1166 },
  'pallikondeswarar-poonamallee': { lat: 12.7633, lng: 80.2411 },
  'arulmigu-dhakshinamurthy-nanganallur': { lat: 12.9833, lng: 80.1917 },
  'sri-vari-kovil-thirumullaivoyal': { lat: 13.1311, lng: 80.1389 },
  'ammapettai-muneeswarar': { lat: 13.0933, lng: 80.2797 },
  'ambattur-shiva-temple': { lat: 13.1144, lng: 80.1548 },
  'bhaktavatsala-perumal-thiruninravur': { lat: 13.1190, lng: 80.0320 },
  'hridayaleeswarar-thiruninravur': { lat: 13.1150, lng: 80.0180 },
  'veeraraghava-perumal-thiruvallur': { lat: 13.1432, lng: 79.9060 },
  'veerapureeswarar-thiruvallur': { lat: 13.1450, lng: 79.9080 },
  'vadaranyeswarar-thiruvalangadu': { lat: 13.1200, lng: 79.7750 },
  'pasupatheeswarar-thirupachur': { lat: 13.1420, lng: 79.8850 }
};

for (const [id, coord] of Object.entries(coords)) {
  const regex = new RegExp(`(id:\\s*'${id}',\\s*\\n\\s*name:\\s*['"][^'"]+['"],\\s*\\n\\s*city:\\s*['"][^'"]+['"],\\s*\\n\\s*state:\\s*['"][^'"]+['"],)`, 'g');
  if (regex.test(content)) {
    content = content.replace(regex, `$1\n    lat: ${coord.lat},\n    lng: ${coord.lng},`);
    console.log(`Updated coords for ${id}`);
  } else {
    console.warn(`Could not match ${id}`);
  }
}

const pallikaranaiTemples = `  {
    id: 'sri-lakshminarayana-perumal-pallikaranai',
    name: 'Sri Lakshmi Narayana Perumal Temple, Pallikaranai',
    city: 'Chennai (Pallikaranai)',
    state: 'Tamil Nadu',
    lat: 12.9372,
    lng: 80.2145,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Parthasarathi_temple_Triplicane.jpg/800px-Parthasarathi_temple_Triplicane.jpg',
    period: '12th–13th Century CE (Later Chola Dynasty)',
    category: 'Vishnu',
    designation: 'Ancient Chola Temple & Abimana Sthalam',
    history: 'Sri Lakshmi Narayana Perumal Temple at Pallikaranai is an ancient temple dating back to the 12th–13th century Chola period, when Pallikaranai was historically known as Madura Lakshmi Narayanapuram. Lord Vishnu is consecrated as Lakshmi Narayana Perumal in a peaceful seated posture, with Goddess Mahalakshmi seated lovingly on His left lap. The temple is revered as an Abimana Sthalam and preserves rare Chola-era sculptural details, a sacred dwajasthambam, garuda mandapam, and an active pooja tradition.',
    timings: 'Morning: 7:00 AM – 11:00 AM | Evening: 5:00 PM – 8:30 PM',
    festivals: ['Vaikunta Ekadasi', 'Chithirai Brahmotsavam', 'Krishna Janmashtami', 'Purattasi Saturdays', 'Thirukarthigai'],
    significance: 'Ancient Chola period temple in South Chennai. Abimana sthalam with Lord Vishnu holding Mahalakshmi on His lap, bestowing wealth, family harmony, and spiritual liberation.',
    mapsUrl: 'https://maps.google.com/?q=Sri+Lakshminarayana+Perumal+Temple+Pallikaranai+Chennai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pallikaranai',
    translations: {
      ta: {
        name: 'ஸ்ரீ லட்சுமி நாராயண பெருமாள் திருக்கோயில், பள்ளிக்கரணை',
        city: 'சென்னை (பள்ளிக்கரணை)',
        state: 'தமிழ்நாடு',
        period: '12-13 ஆம் நூற்றாண்டு (பிற்கால சோழர் காலம்)',
        category: 'விஷ்ணு',
        designation: 'பண்டைய சோழர் கோயில் & அபிமான ஸ்தலம்',
        history: 'பள்ளிக்கரணையில் அமைந்துள்ள ஸ்ரீ லட்சுமி நாராயண பெருமாள் திருக்கோயில் 12-13 ஆம் நூற்றாண்டு சோழர் காலத்து வரலாற்றுச் சிறப்புமிக்க கோயிலாகும். பழங்காலத்தில் இவ்வூர் "மதுரா லட்சுமி நாராயணபுரம்" என்று அழைக்கப்பட்டது. பெருமாள் மகாலட்சுமியை தன் மடியில் அமர்த்தி லட்சுமி நாராயணராக அமர்ந்த கோலத்தில் திருக்காட்சி தருகிறார். அபிமான ஸ்தலமாக போற்றப்படும் இக்கோயிலில் சோழர் கால சிற்ப வேலைப்பாடுகளும் பிரம்மோற்சவ விழாக்களும் சிறப்பானவை.',
        timings: 'காலை: 7:00 – 11:00 | மாலை: 5:00 – 8:30',
        festivals: ['வைகுண்ட ஏகாதசி', 'சித்திரை பிரம்மோற்சவம்', 'கிருஷ்ண ஜெயந்தி', 'புரட்டாசி சனிக்கிழமைகள்'],
        significance: 'தென் சென்னையின் தொன்மையான சோழர் கால வைணவ தலம். லட்சுமி நாராயணரை வழிபட குடும்ப நல்வாழ்வும் தனதான்ய விருத்தியும் கிட்டும்.',
      },
      hi: {
        name: 'श्री लक्ष्मीनारायण पेरुमल मंदिर, पल्लिकरणई',
        city: 'चेन्नई (पल्लिकरणई)',
        state: 'तमिलनाडु',
        period: '12वीं-13वीं शताब्दी (चोल काल)',
        category: 'विष्णु',
        designation: 'प्राचीन चोल मंदिर एवं अभिमान स्थलम्',
        history: 'पल्लिकरणई का श्री लक्ष्मीनारायण पेरुमल मंदिर 12वीं-13वीं शताब्दी के चोल काल का है। प्राचीन काल में इसे मधुरा लक्ष्मीनारायणपुरम के नाम से जाना जाता था। यहाँ भगवान विष्णु देवी महालक्ष्मी को अपनी बाईं गोद में बैठाए पद्मासन में विराजमान हैं।',
        timings: 'प्रातः: 7:00 – 11:00 | सायं: 5:00 – 8:30',
        festivals: ['वैकुंठ एकादशी', 'चित्तिरई ब्रह्मोत्सव', 'कृष्ण जन्माष्टमी'],
        significance: 'प्राचीन चोल कालीन मंदिर। परिवार कल्याण और समृद्धि हेतु अत्यंत पावन।',
      },
    },
  },
  {
    id: 'sri-adhipureeswarar-pallikaranai',
    name: 'Sri Athipureeswarar Temple, Pallikaranai',
    city: 'Chennai (Pallikaranai)',
    state: 'Tamil Nadu',
    lat: 12.9351,
    lng: 80.2118,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Thiruvanmiyur_Marundeeswarar_Temple.jpg/800px-Thiruvanmiyur_Marundeeswarar_Temple.jpg',
    period: 'Ancient Shiva Sthalam (rebuilt with 3-tier Rajagopuram)',
    category: 'Shiva',
    designation: 'Historic Swayambhu Shiva Temple of South Chennai',
    history: 'Sri Athipureeswarar (Adhipureeswarar) Temple in Pallikaranai is situated prominently on the Velachery to Tambaram Main Road. Dedicated to Lord Shiva as Athipureeswarar (a Swayambhu Lingam) and His divine consort Goddess Sri Shantha Nayagi. The temple features a graceful three-tiered Rajagopuram, an adhisthana, koshtas housing Dakshinamurthy, Mahavishnu/Lingodhbhavar, Brahma, and Durga, and a serene temple theertham (tank) with a walking track. Sub-shrines include Lord Ganesha, Murugan with Valli & Devasena, Bhairavar, and the Navagrahas.',
    timings: 'Morning: 6:00 AM – 11:30 AM | Evening: 4:30 PM – 8:30 PM',
    festivals: ['Maha Shivaratri', 'Arudra Darshan', 'Pradosham (bimonthly)', 'Panguni Uthiram', 'Aani Thirumanjanam'],
    significance: 'Ancient Swayambhu Shiva temple with Goddess Shantha Nayagi in Pallikaranai. Beautiful temple tank and three-tiered Rajagopuram on Velachery-Tambaram highway.',
    mapsUrl: 'https://maps.google.com/?q=Athipureeswarar+Temple+Pallikaranai+Chennai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pallikaranai',
    translations: {
      ta: {
        name: 'ஸ்ரீ அதிபுரீஸ்வரர் திருக்கோயில், பள்ளிக்கரணை',
        city: 'சென்னை (பள்ளிக்கரணை)',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய சிவாலயம் (3 நிலை ராஜகோபுரம்)',
        category: 'சிவன்',
        designation: 'தென் சென்னையின் தொன்மை சுயம்பு சிவாலயம்',
        history: 'வேளச்சேரி - தாம்பரம் பிரதான சாலையில் அமைந்துள்ள அருள்மிகு அதிபுரீஸ்வரர் திருக்கோயில் பள்ளிக்கரணையின் பழமையான சிவாலயமாகும். இறைவன் ஸ்ரீ அதிபுரீஸ்வரர் சுயம்பு லிங்க மூர்த்தியாகவும், அம்பாள் ஸ்ரீ சாந்த நாயகி சாந்த சொரூபியாகவும் அருள்பாலிக்கின்றனர். மூன்று நிலை ராஜகோபுரம், திருக்குளம், தட்சிணாமூர்த்தி, லிங்கோத்பவர், பிரம்மா, துர்க்கை கோஷ்டங்களும், விநாயகர், வள்ளி-தெய்வானை சமேத முருகப்பெருமான், பைரவர் மற்றும் நவகிரக சன்னதிகளும் இங்கு அமைந்துள்ளன.',
        timings: 'காலை: 6:00 – 11:30 | மாலை: 4:30 – 8:30',
        festivals: ['மகா சிவராத்திரி', 'ஆருத்ரா தரிசனம்', 'பிரதோஷம்', 'பங்குனி உத்திரம்'],
        significance: 'சுயம்பு லிங்க மூர்த்தியாக அதிபுரீஸ்வரரும் சாந்த நாயகி அம்மனும் அருளும் திருத்தலம். அழகான திருக்குளம் கொண்ட ஆலயம்.',
      },
      hi: {
        name: 'श्री अथिपुरीश्वरर मंदिर, पल्लिकरणई',
        city: 'चेन्नई (पल्लिकरणई)',
        state: 'तमिलनाडु',
        period: 'प्राचीन शिव मंदिर',
        category: 'शिव',
        designation: 'स्वयंभू शिव मंदिर',
        history: 'वेलचेरी-तांबरम मुख्य मार्ग पर स्थित यह मंदिर भगवान शिव (अथिपुरीश्वरर - स्वयंभू लिंग) और देवी शांता नायकी को समर्पित है। मंदिर में तीन मंजिला राजगोपुरम और एक सुंदर पुष्करिणी (तालाब) है।',
        timings: 'प्रातः: 6:00 – 11:30 | सायं: 4:30 – 8:30',
        festivals: ['महाशिवरात्रि', 'प्रदोषम', 'आरुद्रा दर्शन'],
        significance: 'पल्लिकरणई का ऐतिहासिक स्वयंभू शिव मंदिर।',
      },
    },
  },
  {
    id: 'pidari-veerathamman-pallikaranai',
    name: 'Arulmigu Pidari Veerathamman Temple, Pallikaranai',
    city: 'Chennai (Pallikaranai)',
    state: 'Tamil Nadu',
    lat: 12.9338,
    lng: 80.2152,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Mangadu_temple_gopuram.jpg/800px-Mangadu_temple_gopuram.jpg',
    period: 'Ancient Gramadevathai Tradition',
    category: 'Shakti',
    designation: 'Ellai Kaval Deivam & Kulatheivam of 7 Surrounding Villages',
    history: 'Arulmigu Pidari Veerathamman Temple in Pallikaranai is the ancient guardian deity (Ellai Kaval Deivam) and Gramadevathai protecting the Pallikaranai wetland and residential belt. The Goddess is the revered Kulatheivam for families across seven traditional surrounding villages. Devotees offer pongal, maavilakku, and seek blessings for family protection, health, and protection from negative influences.',
    timings: 'Morning: 6:00 AM – 12:00 PM | Evening: 5:00 PM – 8:30 PM (Tuesdays & Fridays extended)',
    festivals: ['Aadi Thiruvizha', 'Navaratri', 'Chithirai Festival', 'Thai Pongal', 'Aadi Velli'],
    significance: 'Revered Ellai Kaval Deivam (guardian deity) and Gramadevathai of Pallikaranai, serving as Kuladeivam for seven surrounding villages.',
    mapsUrl: 'https://maps.google.com/?q=Veerathamman+Temple+Pallikaranai+Chennai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pallikaranai',
    translations: {
      ta: {
        name: 'அருள்மிகு பிடாரி வீரத்தம்மன் திருக்கோயில், பள்ளிக்கரணை',
        city: 'சென்னை (பள்ளிக்கரணை)',
        state: 'தமிழ்நாடு',
        period: 'பண்டைய கிராம தேவதை மரபு',
        category: 'சக்தி',
        designation: 'எல்லை காவல் தெய்வம் & ஏழு கிராம குலதெய்வம்',
        history: 'பள்ளிக்கரணையின் பழமையான எல்லை காவல் தெய்வமாகவும் கிராம தேவதையாகவும் அருள்மிகு பிடாரி வீரத்தம்மன் விளங்குகிறார். பள்ளிக்கரணையைச் சுற்றியுள்ள ஏழு கிராம மக்களின் குலதெய்வமாக வீற்றிருக்கும் அன்னை வீரத்தம்மனுக்கு ஆடி மாத திருவிழா, பொங்கல் வைத்தல், மாவிளக்கு எடுத்தல் போன்ற வழிபாடுகள் மிக விமரிசையாக நடைபெறும்.',
        timings: 'காலை: 6:00 – 12:00 | மாலை: 5:00 – 8:30',
        festivals: ['ஆடி திருவிழா', 'நவராத்திரி', 'சித்திரை பெருவிழா', 'ஆடி வெள்ளி'],
        significance: 'ஏழு கிராம மக்களின் குலதெய்வம். தீவினைகள் அகற்றி குடும்பத்தைக் காக்கும் சக்தி வாய்ந்த காவல் தெய்வம்.',
      },
      hi: {
        name: 'अरुलमिगु पिडारी वीरथम्मन मंदिर, पल्लिकरणई',
        city: 'चेन्नई (पल्लिकरणई)',
        state: 'तमिलनाडु',
        period: 'प्राचीन ग्राम देवता परंपरा',
        category: 'शक्ति',
        designation: 'ग्राम संरक्षक देवी एवं कुलदेवी',
        history: 'पल्लिकरणई की प्राचीन संरक्षक देवी (एल्लै कावल दैवम)। यह देवी आसपास के सात गांवों के परिवारों की कुलदेवी मानी जाती हैं।',
        timings: 'प्रातः: 6:00 – 12:00 | सायं: 5:00 – 8:30',
        festivals: ['आदि तिरुविझा', 'नवरात्रि', 'थाई पोंगल'],
        significance: 'सात गांवों की पूज्य कुलदेवी एवं संरक्षक शक्ति।',
      },
    },
  },
  {
    id: 'annai-adhi-parasakthi-pallikaranai',
    name: 'Arulmigu Annai Adhi Parasakthi Temple, Pallikaranai',
    city: 'Chennai (Pallikaranai)',
    state: 'Tamil Nadu',
    lat: 12.9380,
    lng: 80.2180,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Chennai_Kaligambal_Temple.jpg/800px-Chennai_Kaligambal_Temple.jpg',
    period: 'Established 1984',
    category: 'Shakti',
    designation: 'Sakthi Peedam & Spiritual Centre',
    history: 'Established in 1984, the Annai Adhi Parasakthi Temple in Pallikaranai is a vibrant spiritual centre dedicated to Mother Adhiparasakthi. The temple conducts regular sakthi poojas, pournami vilakku poojas, and charitable welfare activities. It serves as a major congregation point for Adhiparasakthi devotees during the annual Irumudi and Thai Poosam pilgrimage seasons.',
    timings: 'Morning: 6:00 AM – 12:00 PM | Evening: 4:30 PM – 8:30 PM',
    festivals: ['Thai Poosam & Irumudi', 'Chitra Pournami', 'Navaratri', 'Aadi Pooram'],
    significance: 'Prominent Adhi Parasakthi temple in South Chennai known for devotion, service, and Pournami lamps.',
    mapsUrl: 'https://maps.google.com/?q=Adhi+Parasakthi+Temple+Pallikaranai+Chennai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pallikaranai',
    translations: {
      ta: {
        name: 'அருள்மிகு அன்னை ஆதிபராசக்தி திருக்கோயில், பள்ளிக்கரணை',
        city: 'சென்னை (பள்ளிக்கரணை)',
        state: 'தமிழ்நாடு',
        period: '1984-ல் நிறுவப்பட்டது',
        category: 'சக்தி',
        designation: 'சக்தி பீடம் & ஆன்மீக மையம்',
        history: '1984 ஆம் ஆண்டு நிறுவப்பட்ட பள்ளிக்கரணை அன்னை ஆதிபராசக்தி ஆலயம் தென் சென்னையின் முக்கிய சக்தி வழிபாட்டுத் தலமாகும். பௌர்ணமி விளக்கு பூஜை, அன்னதானம், இருமுடி செலுத்தும் வைபவங்கள் இங்கு பக்தியுடன் நடத்தப்படுகின்றன.',
        timings: 'காலை: 6:00 – 12:00 | மாலை: 4:30 – 8:30',
        festivals: ['தைப்பூசம் இருமுடி விழா', 'சித்ரா பௌர்ணமி', 'நவராத்திரி', 'ஆடிப் பூரம்'],
        significance: 'பௌர்ணமி விளக்கு பூஜை மற்றும் இருமுடி வழிபாட்டிற்கு புகழ்பெற்ற சக்தி பீடம்.',
      },
      hi: {
        name: 'अन्नाई आदि पराशक्ति मंदिर, पल्लिकरणई',
        city: 'चेन्नई (पल्लिकरणई)',
        state: 'तमिलनाडु',
        period: '1984 में स्थापित',
        category: 'शक्ति',
        designation: 'शक्ति पीठ',
        history: '1984 में स्थापित यह मंदिर देवी आदि पराशक्ति को समर्पित एक प्रसिद्ध आध्यात्मिक केंद्र है। यहाँ पूर्णिमा दीप पूजा और इरुमुडी उत्सव बड़े उत्साह से मनाए जाते हैं।',
        timings: 'प्रातः: 6:00 – 12:00 | सायं: 4:30 – 8:30',
        festivals: ['थाई पूसम', 'चित्रा पूर्णिमा', 'नवरात्रि'],
        significance: 'पूर्णिमा दीप पूजा और समाज सेवा के लिए प्रसिद्ध शक्ति मंदिर।',
      },
    },
  },
  {
    id: 'selva-vinayagar-pallikaranai',
    name: 'Arulmigu Sri Selva Vinayagar Temple, Pallikaranai',
    city: 'Chennai (Pallikaranai)',
    state: 'Tamil Nadu',
    lat: 12.9340,
    lng: 80.2125,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Padi_sivam.jpg/800px-Padi_sivam.jpg',
    period: 'Traditional Community Shrine',
    category: 'Ganesh',
    designation: 'Popular Vignaharta Shrine in Pallikaranai',
    history: 'Arulmigu Sri Selva Vinayagar Temple is a revered temple dedicated to Lord Ganesha located in Pallikaranai. As the remover of obstacles and bestower of auspicious beginnings (Selvam = prosperity), devotees begin new ventures, vehicle registrations, and educational milestones with special archana here.',
    timings: 'Morning: 6:30 AM – 11:30 AM | Evening: 5:00 PM – 8:30 PM',
    festivals: ['Vinayaka Chaturthi (grand celebrations)', 'Sankatahara Chaturthi (monthly)', 'Tamil New Year'],
    significance: 'Auspicious Vinayagar temple in Pallikaranai for prosperity and overcoming obstacles.',
    mapsUrl: 'https://maps.google.com/?q=Selva+Vinayagar+Temple+Pallikaranai+Chennai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pallikaranai',
    translations: {
      ta: {
        name: 'அருள்மிகு செல்வ விநாயகர் ஆலயம், பள்ளிக்கரணை',
        city: 'சென்னை (பள்ளிக்கரணை)',
        state: 'தமிழ்நாடு',
        period: 'மரபுவழி விநாயகர் ஆலயம்',
        category: 'விநாயகர்',
        designation: 'விக்னங்களை தீர்க்கும் செல்வ விநாயகர்',
        history: 'பள்ளிக்கரணையில் அமைந்துள்ள அருள்மிகு செல்வ விநாயகர் திருக்கோயில், பக்தர்களின் தடைகளை அகற்றி காரிய சித்தி அருளும் ஆலயம். புதுமனை புகுவிழா, புதிய தொழில் தொடங்குவோர், வாகன பூஜை செய்வோர் இங்கு சங்கல்பம் செய்து வழிபடுகின்றனர்.',
        timings: 'காலை: 6:30 – 11:30 | மாலை: 5:00 – 8:30',
        festivals: ['விநாயகர் சதுர்த்தி', 'சங்கடஹர சதுர்த்தி', 'தமிழ் புத்தாண்டு'],
        significance: 'காரியத்தடை நீக்கும் செல்வ விநாயகர் சன்னதி.',
      },
      hi: {
        name: 'श्री सेल्वा विनायक मंदिर, पल्लिकरणई',
        city: 'चेन्नई (पल्लिकरणई)',
        state: 'तमिलनाडु',
        period: 'पारंपरिक मंदिर',
        category: 'गणेश',
        designation: 'विघ्नहर्ता गणेश मंदिर',
        history: 'पल्लिकरणई में स्थित भगवान गणेश का लोकप्रिय मंदिर। नए कार्यों की शुरुआत और वाहन पूजा हेतु श्रद्धालु यहाँ आते हैं।',
        timings: 'प्रातः: 6:30 – 11:30 | सायं: 5:00 – 8:30',
        festivals: ['विनायक चतुर्थी', 'संकष्टी चतुर्थी'],
        significance: 'विघ्न निवारण और समृद्धि हेतु प्रसिद्ध।',
      },
    },
  },
  {
    id: 'panchami-varahi-pallikaranai',
    name: 'Sri Panchami Varahi Samedha Manoonmaneeswarar Temple, Pallikaranai',
    city: 'Chennai (Pallikaranai)',
    state: 'Tamil Nadu',
    lat: 12.9360,
    lng: 80.2160,
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Ashtalakshmi_Temple_Chennai.jpg/800px-Ashtalakshmi_Temple_Chennai.jpg',
    period: 'Modern Sthalam',
    category: 'Shakti',
    designation: 'Sri Varahi & Lord Manoonmaneeswarar Shrine',
    history: 'Sri Panchami Varahi Samedha Manoonmaneeswarar Temple in Pallikaranai is dedicated to Sri Maha Varahi Amman—one of the Sapta Matrikas and commander-in-chief of Goddess Lalitha Tripurasundari—along with Lord Shiva as Manoonmaneeswarar. It is renowned across South Chennai for powerful remedies against obstacles, court cases, negative energies, and business hurdles. Devotees throng the temple on Panchami, Ashtami, and Amavasya days to light pomegranate and coconut lamps.',
    timings: 'Morning: 6:30 AM – 12:00 PM | Evening: 4:30 PM – 8:30 PM (Panchami/Ashtami days extended)',
    festivals: ['Varahi Navaratri (Ashada Navaratri)', 'Panchami Tithi poojas', 'Maha Shivaratri', 'Navaratri'],
    significance: 'Powerful Varahi Amman shrine in South Chennai, famous for special Panchami homams and deepa poojas.',
    mapsUrl: 'https://maps.google.com/?q=Sri+Varahi+Temple+Pallikaranai+Chennai',
    sourceUrl: 'https://en.wikipedia.org/wiki/Pallikaranai',
    translations: {
      ta: {
        name: 'ஸ்ரீ பஞ்சமி வாராஹி சமேத மனோன்மணீஸ்வரர் திருக்கோயில், பள்ளிக்கரணை',
        city: 'சென்னை (பள்ளிக்கரணை)',
        state: 'தமிழ்நாடு',
        period: 'சக்தி வாய்ந்த பரிகார தலம்',
        category: 'சக்தி',
        designation: 'ஸ்ரீ வாராஹி மற்றும் மனோன்மணீஸ்வரர் ஆலயம்',
        history: 'பள்ளிக்கரணையில் அமைந்துள்ள ஸ்ரீ பஞ்சமி வாராஹி சமேத மனோன்மணீஸ்வரர் ஆலயம் தென் சென்னையின் புகழ்பெற்ற வாராஹி வழிபாட்டுத் தலமாகும். அன்னை லலிதா பரமேஸ்வரியின் படைத்தளபதியான ஸ்ரீ வாராஹி அம்மனை பஞ்சமி மற்றும் அஷ்டமி திதிகளில் பூசணி, தேங்காய் விளக்கு ஏற்றி வழிபடுவது விசேஷம்.',
        timings: 'காலை: 6:30 – 12:00 | மாலை: 4:30 – 8:30',
        festivals: ['ஆஷாட நவராத்திரி (வாராஹி நவராத்திரி)', 'பஞ்சமி திதி ஹோமங்கள்', 'மகா சிவராத்திரி'],
        significance: 'வழக்குகள், கடன் சுமை, திருஷ்டி தோஷங்கள் நீங்க பஞ்சமி திதியில் வாராஹி அம்மனை வழிபடும் சக்தி தலம்.',
      },
      hi: {
        name: 'श्री पंचमी वाराही समेध मनोन्मणीश्वरर मंदिर, पल्लिकरणई',
        city: 'चेन्नई (पल्लिकरणई)',
        state: 'तमिलनाडु',
        period: 'प्रसिद्ध शक्ति पीठ',
        category: 'शक्ति',
        designation: 'माँ वाराही एवं शिव मंदिर',
        history: 'पल्लिकरणई में स्थित माँ वाराही और भगवान शिव (मनोन्मणीश्वरर) का पावन मंदिर। बाधाओं के निवारण और मुकदमों में विजय हेतु पंचमी और अष्टमी पर श्रद्धालु विशेष दीप पूजा करते हैं।',
        timings: 'प्रातः: 6:30 – 12:00 | सायं: 4:30 – 8:30',
        festivals: ['वाराही नवरात्रि', 'पंचमी हवन', 'महाशिवरात्रि'],
        significance: 'कष्ट निवारक माँ वाराही की दिव्य आराधना का केंद्र।',
      },
    },
  },
`;

const lastBracketIndex = content.lastIndexOf('];');
if (lastBracketIndex !== -1) {
  content = content.slice(0, lastBracketIndex) + pallikaranaiTemples + content.slice(lastBracketIndex);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Successfully updated chennaiTemples.js!');
} else {
  console.error('Could not find closing bracket in chennaiTemples.js');
}
